// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ConnectionSecuring.proto

package net.iGap.proto;

public final class ProtoConnectionSecuring {
  private ProtoConnectionSecuring() {
  }

  public static void registerAllExtensions(com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions((com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ConnectionSecuringResponseOrBuilder extends
          // @@protoc_insertion_point(interface_extends:proto.ConnectionSecuringResponse)
          com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional .proto.Response response = 1;</code>
     */
    boolean hasResponse();
    /**
     * <code>optional .proto.Response response = 1;</code>
     */
    ProtoResponse.Response getResponse();
    /**
     * <code>optional .proto.Response response = 1;</code>
     */
    ProtoResponse.ResponseOrBuilder getResponseOrBuilder();

    /**
     * <code>optional string public_key = 2;</code>
     */
    String getPublicKey();
    /**
     * <code>optional string public_key = 2;</code>
     */
    com.google.protobuf.ByteString getPublicKeyBytes();

    /**
     * <code>optional uint32 symmetric_key_length = 3;</code>
     */
    int getSymmetricKeyLength();

    /**
     * <code>optional uint32 heartbeat_interval = 4;</code>
     */
    int getHeartbeatInterval();

    /**
     * <code>optional string primary_node_name = 5;</code>
     */
    String getPrimaryNodeName();
    /**
     * <code>optional string primary_node_name = 5;</code>
     */
    com.google.protobuf.ByteString getPrimaryNodeNameBytes();

    /**
     * <code>optional uint32 secondary_chunk_size = 6;</code>
     */
    int getSecondaryChunkSize();
  }
  /**
   * Protobuf type {@code proto.ConnectionSecuringResponse}
   */
  public static final class ConnectionSecuringResponse extends com.google.protobuf.GeneratedMessageV3 implements
          // @@protoc_insertion_point(message_implements:proto.ConnectionSecuringResponse)
          ConnectionSecuringResponseOrBuilder {
    // Use ConnectionSecuringResponse.newBuilder() to construct.
    private ConnectionSecuringResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ConnectionSecuringResponse() {
      publicKey_ = "";
      symmetricKeyLength_ = 0;
      heartbeatInterval_ = 0;
      primaryNodeName_ = "";
      secondaryChunkSize_ = 0;
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }

    private ConnectionSecuringResponse(com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              ProtoResponse.Response.Builder subBuilder = null;
              if (response_ != null) {
                subBuilder = response_.toBuilder();
              }
              response_ = input.readMessage(ProtoResponse.Response.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(response_);
                response_ = subBuilder.buildPartial();
              }

              break;
            }
            case 18: {
              String s = input.readStringRequireUtf8();

              publicKey_ = s;
              break;
            }
            case 24: {

              symmetricKeyLength_ = input.readUInt32();
              break;
            }
            case 32: {

              heartbeatInterval_ = input.readUInt32();
              break;
            }
            case 42: {
              String s = input.readStringRequireUtf8();

              primaryNodeName_ = s;
              break;
            }
            case 48: {

              secondaryChunkSize_ = input.readUInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }

    public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
      return ProtoConnectionSecuring.internal_static_proto_ConnectionSecuringResponse_descriptor;
    }

    protected FieldAccessorTable internalGetFieldAccessorTable() {
      return ProtoConnectionSecuring.internal_static_proto_ConnectionSecuringResponse_fieldAccessorTable.ensureFieldAccessorsInitialized(ConnectionSecuringResponse.class, Builder.class);
    }

    public static final int RESPONSE_FIELD_NUMBER = 1;
    private ProtoResponse.Response response_;
    /**
     * <code>optional .proto.Response response = 1;</code>
     */
    public boolean hasResponse() {
      return response_ != null;
    }
    /**
     * <code>optional .proto.Response response = 1;</code>
     */
    public ProtoResponse.Response getResponse() {
      return response_ == null ? ProtoResponse.Response.getDefaultInstance() : response_;
    }
    /**
     * <code>optional .proto.Response response = 1;</code>
     */
    public ProtoResponse.ResponseOrBuilder getResponseOrBuilder() {
      return getResponse();
    }

    public static final int PUBLIC_KEY_FIELD_NUMBER = 2;
    private volatile Object publicKey_;
    /**
     * <code>optional string public_key = 2;</code>
     */
    public String getPublicKey() {
      Object ref = publicKey_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        publicKey_ = s;
        return s;
      }
    }
    /**
     * <code>optional string public_key = 2;</code>
     */
    public com.google.protobuf.ByteString getPublicKeyBytes() {
      Object ref = publicKey_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        publicKey_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SYMMETRIC_KEY_LENGTH_FIELD_NUMBER = 3;
    private int symmetricKeyLength_;
    /**
     * <code>optional uint32 symmetric_key_length = 3;</code>
     */
    public int getSymmetricKeyLength() {
      return symmetricKeyLength_;
    }

    public static final int HEARTBEAT_INTERVAL_FIELD_NUMBER = 4;
    private int heartbeatInterval_;
    /**
     * <code>optional uint32 heartbeat_interval = 4;</code>
     */
    public int getHeartbeatInterval() {
      return heartbeatInterval_;
    }

    public static final int PRIMARY_NODE_NAME_FIELD_NUMBER = 5;
    private volatile Object primaryNodeName_;
    /**
     * <code>optional string primary_node_name = 5;</code>
     */
    public String getPrimaryNodeName() {
      Object ref = primaryNodeName_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        primaryNodeName_ = s;
        return s;
      }
    }
    /**
     * <code>optional string primary_node_name = 5;</code>
     */
    public com.google.protobuf.ByteString getPrimaryNodeNameBytes() {
      Object ref = primaryNodeName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        primaryNodeName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SECONDARY_CHUNK_SIZE_FIELD_NUMBER = 6;
    private int secondaryChunkSize_;

    /**
     * <code>optional uint32 secondary_chunk_size = 6;</code>
     */
    public int getSecondaryChunkSize() {
      return secondaryChunkSize_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output) throws java.io.IOException {
      if (response_ != null) {
        output.writeMessage(1, getResponse());
      }
      if (!getPublicKeyBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, publicKey_);
      }
      if (symmetricKeyLength_ != 0) {
        output.writeUInt32(3, symmetricKeyLength_);
      }
      if (heartbeatInterval_ != 0) {
        output.writeUInt32(4, heartbeatInterval_);
      }
      if (!getPrimaryNodeNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, primaryNodeName_);
      }
      if (secondaryChunkSize_ != 0) {
        output.writeUInt32(6, secondaryChunkSize_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (response_ != null) {
        size += com.google.protobuf.CodedOutputStream.computeMessageSize(1, getResponse());
      }
      if (!getPublicKeyBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, publicKey_);
      }
      if (symmetricKeyLength_ != 0) {
        size += com.google.protobuf.CodedOutputStream.computeUInt32Size(3, symmetricKeyLength_);
      }
      if (heartbeatInterval_ != 0) {
        size += com.google.protobuf.CodedOutputStream.computeUInt32Size(4, heartbeatInterval_);
      }
      if (!getPrimaryNodeNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, primaryNodeName_);
      }
      if (secondaryChunkSize_ != 0) {
        size += com.google.protobuf.CodedOutputStream.computeUInt32Size(6, secondaryChunkSize_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ConnectionSecuringResponse)) {
        return super.equals(obj);
      }
      ConnectionSecuringResponse other = (ConnectionSecuringResponse) obj;

      boolean result = true;
      result = result && (hasResponse() == other.hasResponse());
      if (hasResponse()) {
        result = result && getResponse().equals(other.getResponse());
      }
      result = result && getPublicKey().equals(other.getPublicKey());
      result = result && (getSymmetricKeyLength() == other.getSymmetricKeyLength());
      result = result && (getHeartbeatInterval() == other.getHeartbeatInterval());
      result = result && getPrimaryNodeName().equals(other.getPrimaryNodeName());
      result = result && (getSecondaryChunkSize() == other.getSecondaryChunkSize());
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasResponse()) {
        hash = (37 * hash) + RESPONSE_FIELD_NUMBER;
        hash = (53 * hash) + getResponse().hashCode();
      }
      hash = (37 * hash) + PUBLIC_KEY_FIELD_NUMBER;
      hash = (53 * hash) + getPublicKey().hashCode();
      hash = (37 * hash) + SYMMETRIC_KEY_LENGTH_FIELD_NUMBER;
      hash = (53 * hash) + getSymmetricKeyLength();
      hash = (37 * hash) + HEARTBEAT_INTERVAL_FIELD_NUMBER;
      hash = (53 * hash) + getHeartbeatInterval();
      hash = (37 * hash) + PRIMARY_NODE_NAME_FIELD_NUMBER;
      hash = (53 * hash) + getPrimaryNodeName().hashCode();
      hash = (37 * hash) + SECONDARY_CHUNK_SIZE_FIELD_NUMBER;
      hash = (53 * hash) + getSecondaryChunkSize();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ConnectionSecuringResponse parseFrom(com.google.protobuf.ByteString data) throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }

    public static ConnectionSecuringResponse parseFrom(com.google.protobuf.ByteString data, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }

    public static ConnectionSecuringResponse parseFrom(byte[] data) throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }

    public static ConnectionSecuringResponse parseFrom(byte[] data, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }

    public static ConnectionSecuringResponse parseFrom(java.io.InputStream input) throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
    }

    public static ConnectionSecuringResponse parseFrom(java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static ConnectionSecuringResponse parseDelimitedFrom(java.io.InputStream input) throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(PARSER, input);
    }

    public static ConnectionSecuringResponse parseDelimitedFrom(java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }

    public static ConnectionSecuringResponse parseFrom(com.google.protobuf.CodedInputStream input) throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
    }

    public static ConnectionSecuringResponse parseFrom(com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }

    public static Builder newBuilder(ConnectionSecuringResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code proto.ConnectionSecuringResponse}
     */
    public static final class Builder extends com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
            // @@protoc_insertion_point(builder_implements:proto.ConnectionSecuringResponse)
            ConnectionSecuringResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ProtoConnectionSecuring.internal_static_proto_ConnectionSecuringResponse_descriptor;
      }

      protected FieldAccessorTable internalGetFieldAccessorTable() {
        return ProtoConnectionSecuring.internal_static_proto_ConnectionSecuringResponse_fieldAccessorTable.ensureFieldAccessorsInitialized(ConnectionSecuringResponse.class, Builder.class);
      }

      // Construct using net.iGap.proto.ProtoConnectionSecuring.ConnectionSecuringResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        if (responseBuilder_ == null) {
          response_ = null;
        } else {
          response_ = null;
          responseBuilder_ = null;
        }
        publicKey_ = "";

        symmetricKeyLength_ = 0;

        heartbeatInterval_ = 0;

        primaryNodeName_ = "";

        secondaryChunkSize_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
        return ProtoConnectionSecuring.internal_static_proto_ConnectionSecuringResponse_descriptor;
      }

      public ConnectionSecuringResponse getDefaultInstanceForType() {
        return ConnectionSecuringResponse.getDefaultInstance();
      }

      public ConnectionSecuringResponse build() {
        ConnectionSecuringResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public ConnectionSecuringResponse buildPartial() {
        ConnectionSecuringResponse result = new ConnectionSecuringResponse(this);
        if (responseBuilder_ == null) {
          result.response_ = response_;
        } else {
          result.response_ = responseBuilder_.build();
        }
        result.publicKey_ = publicKey_;
        result.symmetricKeyLength_ = symmetricKeyLength_;
        result.heartbeatInterval_ = heartbeatInterval_;
        result.primaryNodeName_ = primaryNodeName_;
        result.secondaryChunkSize_ = secondaryChunkSize_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }

      public Builder setField(com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }

      public Builder clearField(com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }

      public Builder clearOneof(com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }

      public Builder setRepeatedField(com.google.protobuf.Descriptors.FieldDescriptor field, int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }

      public Builder addRepeatedField(com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ConnectionSecuringResponse) {
          return mergeFrom((ConnectionSecuringResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ConnectionSecuringResponse other) {
        if (other == ConnectionSecuringResponse.getDefaultInstance()) return this;
        if (other.hasResponse()) {
          mergeResponse(other.getResponse());
        }
        if (!other.getPublicKey().isEmpty()) {
          publicKey_ = other.publicKey_;
          onChanged();
        }
        if (other.getSymmetricKeyLength() != 0) {
          setSymmetricKeyLength(other.getSymmetricKeyLength());
        }
        if (other.getHeartbeatInterval() != 0) {
          setHeartbeatInterval(other.getHeartbeatInterval());
        }
        if (!other.getPrimaryNodeName().isEmpty()) {
          primaryNodeName_ = other.primaryNodeName_;
          onChanged();
        }
        if (other.getSecondaryChunkSize() != 0) {
          setSecondaryChunkSize(other.getSecondaryChunkSize());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
        ConnectionSecuringResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ConnectionSecuringResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private ProtoResponse.Response response_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<ProtoResponse.Response, ProtoResponse.Response.Builder, ProtoResponse.ResponseOrBuilder> responseBuilder_;
      /**
       * <code>optional .proto.Response response = 1;</code>
       */
      public boolean hasResponse() {
        return responseBuilder_ != null || response_ != null;
      }
      /**
       * <code>optional .proto.Response response = 1;</code>
       */
      public ProtoResponse.Response getResponse() {
        if (responseBuilder_ == null) {
          return response_ == null ? ProtoResponse.Response.getDefaultInstance() : response_;
        } else {
          return responseBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .proto.Response response = 1;</code>
       */
      public Builder setResponse(ProtoResponse.Response value) {
        if (responseBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          response_ = value;
          onChanged();
        } else {
          responseBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>optional .proto.Response response = 1;</code>
       */
      public Builder setResponse(ProtoResponse.Response.Builder builderForValue) {
        if (responseBuilder_ == null) {
          response_ = builderForValue.build();
          onChanged();
        } else {
          responseBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>optional .proto.Response response = 1;</code>
       */
      public Builder mergeResponse(ProtoResponse.Response value) {
        if (responseBuilder_ == null) {
          if (response_ != null) {
            response_ = ProtoResponse.Response.newBuilder(response_).mergeFrom(value).buildPartial();
          } else {
            response_ = value;
          }
          onChanged();
        } else {
          responseBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>optional .proto.Response response = 1;</code>
       */
      public Builder clearResponse() {
        if (responseBuilder_ == null) {
          response_ = null;
          onChanged();
        } else {
          response_ = null;
          responseBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>optional .proto.Response response = 1;</code>
       */
      public ProtoResponse.Response.Builder getResponseBuilder() {
        
        onChanged();
        return getResponseFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .proto.Response response = 1;</code>
       */
      public ProtoResponse.ResponseOrBuilder getResponseOrBuilder() {
        if (responseBuilder_ != null) {
          return responseBuilder_.getMessageOrBuilder();
        } else {
          return response_ == null ? ProtoResponse.Response.getDefaultInstance() : response_;
        }
      }
      /**
       * <code>optional .proto.Response response = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<ProtoResponse.Response, ProtoResponse.Response.Builder, ProtoResponse.ResponseOrBuilder> getResponseFieldBuilder() {
        if (responseBuilder_ == null) {
          responseBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<ProtoResponse.Response, ProtoResponse.Response.Builder, ProtoResponse.ResponseOrBuilder>(
                  getResponse(),
                  getParentForChildren(),
                  isClean());
          response_ = null;
        }
        return responseBuilder_;
      }

      private Object publicKey_ = "";
      /**
       * <code>optional string public_key = 2;</code>
       */
      public String getPublicKey() {
        Object ref = publicKey_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          publicKey_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string public_key = 2;</code>
       */
      public com.google.protobuf.ByteString
          getPublicKeyBytes() {
        Object ref = publicKey_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((String) ref);
          publicKey_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string public_key = 2;</code>
       */
      public Builder setPublicKey(String value) {
        if (value == null) {
          throw new NullPointerException();
  }
  
        publicKey_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string public_key = 2;</code>
       */
      public Builder clearPublicKey() {
        
        publicKey_ = getDefaultInstance().getPublicKey();
        onChanged();
        return this;
      }
      /**
       * <code>optional string public_key = 2;</code>
       */
      public Builder setPublicKeyBytes(com.google.protobuf.ByteString value) {
        if (value == null) {
          throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        publicKey_ = value;
        onChanged();
        return this;
      }

      private int symmetricKeyLength_ ;
      /**
       * <code>optional uint32 symmetric_key_length = 3;</code>
       */
      public int getSymmetricKeyLength() {
        return symmetricKeyLength_;
      }
      /**
       * <code>optional uint32 symmetric_key_length = 3;</code>
       */
      public Builder setSymmetricKeyLength(int value) {
        
        symmetricKeyLength_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 symmetric_key_length = 3;</code>
       */
      public Builder clearSymmetricKeyLength() {
        
        symmetricKeyLength_ = 0;
        onChanged();
        return this;
      }

      private int heartbeatInterval_ ;
      /**
       * <code>optional uint32 heartbeat_interval = 4;</code>
       */
      public int getHeartbeatInterval() {
        return heartbeatInterval_;
      }
      /**
       * <code>optional uint32 heartbeat_interval = 4;</code>
       */
      public Builder setHeartbeatInterval(int value) {
        
        heartbeatInterval_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 heartbeat_interval = 4;</code>
       */
      public Builder clearHeartbeatInterval() {
        
        heartbeatInterval_ = 0;
        onChanged();
        return this;
      }

      private Object primaryNodeName_ = "";
      /**
       * <code>optional string primary_node_name = 5;</code>
       */
      public String getPrimaryNodeName() {
        Object ref = primaryNodeName_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          primaryNodeName_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string primary_node_name = 5;</code>
       */
      public com.google.protobuf.ByteString getPrimaryNodeNameBytes() {
        Object ref = primaryNodeName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((String) ref);
          primaryNodeName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string primary_node_name = 5;</code>
       */
      public Builder setPrimaryNodeName(String value) {
        if (value == null) {
          throw new NullPointerException();
  }
  
        primaryNodeName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string primary_node_name = 5;</code>
       */
      public Builder clearPrimaryNodeName() {
        
        primaryNodeName_ = getDefaultInstance().getPrimaryNodeName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string primary_node_name = 5;</code>
       */
      public Builder setPrimaryNodeNameBytes(com.google.protobuf.ByteString value) {
        if (value == null) {
          throw new NullPointerException();
        }
        checkByteStringIsUtf8(value);
        
        primaryNodeName_ = value;
        onChanged();
        return this;
      }

      private int secondaryChunkSize_;

      /**
       * <code>optional uint32 secondary_chunk_size = 6;</code>
       */
      public int getSecondaryChunkSize() {
        return secondaryChunkSize_;
      }

      /**
       * <code>optional uint32 secondary_chunk_size = 6;</code>
       */
      public Builder setSecondaryChunkSize(int value) {

        secondaryChunkSize_ = value;
        onChanged();
        return this;
      }

      /**
       * <code>optional uint32 secondary_chunk_size = 6;</code>
       */
      public Builder clearSecondaryChunkSize() {

        secondaryChunkSize_ = 0;
        onChanged();
        return this;
      }

      public final Builder setUnknownFields(final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:proto.ConnectionSecuringResponse)
    }

    // @@protoc_insertion_point(class_scope:proto.ConnectionSecuringResponse)
    private static final ConnectionSecuringResponse DEFAULT_INSTANCE;

    static {
      DEFAULT_INSTANCE = new ConnectionSecuringResponse();
    }

    public static ConnectionSecuringResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ConnectionSecuringResponse> PARSER = new com.google.protobuf.AbstractParser<ConnectionSecuringResponse>() {
      public ConnectionSecuringResponse parsePartialFrom(com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException {
          return new ConnectionSecuringResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ConnectionSecuringResponse> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<ConnectionSecuringResponse> getParserForType() {
      return PARSER;
    }

    public ConnectionSecuringResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ConnectionSymmetricKeyOrBuilder extends
      // @@protoc_insertion_point(interface_extends:proto.ConnectionSymmetricKey)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional .proto.Request request = 1;</code>
     */
    boolean hasRequest();
    /**
     * <code>optional .proto.Request request = 1;</code>
     */
    ProtoRequest.Request getRequest();
    /**
     * <code>optional .proto.Request request = 1;</code>
     */
    ProtoRequest.RequestOrBuilder getRequestOrBuilder();

    /**
     * <code>optional bytes symmetric_key = 2;</code>
     */
    com.google.protobuf.ByteString getSymmetricKey();

    /**
     * <code>optional uint32 version = 3;</code>
     */
    int getVersion();
  }
  /**
   * Protobuf type {@code proto.ConnectionSymmetricKey}
   */
  public static final class ConnectionSymmetricKey extends com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:proto.ConnectionSymmetricKey)
      ConnectionSymmetricKeyOrBuilder {
    // Use ConnectionSymmetricKey.newBuilder() to construct.
    private ConnectionSymmetricKey(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ConnectionSymmetricKey() {
      symmetricKey_ = com.google.protobuf.ByteString.EMPTY;
      version_ = 0;
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }

    private ConnectionSymmetricKey(com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              ProtoRequest.Request.Builder subBuilder = null;
              if (request_ != null) {
                subBuilder = request_.toBuilder();
              }
              request_ = input.readMessage(ProtoRequest.Request.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(request_);
                request_ = subBuilder.buildPartial();
              }

              break;
            }
            case 18: {

              symmetricKey_ = input.readBytes();
              break;
            }
            case 24: {

              version_ = input.readUInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
      return ProtoConnectionSecuring.internal_static_proto_ConnectionSymmetricKey_descriptor;
    }

    protected FieldAccessorTable internalGetFieldAccessorTable() {
      return ProtoConnectionSecuring.internal_static_proto_ConnectionSymmetricKey_fieldAccessorTable.ensureFieldAccessorsInitialized(ConnectionSymmetricKey.class, Builder.class);
    }

    public static final int REQUEST_FIELD_NUMBER = 1;
    private ProtoRequest.Request request_;
    /**
     * <code>optional .proto.Request request = 1;</code>
     */
    public boolean hasRequest() {
      return request_ != null;
    }
    /**
     * <code>optional .proto.Request request = 1;</code>
     */
    public ProtoRequest.Request getRequest() {
      return request_ == null ? ProtoRequest.Request.getDefaultInstance() : request_;
    }
    /**
     * <code>optional .proto.Request request = 1;</code>
     */
    public ProtoRequest.RequestOrBuilder getRequestOrBuilder() {
      return getRequest();
    }

    public static final int SYMMETRIC_KEY_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString symmetricKey_;
    /**
     * <code>optional bytes symmetric_key = 2;</code>
     */
    public com.google.protobuf.ByteString getSymmetricKey() {
      return symmetricKey_;
    }

    public static final int VERSION_FIELD_NUMBER = 3;
    private int version_;
    /**
     * <code>optional uint32 version = 3;</code>
     */
    public int getVersion() {
      return version_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (request_ != null) {
        output.writeMessage(1, getRequest());
      }
      if (!symmetricKey_.isEmpty()) {
        output.writeBytes(2, symmetricKey_);
      }
      if (version_ != 0) {
        output.writeUInt32(3, version_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (request_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getRequest());
      }
      if (!symmetricKey_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, symmetricKey_);
      }
      if (version_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(3, version_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
        return true;
      }
      if (!(obj instanceof ConnectionSymmetricKey)) {
        return super.equals(obj);
      }
      ConnectionSymmetricKey other = (ConnectionSymmetricKey) obj;

      boolean result = true;
      result = result && (hasRequest() == other.hasRequest());
      if (hasRequest()) {
        result = result && getRequest()
            .equals(other.getRequest());
      }
      result = result && getSymmetricKey().equals(other.getSymmetricKey());
      result = result && (getVersion() == other.getVersion());
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasRequest()) {
        hash = (37 * hash) + REQUEST_FIELD_NUMBER;
        hash = (53 * hash) + getRequest().hashCode();
      }
      hash = (37 * hash) + SYMMETRIC_KEY_FIELD_NUMBER;
      hash = (53 * hash) + getSymmetricKey().hashCode();
      hash = (37 * hash) + VERSION_FIELD_NUMBER;
      hash = (53 * hash) + getVersion();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ConnectionSymmetricKey parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }

    public static ConnectionSymmetricKey parseFrom(com.google.protobuf.ByteString data, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }

    public static ConnectionSymmetricKey parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }

    public static ConnectionSymmetricKey parseFrom(byte[] data, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }

    public static ConnectionSymmetricKey parseFrom(java.io.InputStream input) throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
    }

    public static ConnectionSymmetricKey parseFrom(java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static ConnectionSymmetricKey parseDelimitedFrom(java.io.InputStream input) throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(PARSER, input);
    }

    public static ConnectionSymmetricKey parseDelimitedFrom(java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }

    public static ConnectionSymmetricKey parseFrom(com.google.protobuf.CodedInputStream input) throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
    }

    public static ConnectionSymmetricKey parseFrom(com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }

    public static Builder newBuilder(ConnectionSymmetricKey prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code proto.ConnectionSymmetricKey}
     */
    public static final class Builder extends com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
            // @@protoc_insertion_point(builder_implements:proto.ConnectionSymmetricKey)
        ConnectionSymmetricKeyOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
        return ProtoConnectionSecuring.internal_static_proto_ConnectionSymmetricKey_descriptor;
      }

      protected FieldAccessorTable internalGetFieldAccessorTable() {
        return ProtoConnectionSecuring.internal_static_proto_ConnectionSymmetricKey_fieldAccessorTable.ensureFieldAccessorsInitialized(ConnectionSymmetricKey.class, Builder.class);
      }

      // Construct using net.iGap.proto.ProtoConnectionSecuring.ConnectionSymmetricKey.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        if (requestBuilder_ == null) {
          request_ = null;
        } else {
          request_ = null;
          requestBuilder_ = null;
        }
        symmetricKey_ = com.google.protobuf.ByteString.EMPTY;

        version_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
        return ProtoConnectionSecuring.internal_static_proto_ConnectionSymmetricKey_descriptor;
      }

      public ConnectionSymmetricKey getDefaultInstanceForType() {
        return ConnectionSymmetricKey.getDefaultInstance();
      }

      public ConnectionSymmetricKey build() {
        ConnectionSymmetricKey result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public ConnectionSymmetricKey buildPartial() {
        ConnectionSymmetricKey result = new ConnectionSymmetricKey(this);
        if (requestBuilder_ == null) {
          result.request_ = request_;
        } else {
          result.request_ = requestBuilder_.build();
        }
        result.symmetricKey_ = symmetricKey_;
        result.version_ = version_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }

      public Builder setField(com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ConnectionSymmetricKey) {
          return mergeFrom((ConnectionSymmetricKey)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ConnectionSymmetricKey other) {
        if (other == ConnectionSymmetricKey.getDefaultInstance()) return this;
        if (other.hasRequest()) {
          mergeRequest(other.getRequest());
        }
        if (other.getSymmetricKey() != com.google.protobuf.ByteString.EMPTY) {
          setSymmetricKey(other.getSymmetricKey());
        }
        if (other.getVersion() != 0) {
          setVersion(other.getVersion());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
        ConnectionSymmetricKey parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ConnectionSymmetricKey) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private ProtoRequest.Request request_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<ProtoRequest.Request, ProtoRequest.Request.Builder, ProtoRequest.RequestOrBuilder> requestBuilder_;
      /**
       * <code>optional .proto.Request request = 1;</code>
       */
      public boolean hasRequest() {
        return requestBuilder_ != null || request_ != null;
      }
      /**
       * <code>optional .proto.Request request = 1;</code>
       */
      public ProtoRequest.Request getRequest() {
        if (requestBuilder_ == null) {
          return request_ == null ? ProtoRequest.Request.getDefaultInstance() : request_;
        } else {
          return requestBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .proto.Request request = 1;</code>
       */
      public Builder setRequest(ProtoRequest.Request value) {
        if (requestBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          request_ = value;
          onChanged();
        } else {
          requestBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>optional .proto.Request request = 1;</code>
       */
      public Builder setRequest(ProtoRequest.Request.Builder builderForValue) {
        if (requestBuilder_ == null) {
          request_ = builderForValue.build();
          onChanged();
        } else {
          requestBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>optional .proto.Request request = 1;</code>
       */
      public Builder mergeRequest(ProtoRequest.Request value) {
        if (requestBuilder_ == null) {
          if (request_ != null) {
            request_ = ProtoRequest.Request.newBuilder(request_).mergeFrom(value).buildPartial();
          } else {
            request_ = value;
          }
          onChanged();
        } else {
          requestBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>optional .proto.Request request = 1;</code>
       */
      public Builder clearRequest() {
        if (requestBuilder_ == null) {
          request_ = null;
          onChanged();
        } else {
          request_ = null;
          requestBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>optional .proto.Request request = 1;</code>
       */
      public ProtoRequest.Request.Builder getRequestBuilder() {
        
        onChanged();
        return getRequestFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .proto.Request request = 1;</code>
       */
      public ProtoRequest.RequestOrBuilder getRequestOrBuilder() {
        if (requestBuilder_ != null) {
          return requestBuilder_.getMessageOrBuilder();
        } else {
          return request_ == null ? ProtoRequest.Request.getDefaultInstance() : request_;
        }
      }
      /**
       * <code>optional .proto.Request request = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<ProtoRequest.Request, ProtoRequest.Request.Builder, ProtoRequest.RequestOrBuilder>
          getRequestFieldBuilder() {
        if (requestBuilder_ == null) {
          requestBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<ProtoRequest.Request, ProtoRequest.Request.Builder, ProtoRequest.RequestOrBuilder>(
                  getRequest(),
                  getParentForChildren(),
                  isClean());
          request_ = null;
        }
        return requestBuilder_;
      }

      private com.google.protobuf.ByteString symmetricKey_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes symmetric_key = 2;</code>
       */
      public com.google.protobuf.ByteString getSymmetricKey() {
        return symmetricKey_;
      }
      /**
       * <code>optional bytes symmetric_key = 2;</code>
       */
      public Builder setSymmetricKey(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        symmetricKey_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes symmetric_key = 2;</code>
       */
      public Builder clearSymmetricKey() {
        
        symmetricKey_ = getDefaultInstance().getSymmetricKey();
        onChanged();
        return this;
      }

      private int version_ ;
      /**
       * <code>optional uint32 version = 3;</code>
       */
      public int getVersion() {
        return version_;
      }
      /**
       * <code>optional uint32 version = 3;</code>
       */
      public Builder setVersion(int value) {
        
        version_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 version = 3;</code>
       */
      public Builder clearVersion() {
        
        version_ = 0;
        onChanged();
        return this;
      }

      public final Builder setUnknownFields(final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:proto.ConnectionSymmetricKey)
    }

    // @@protoc_insertion_point(class_scope:proto.ConnectionSymmetricKey)
    private static final ConnectionSymmetricKey DEFAULT_INSTANCE;

    static {
      DEFAULT_INSTANCE = new ConnectionSymmetricKey();
    }

    public static ConnectionSymmetricKey getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ConnectionSymmetricKey> PARSER = new com.google.protobuf.AbstractParser<ConnectionSymmetricKey>() {
      public ConnectionSymmetricKey parsePartialFrom(com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException {
          return new ConnectionSymmetricKey(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ConnectionSymmetricKey> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<ConnectionSymmetricKey> getParserForType() {
      return PARSER;
    }

    public ConnectionSymmetricKey getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ConnectionSymmetricKeyResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:proto.ConnectionSymmetricKeyResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional .proto.Response response = 1;</code>
     */
    boolean hasResponse();
    /**
     * <code>optional .proto.Response response = 1;</code>
     */
    ProtoResponse.Response getResponse();
    /**
     * <code>optional .proto.Response response = 1;</code>
     */
    ProtoResponse.ResponseOrBuilder getResponseOrBuilder();

    /**
     * <code>optional .proto.ConnectionSymmetricKeyResponse.Status status = 2;</code>
     */
    int getStatusValue();
    /**
     * <code>optional .proto.ConnectionSymmetricKeyResponse.Status status = 2;</code>
     */
    ConnectionSymmetricKeyResponse.Status getStatus();

    /**
     * <code>optional string symmetric_method = 3;</code>
     */
    String getSymmetricMethod();
    /**
     * <code>optional string symmetric_method = 3;</code>
     */
    com.google.protobuf.ByteString
        getSymmetricMethodBytes();

    /**
     * <code>optional uint32 symmetric_iv_size = 4;</code>
     */
    int getSymmetricIvSize();

    /**
     * <code>optional bool security_issue = 5;</code>
     */
    boolean getSecurityIssue();
  }
  /**
   * Protobuf type {@code proto.ConnectionSymmetricKeyResponse}
   */
  public static final class ConnectionSymmetricKeyResponse extends com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:proto.ConnectionSymmetricKeyResponse)
      ConnectionSymmetricKeyResponseOrBuilder {
    // Use ConnectionSymmetricKeyResponse.newBuilder() to construct.
    private ConnectionSymmetricKeyResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ConnectionSymmetricKeyResponse() {
      status_ = 0;
      symmetricMethod_ = "";
      symmetricIvSize_ = 0;
      securityIssue_ = false;
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }

    private ConnectionSymmetricKeyResponse(com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              ProtoResponse.Response.Builder subBuilder = null;
              if (response_ != null) {
                subBuilder = response_.toBuilder();
              }
              response_ = input.readMessage(ProtoResponse.Response.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(response_);
                response_ = subBuilder.buildPartial();
              }

              break;
            }
            case 16: {
              int rawValue = input.readEnum();

              status_ = rawValue;
              break;
            }
            case 26: {
              String s = input.readStringRequireUtf8();

              symmetricMethod_ = s;
              break;
            }
            case 32: {

              symmetricIvSize_ = input.readUInt32();
              break;
            }
            case 40: {

              securityIssue_ = input.readBool();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
      return ProtoConnectionSecuring.internal_static_proto_ConnectionSymmetricKeyResponse_descriptor;
    }

    protected FieldAccessorTable internalGetFieldAccessorTable() {
      return ProtoConnectionSecuring.internal_static_proto_ConnectionSymmetricKeyResponse_fieldAccessorTable.ensureFieldAccessorsInitialized(ConnectionSymmetricKeyResponse.class, Builder.class);
    }

    /**
     * Protobuf enum {@code proto.ConnectionSymmetricKeyResponse.Status}
     */
    public enum Status
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>REJECTED = 0;</code>
       */
      REJECTED(0),
      /**
       * <code>ACCEPTED = 1;</code>
       */
      ACCEPTED(1),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>REJECTED = 0;</code>
       */
      public static final int REJECTED_VALUE = 0;
      /**
       * <code>ACCEPTED = 1;</code>
       */
      public static final int ACCEPTED_VALUE = 1;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @Deprecated
      public static Status valueOf(int value) {
        return forNumber(value);
      }

      public static Status forNumber(int value) {
        switch (value) {
          case 0:
            return REJECTED;
          case 1: return ACCEPTED;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Status>
          internalGetValueMap() {
        return internalValueMap;
      }

      private static final com.google.protobuf.Internal.EnumLiteMap<Status> internalValueMap = new com.google.protobuf.Internal.EnumLiteMap<Status>() {
              public Status findValueByNumber(int number) {
                return Status.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor getDescriptor() {
        return ConnectionSymmetricKeyResponse.getDescriptor().getEnumTypes().get(0);
      }

      private static final Status[] VALUES = values();

      public static Status valueOf(com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private Status(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:proto.ConnectionSymmetricKeyResponse.Status)
    }

    public static final int RESPONSE_FIELD_NUMBER = 1;
    private ProtoResponse.Response response_;
    /**
     * <code>optional .proto.Response response = 1;</code>
     */
    public boolean hasResponse() {
      return response_ != null;
    }
    /**
     * <code>optional .proto.Response response = 1;</code>
     */
    public ProtoResponse.Response getResponse() {
      return response_ == null ? ProtoResponse.Response.getDefaultInstance() : response_;
    }
    /**
     * <code>optional .proto.Response response = 1;</code>
     */
    public ProtoResponse.ResponseOrBuilder getResponseOrBuilder() {
      return getResponse();
    }

    public static final int STATUS_FIELD_NUMBER = 2;
    private int status_;
    /**
     * <code>optional .proto.ConnectionSymmetricKeyResponse.Status status = 2;</code>
     */
    public int getStatusValue() {
      return status_;
    }
    /**
     * <code>optional .proto.ConnectionSymmetricKeyResponse.Status status = 2;</code>
     */
    public Status getStatus() {
      Status result = Status.valueOf(status_);
      return result == null ? Status.UNRECOGNIZED : result;
    }

    public static final int SYMMETRIC_METHOD_FIELD_NUMBER = 3;
    private volatile Object symmetricMethod_;
    /**
     * <code>optional string symmetric_method = 3;</code>
     */
    public String getSymmetricMethod() {
      Object ref = symmetricMethod_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        symmetricMethod_ = s;
        return s;
      }
    }
    /**
     * <code>optional string symmetric_method = 3;</code>
     */
    public com.google.protobuf.ByteString getSymmetricMethodBytes() {
      Object ref = symmetricMethod_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        symmetricMethod_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SYMMETRIC_IV_SIZE_FIELD_NUMBER = 4;
    private int symmetricIvSize_;
    /**
     * <code>optional uint32 symmetric_iv_size = 4;</code>
     */
    public int getSymmetricIvSize() {
      return symmetricIvSize_;
    }

    public static final int SECURITY_ISSUE_FIELD_NUMBER = 5;
    private boolean securityIssue_;
    /**
     * <code>optional bool security_issue = 5;</code>
     */
    public boolean getSecurityIssue() {
      return securityIssue_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (response_ != null) {
        output.writeMessage(1, getResponse());
      }
      if (status_ != Status.REJECTED.getNumber()) {
        output.writeEnum(2, status_);
      }
      if (!getSymmetricMethodBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, symmetricMethod_);
      }
      if (symmetricIvSize_ != 0) {
        output.writeUInt32(4, symmetricIvSize_);
      }
      if (securityIssue_ != false) {
        output.writeBool(5, securityIssue_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (response_ != null) {
        size += com.google.protobuf.CodedOutputStream.computeMessageSize(1, getResponse());
      }
      if (status_ != Status.REJECTED.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, status_);
      }
      if (!getSymmetricMethodBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, symmetricMethod_);
      }
      if (symmetricIvSize_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(4, symmetricIvSize_);
      }
      if (securityIssue_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(5, securityIssue_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
        return true;
      }
      if (!(obj instanceof ConnectionSymmetricKeyResponse)) {
        return super.equals(obj);
      }
      ConnectionSymmetricKeyResponse other = (ConnectionSymmetricKeyResponse) obj;

      boolean result = true;
      result = result && (hasResponse() == other.hasResponse());
      if (hasResponse()) {
        result = result && getResponse()
            .equals(other.getResponse());
      }
      result = result && status_ == other.status_;
      result = result && getSymmetricMethod().equals(other.getSymmetricMethod());
      result = result && (getSymmetricIvSize()
          == other.getSymmetricIvSize());
      result = result && (getSecurityIssue()
          == other.getSecurityIssue());
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasResponse()) {
        hash = (37 * hash) + RESPONSE_FIELD_NUMBER;
        hash = (53 * hash) + getResponse().hashCode();
      }
      hash = (37 * hash) + STATUS_FIELD_NUMBER;
      hash = (53 * hash) + status_;
      hash = (37 * hash) + SYMMETRIC_METHOD_FIELD_NUMBER;
      hash = (53 * hash) + getSymmetricMethod().hashCode();
      hash = (37 * hash) + SYMMETRIC_IV_SIZE_FIELD_NUMBER;
      hash = (53 * hash) + getSymmetricIvSize();
      hash = (37 * hash) + SECURITY_ISSUE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getSecurityIssue());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ConnectionSymmetricKeyResponse parseFrom(com.google.protobuf.ByteString data) throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }

    public static ConnectionSymmetricKeyResponse parseFrom(com.google.protobuf.ByteString data, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }

    public static ConnectionSymmetricKeyResponse parseFrom(byte[] data) throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }

    public static ConnectionSymmetricKeyResponse parseFrom(byte[] data, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }

    public static ConnectionSymmetricKeyResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
    }

    public static ConnectionSymmetricKeyResponse parseFrom(java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static ConnectionSymmetricKeyResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static ConnectionSymmetricKeyResponse parseDelimitedFrom(java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }

    public static ConnectionSymmetricKeyResponse parseFrom(com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
    }

    public static ConnectionSymmetricKeyResponse parseFrom(com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }

    public static Builder newBuilder(ConnectionSymmetricKeyResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code proto.ConnectionSymmetricKeyResponse}
     */
    public static final class Builder extends com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
            // @@protoc_insertion_point(builder_implements:proto.ConnectionSymmetricKeyResponse)
        ConnectionSymmetricKeyResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
        return ProtoConnectionSecuring.internal_static_proto_ConnectionSymmetricKeyResponse_descriptor;
      }

      protected FieldAccessorTable internalGetFieldAccessorTable() {
        return ProtoConnectionSecuring.internal_static_proto_ConnectionSymmetricKeyResponse_fieldAccessorTable.ensureFieldAccessorsInitialized(ConnectionSymmetricKeyResponse.class, Builder.class);
      }

      // Construct using net.iGap.proto.ProtoConnectionSecuring.ConnectionSymmetricKeyResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        if (responseBuilder_ == null) {
          response_ = null;
        } else {
          response_ = null;
          responseBuilder_ = null;
        }
        status_ = 0;

        symmetricMethod_ = "";

        symmetricIvSize_ = 0;

        securityIssue_ = false;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
        return ProtoConnectionSecuring.internal_static_proto_ConnectionSymmetricKeyResponse_descriptor;
      }

      public ConnectionSymmetricKeyResponse getDefaultInstanceForType() {
        return ConnectionSymmetricKeyResponse.getDefaultInstance();
      }

      public ConnectionSymmetricKeyResponse build() {
        ConnectionSymmetricKeyResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public ConnectionSymmetricKeyResponse buildPartial() {
        ConnectionSymmetricKeyResponse result = new ConnectionSymmetricKeyResponse(this);
        if (responseBuilder_ == null) {
          result.response_ = response_;
        } else {
          result.response_ = responseBuilder_.build();
        }
        result.status_ = status_;
        result.symmetricMethod_ = symmetricMethod_;
        result.symmetricIvSize_ = symmetricIvSize_;
        result.securityIssue_ = securityIssue_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }

      public Builder setField(com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }

      public Builder clearField(com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }

      public Builder clearOneof(com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }

      public Builder setRepeatedField(com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ConnectionSymmetricKeyResponse) {
          return mergeFrom((ConnectionSymmetricKeyResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ConnectionSymmetricKeyResponse other) {
        if (other == ConnectionSymmetricKeyResponse.getDefaultInstance()) return this;
        if (other.hasResponse()) {
          mergeResponse(other.getResponse());
        }
        if (other.status_ != 0) {
          setStatusValue(other.getStatusValue());
        }
        if (!other.getSymmetricMethod().isEmpty()) {
          symmetricMethod_ = other.symmetricMethod_;
          onChanged();
        }
        if (other.getSymmetricIvSize() != 0) {
          setSymmetricIvSize(other.getSymmetricIvSize());
        }
        if (other.getSecurityIssue() != false) {
          setSecurityIssue(other.getSecurityIssue());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
        ConnectionSymmetricKeyResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ConnectionSymmetricKeyResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private ProtoResponse.Response response_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<ProtoResponse.Response, ProtoResponse.Response.Builder, ProtoResponse.ResponseOrBuilder> responseBuilder_;
      /**
       * <code>optional .proto.Response response = 1;</code>
       */
      public boolean hasResponse() {
        return responseBuilder_ != null || response_ != null;
      }
      /**
       * <code>optional .proto.Response response = 1;</code>
       */
      public ProtoResponse.Response getResponse() {
        if (responseBuilder_ == null) {
          return response_ == null ? ProtoResponse.Response.getDefaultInstance() : response_;
        } else {
          return responseBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .proto.Response response = 1;</code>
       */
      public Builder setResponse(ProtoResponse.Response value) {
        if (responseBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          response_ = value;
          onChanged();
        } else {
          responseBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>optional .proto.Response response = 1;</code>
       */
      public Builder setResponse(ProtoResponse.Response.Builder builderForValue) {
        if (responseBuilder_ == null) {
          response_ = builderForValue.build();
          onChanged();
        } else {
          responseBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>optional .proto.Response response = 1;</code>
       */
      public Builder mergeResponse(ProtoResponse.Response value) {
        if (responseBuilder_ == null) {
          if (response_ != null) {
            response_ = ProtoResponse.Response.newBuilder(response_).mergeFrom(value).buildPartial();
          } else {
            response_ = value;
          }
          onChanged();
        } else {
          responseBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>optional .proto.Response response = 1;</code>
       */
      public Builder clearResponse() {
        if (responseBuilder_ == null) {
          response_ = null;
          onChanged();
        } else {
          response_ = null;
          responseBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>optional .proto.Response response = 1;</code>
       */
      public ProtoResponse.Response.Builder getResponseBuilder() {
        
        onChanged();
        return getResponseFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .proto.Response response = 1;</code>
       */
      public ProtoResponse.ResponseOrBuilder getResponseOrBuilder() {
        if (responseBuilder_ != null) {
          return responseBuilder_.getMessageOrBuilder();
        } else {
          return response_ == null ? ProtoResponse.Response.getDefaultInstance() : response_;
        }
      }
      /**
       * <code>optional .proto.Response response = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<ProtoResponse.Response, ProtoResponse.Response.Builder, ProtoResponse.ResponseOrBuilder>
          getResponseFieldBuilder() {
        if (responseBuilder_ == null) {
          responseBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<ProtoResponse.Response, ProtoResponse.Response.Builder, ProtoResponse.ResponseOrBuilder>(
                  getResponse(),
                  getParentForChildren(),
                  isClean());
          response_ = null;
        }
        return responseBuilder_;
      }

      private int status_ = 0;
      /**
       * <code>optional .proto.ConnectionSymmetricKeyResponse.Status status = 2;</code>
       */
      public int getStatusValue() {
        return status_;
      }
      /**
       * <code>optional .proto.ConnectionSymmetricKeyResponse.Status status = 2;</code>
       */
      public Builder setStatusValue(int value) {
        status_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .proto.ConnectionSymmetricKeyResponse.Status status = 2;</code>
       */
      public Status getStatus() {
        Status result = Status.valueOf(status_);
        return result == null ? Status.UNRECOGNIZED : result;
      }
      /**
       * <code>optional .proto.ConnectionSymmetricKeyResponse.Status status = 2;</code>
       */
      public Builder setStatus(Status value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        status_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>optional .proto.ConnectionSymmetricKeyResponse.Status status = 2;</code>
       */
      public Builder clearStatus() {
        
        status_ = 0;
        onChanged();
        return this;
      }

      private Object symmetricMethod_ = "";
      /**
       * <code>optional string symmetric_method = 3;</code>
       */
      public String getSymmetricMethod() {
        Object ref = symmetricMethod_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          symmetricMethod_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string symmetric_method = 3;</code>
       */
      public com.google.protobuf.ByteString getSymmetricMethodBytes() {
        Object ref = symmetricMethod_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          symmetricMethod_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string symmetric_method = 3;</code>
       */
      public Builder setSymmetricMethod(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        symmetricMethod_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string symmetric_method = 3;</code>
       */
      public Builder clearSymmetricMethod() {
        
        symmetricMethod_ = getDefaultInstance().getSymmetricMethod();
        onChanged();
        return this;
      }
      /**
       * <code>optional string symmetric_method = 3;</code>
       */
      public Builder setSymmetricMethodBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        symmetricMethod_ = value;
        onChanged();
        return this;
      }

      private int symmetricIvSize_ ;
      /**
       * <code>optional uint32 symmetric_iv_size = 4;</code>
       */
      public int getSymmetricIvSize() {
        return symmetricIvSize_;
      }
      /**
       * <code>optional uint32 symmetric_iv_size = 4;</code>
       */
      public Builder setSymmetricIvSize(int value) {
        
        symmetricIvSize_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 symmetric_iv_size = 4;</code>
       */
      public Builder clearSymmetricIvSize() {
        
        symmetricIvSize_ = 0;
        onChanged();
        return this;
      }

      private boolean securityIssue_ ;
      /**
       * <code>optional bool security_issue = 5;</code>
       */
      public boolean getSecurityIssue() {
        return securityIssue_;
      }
      /**
       * <code>optional bool security_issue = 5;</code>
       */
      public Builder setSecurityIssue(boolean value) {
        
        securityIssue_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool security_issue = 5;</code>
       */
      public Builder clearSecurityIssue() {
        
        securityIssue_ = false;
        onChanged();
        return this;
      }

      public final Builder setUnknownFields(final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:proto.ConnectionSymmetricKeyResponse)
    }

    // @@protoc_insertion_point(class_scope:proto.ConnectionSymmetricKeyResponse)
    private static final ConnectionSymmetricKeyResponse DEFAULT_INSTANCE;

    static {
      DEFAULT_INSTANCE = new ConnectionSymmetricKeyResponse();
    }

    public static ConnectionSymmetricKeyResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ConnectionSymmetricKeyResponse> PARSER = new com.google.protobuf.AbstractParser<ConnectionSymmetricKeyResponse>() {
      public ConnectionSymmetricKeyResponse parsePartialFrom(com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new ConnectionSymmetricKeyResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ConnectionSymmetricKeyResponse> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<ConnectionSymmetricKeyResponse> getParserForType() {
      return PARSER;
    }

    public ConnectionSymmetricKeyResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor internal_static_proto_ConnectionSecuringResponse_descriptor;
  private static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internal_static_proto_ConnectionSecuringResponse_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor internal_static_proto_ConnectionSymmetricKey_descriptor;
  private static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internal_static_proto_ConnectionSymmetricKey_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor internal_static_proto_ConnectionSymmetricKeyResponse_descriptor;
  private static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_ConnectionSymmetricKeyResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor getDescriptor() {
    return descriptor;
  }

  private static com.google.protobuf.Descriptors.FileDescriptor descriptor;

  static {
    String[] descriptorData = {
            "\n\030ConnectionSecuring.proto\022\005proto\032\rReque" +
                    "st.proto\032\016Response.proto\"\306\001\n\032ConnectionS" +
                    "ecuringResponse\022!\n\010response\030\001 \001(\0132\017.prot" +
                    "o.Response\022\022\n\npublic_key\030\002 \001(\t\022\034\n\024symmet" +
                    "ric_key_length\030\003 \001(\r\022\032\n\022heartbeat_interv" +
                    "al\030\004 \001(\r\022\031\n\021primary_node_name\030\005 \001(\t\022\034\n\024s" +
                    "econdary_chunk_size\030\006 \001(\r\"a\n\026ConnectionS" +
                    "ymmetricKey\022\037\n\007request\030\001 \001(\0132\016.proto.Req" +
                    "uest\022\025\n\rsymmetric_key\030\002 \001(\014\022\017\n\007version\030\003" +
                    " \001(\r\"\364\001\n\036ConnectionSymmetricKeyResponse\022", "!\n\010response\030\001 \001(\0132\017.proto.Response\022<\n\006st" +
            "atus\030\002 \001(\0162,.proto.ConnectionSymmetricKe" +
            "yResponse.Status\022\030\n\020symmetric_method\030\003 \001" +
            "(\t\022\031\n\021symmetric_iv_size\030\004 \001(\r\022\026\n\016securit" +
            "y_issue\030\005 \001(\010\"$\n\006Status\022\014\n\010REJECTED\020\000\022\014\n" +
            "\010ACCEPTED\020\001B)\n\016net.iGap.protoB\027ProtoConn" +
            "ectionSecuringb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner = new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
      public com.google.protobuf.ExtensionRegistry assignDescriptors(com.google.protobuf.Descriptors.FileDescriptor root) {
        descriptor = root;
        return null;
      }
    };
    com.google.protobuf.Descriptors.FileDescriptor.internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[]{
                ProtoRequest.getDescriptor(),
          ProtoResponse.getDescriptor(),
        }, assigner);
    internal_static_proto_ConnectionSecuringResponse_descriptor = getDescriptor().getMessageTypes().get(0);
    internal_static_proto_ConnectionSecuringResponse_fieldAccessorTable = new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(internal_static_proto_ConnectionSecuringResponse_descriptor, new String[]{"Response", "PublicKey", "SymmetricKeyLength", "HeartbeatInterval", "PrimaryNodeName", "SecondaryChunkSize",});
    internal_static_proto_ConnectionSymmetricKey_descriptor = getDescriptor().getMessageTypes().get(1);
    internal_static_proto_ConnectionSymmetricKey_fieldAccessorTable = new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(internal_static_proto_ConnectionSymmetricKey_descriptor, new String[]{"Request", "SymmetricKey", "Version",});
    internal_static_proto_ConnectionSymmetricKeyResponse_descriptor = getDescriptor().getMessageTypes().get(2);
    internal_static_proto_ConnectionSymmetricKeyResponse_fieldAccessorTable = new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(internal_static_proto_ConnectionSymmetricKeyResponse_descriptor, new String[]{"Response", "Status", "SymmetricMethod", "SymmetricIvSize", "SecurityIssue",});
    ProtoRequest.getDescriptor();
    ProtoResponse.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
