// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: FileDownload.proto

package com.iGap.proto;

import com.google.protobuf.AbstractMessageLite;

public final class ProtoFileDownload {
    private static final com.google.protobuf.Descriptors.Descriptor
        internal_static_proto_FileDownload_descriptor;
    private static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internal_static_proto_FileDownload_fieldAccessorTable;
    private static final com.google.protobuf.Descriptors.Descriptor
        internal_static_proto_FileDownloadResponse_descriptor;
    private static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internal_static_proto_FileDownloadResponse_fieldAccessorTable;
    private static com.google.protobuf.Descriptors.FileDescriptor descriptor;

    static {
        String[] descriptorData = {
            "\n\022FileDownload.proto\022\005proto\032\rRequest.pro"
                +
                "to\032\016Response.proto\"\321\001\n\014FileDownload\022\037\n\007r"
                +
                "equest\030\001 \001(\0132\016.proto.Request\022\r\n\005token\030\002 "
                +
                "\001(\t\022\016\n\006offset\030\003 \001(\003\022\021\n\tmax_limit\030\004 \001(\005\022."
                +
                "\n\010selector\030\005 \001(\0162\034.proto.FileDownload.Se"
                +
                "lector\">\n\010Selector\022\010\n\004FILE\020\000\022\023\n\017SMALL_TH"
                +
                "UMBNAIL\020\001\022\023\n\017LARGE_THUMBNAIL\020\002\"H\n\024FileDo"
                +
                "wnloadResponse\022!\n\010response\030\001 \001(\0132\017.proto"
                +
                ".Response\022\r\n\005bytes\030\004 \001(\014B#\n\016com.iGap.pro"
                +
                "toB\021ProtoFileDownloadb\006proto3"
        };
        com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
            new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
                public com.google.protobuf.ExtensionRegistry assignDescriptors(
                    com.google.protobuf.Descriptors.FileDescriptor root) {
                    descriptor = root;
                    return null;
                }
            };
        com.google.protobuf.Descriptors.FileDescriptor.internalBuildGeneratedFileFrom(
            descriptorData, new com.google.protobuf.Descriptors.FileDescriptor[] {
                ProtoRequest.getDescriptor(), ProtoResponse.getDescriptor(),
            }, assigner);
        internal_static_proto_FileDownload_descriptor = getDescriptor().getMessageTypes().get(0);
        internal_static_proto_FileDownload_fieldAccessorTable =
            new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_proto_FileDownload_descriptor,
                new String[] { "Request", "Token", "Offset", "MaxLimit", "Selector", });
        internal_static_proto_FileDownloadResponse_descriptor =
            getDescriptor().getMessageTypes().get(1);
        internal_static_proto_FileDownloadResponse_fieldAccessorTable =
            new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_proto_FileDownloadResponse_descriptor,
                new String[] { "Response", "Bytes", });
        ProtoRequest.getDescriptor();
        ProtoResponse.getDescriptor();
    }

    private ProtoFileDownload() {
    }

    public static void registerAllExtensions(com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions((com.google.protobuf.ExtensionRegistryLite) registry);
    }

    public static com.google.protobuf.Descriptors.FileDescriptor getDescriptor() {
        return descriptor;
    }

    public interface FileDownloadOrBuilder extends
        // @@protoc_insertion_point(interface_extends:proto.FileDownload)
        com.google.protobuf.MessageOrBuilder {

        /**
         * <code>optional .proto.Request request = 1;</code>
         */
        boolean hasRequest();

        /**
         * <code>optional .proto.Request request = 1;</code>
         */
        ProtoRequest.Request getRequest();

        /**
         * <code>optional .proto.Request request = 1;</code>
         */
        ProtoRequest.RequestOrBuilder getRequestOrBuilder();

        /**
         * <code>optional string token = 2;</code>
         */
        String getToken();

        /**
         * <code>optional string token = 2;</code>
         */
        com.google.protobuf.ByteString getTokenBytes();

        /**
         * <code>optional int64 offset = 3;</code>
         */
        long getOffset();

        /**
         * <code>optional int32 max_limit = 4;</code>
         */
        int getMaxLimit();

        /**
         * <code>optional .proto.FileDownload.Selector selector = 5;</code>
         */
        int getSelectorValue();

        /**
         * <code>optional .proto.FileDownload.Selector selector = 5;</code>
         */
        FileDownload.Selector getSelector();
    }

    public interface FileDownloadResponseOrBuilder extends
        // @@protoc_insertion_point(interface_extends:proto.FileDownloadResponse)
        com.google.protobuf.MessageOrBuilder {

        /**
         * <code>optional .proto.Response response = 1;</code>
         */
        boolean hasResponse();

        /**
         * <code>optional .proto.Response response = 1;</code>
         */
        ProtoResponse.Response getResponse();

        /**
         * <code>optional .proto.Response response = 1;</code>
         */
        ProtoResponse.ResponseOrBuilder getResponseOrBuilder();

        /**
         * <code>optional bytes bytes = 4;</code>
         */
        com.google.protobuf.ByteString getBytes();
    }

    /**
     * Protobuf type {@code proto.FileDownload}
     */
    public static final class FileDownload extends com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:proto.FileDownload)
        FileDownloadOrBuilder {
        public static final int REQUEST_FIELD_NUMBER = 1;
        public static final int TOKEN_FIELD_NUMBER = 2;
        public static final int OFFSET_FIELD_NUMBER = 3;
        public static final int MAX_LIMIT_FIELD_NUMBER = 4;
        public static final int SELECTOR_FIELD_NUMBER = 5;
        private static final long serialVersionUID = 0L;
        // @@protoc_insertion_point(class_scope:proto.FileDownload)
        private static final FileDownload DEFAULT_INSTANCE;
        private static final com.google.protobuf.Parser<FileDownload> PARSER =
            new com.google.protobuf.AbstractParser<FileDownload>() {
                public FileDownload parsePartialFrom(com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                    return new FileDownload(input, extensionRegistry);
                }
            };

        static {
            DEFAULT_INSTANCE = new FileDownload();
        }

        private ProtoRequest.Request request_;
        private volatile Object token_;
        private long offset_;
        private int maxLimit_;
        private int selector_;
        private byte memoizedIsInitialized = -1;

        // Use FileDownload.newBuilder() to construct.
        private FileDownload(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }

        private FileDownload() {
            token_ = "";
            offset_ = 0L;
            maxLimit_ = 0;
            selector_ = 0;
        }

        private FileDownload(com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
            this();
            int mutable_bitField0_ = 0;
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        default: {
                            if (!input.skipField(tag)) {
                                done = true;
                            }
                            break;
                        }
                        case 10: {
                            ProtoRequest.Request.Builder subBuilder = null;
                            if (request_ != null) {
                                subBuilder = request_.toBuilder();
                            }
                            request_ =
                                input.readMessage(ProtoRequest.Request.parser(), extensionRegistry);
                            if (subBuilder != null) {
                                subBuilder.mergeFrom(request_);
                                request_ = subBuilder.buildPartial();
                            }

                            break;
                        }
                        case 18: {
                            String s = input.readStringRequireUtf8();

                            token_ = s;
                            break;
                        }
                        case 24: {

                            offset_ = input.readInt64();
                            break;
                        }
                        case 32: {

                            maxLimit_ = input.readInt32();
                            break;
                        }
                        case 40: {
                            int rawValue = input.readEnum();

                            selector_ = rawValue;
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                    e).setUnfinishedMessage(this);
            } finally {
                makeExtensionsImmutable();
            }
        }

        public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
            return ProtoFileDownload.internal_static_proto_FileDownload_descriptor;
        }

        public static FileDownload parseFrom(com.google.protobuf.ByteString data)
            throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static FileDownload parseFrom(com.google.protobuf.ByteString data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static FileDownload parseFrom(byte[] data)
            throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static FileDownload parseFrom(byte[] data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static FileDownload parseFrom(java.io.InputStream input) throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
        }

        public static FileDownload parseFrom(java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input,
                extensionRegistry);
        }

        public static FileDownload parseDelimitedFrom(java.io.InputStream input)
            throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(PARSER,
                input);
        }

        public static FileDownload parseDelimitedFrom(java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(PARSER,
                input, extensionRegistry);
        }

        public static FileDownload parseFrom(com.google.protobuf.CodedInputStream input)
            throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
        }

        public static FileDownload parseFrom(com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input,
                extensionRegistry);
        }

        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(FileDownload prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        public static FileDownload getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        public static com.google.protobuf.Parser<FileDownload> parser() {
            return PARSER;
        }

        @Override public final com.google.protobuf.UnknownFieldSet getUnknownFields() {
            return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
        }

        protected FieldAccessorTable internalGetFieldAccessorTable() {
            return ProtoFileDownload.internal_static_proto_FileDownload_fieldAccessorTable.ensureFieldAccessorsInitialized(
                FileDownload.class, Builder.class);
        }

        /**
         * <code>optional .proto.Request request = 1;</code>
         */
        public boolean hasRequest() {
            return request_ != null;
        }

        /**
         * <code>optional .proto.Request request = 1;</code>
         */
        public ProtoRequest.Request getRequest() {
            return request_ == null ? ProtoRequest.Request.getDefaultInstance() : request_;
        }

        /**
         * <code>optional .proto.Request request = 1;</code>
         */
        public ProtoRequest.RequestOrBuilder getRequestOrBuilder() {
            return getRequest();
        }

        /**
         * <code>optional string token = 2;</code>
         */
        public String getToken() {
            Object ref = token_;
            if (ref instanceof String) {
                return (String) ref;
            } else {
                com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                token_ = s;
                return s;
            }
        }

        /**
         * <code>optional string token = 2;</code>
         */
        public com.google.protobuf.ByteString getTokenBytes() {
            Object ref = token_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                    com.google.protobuf.ByteString.copyFromUtf8((String) ref);
                token_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <code>optional int64 offset = 3;</code>
         */
        public long getOffset() {
            return offset_;
        }

        /**
         * <code>optional int32 max_limit = 4;</code>
         */
        public int getMaxLimit() {
            return maxLimit_;
        }

        /**
         * <code>optional .proto.FileDownload.Selector selector = 5;</code>
         */
        public int getSelectorValue() {
            return selector_;
        }

        /**
         * <code>optional .proto.FileDownload.Selector selector = 5;</code>
         */
        public Selector getSelector() {
            Selector result = Selector.valueOf(selector_);
            return result == null ? Selector.UNRECOGNIZED : result;
        }

        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        public void writeTo(com.google.protobuf.CodedOutputStream output)
            throws java.io.IOException {
            if (request_ != null) {
                output.writeMessage(1, getRequest());
            }
            if (!getTokenBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 2, token_);
            }
            if (offset_ != 0L) {
                output.writeInt64(3, offset_);
            }
            if (maxLimit_ != 0) {
                output.writeInt32(4, maxLimit_);
            }
            if (selector_ != Selector.FILE.getNumber()) {
                output.writeEnum(5, selector_);
            }
        }

        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            if (request_ != null) {
                size += com.google.protobuf.CodedOutputStream.computeMessageSize(1, getRequest());
            }
            if (!getTokenBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, token_);
            }
            if (offset_ != 0L) {
                size += com.google.protobuf.CodedOutputStream.computeInt64Size(3, offset_);
            }
            if (maxLimit_ != 0) {
                size += com.google.protobuf.CodedOutputStream.computeInt32Size(4, maxLimit_);
            }
            if (selector_ != Selector.FILE.getNumber()) {
                size += com.google.protobuf.CodedOutputStream.computeEnumSize(5, selector_);
            }
            memoizedSize = size;
            return size;
        }

        @Override public boolean equals(final Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof FileDownload)) {
                return super.equals(obj);
            }
            FileDownload other = (FileDownload) obj;

            boolean result = true;
            result = result && (hasRequest() == other.hasRequest());
            if (hasRequest()) {
                result = result && getRequest().equals(other.getRequest());
            }
            result = result && getToken().equals(other.getToken());
            result = result && (getOffset() == other.getOffset());
            result = result && (getMaxLimit() == other.getMaxLimit());
            result = result && selector_ == other.selector_;
            return result;
        }

        @Override public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptorForType().hashCode();
            if (hasRequest()) {
                hash = (37 * hash) + REQUEST_FIELD_NUMBER;
                hash = (53 * hash) + getRequest().hashCode();
            }
            hash = (37 * hash) + TOKEN_FIELD_NUMBER;
            hash = (53 * hash) + getToken().hashCode();
            hash = (37 * hash) + OFFSET_FIELD_NUMBER;
            hash = (53 * hash) + com.google.protobuf.Internal.hashLong(getOffset());
            hash = (37 * hash) + MAX_LIMIT_FIELD_NUMBER;
            hash = (53 * hash) + getMaxLimit();
            hash = (37 * hash) + SELECTOR_FIELD_NUMBER;
            hash = (53 * hash) + selector_;
            hash = (29 * hash) + unknownFields.hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public Builder newBuilderForType() {
            return newBuilder();
        }

        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE ? new Builder() : new Builder().mergeFrom(this);
        }

        @Override protected Builder newBuilderForType(BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        @Override public com.google.protobuf.Parser<FileDownload> getParserForType() {
            return PARSER;
        }

        public FileDownload getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

        /**
         * Protobuf enum {@code proto.FileDownload.Selector}
         */
        public enum Selector implements com.google.protobuf.ProtocolMessageEnum {
            /**
             * <code>FILE = 0;</code>
             */
            FILE(0),
            /**
             * <code>SMALL_THUMBNAIL = 1;</code>
             */
            SMALL_THUMBNAIL(1),
            /**
             * <code>LARGE_THUMBNAIL = 2;</code>
             */
            LARGE_THUMBNAIL(2),
            UNRECOGNIZED(-1),;

            /**
             * <code>FILE = 0;</code>
             */
            public static final int FILE_VALUE = 0;
            /**
             * <code>SMALL_THUMBNAIL = 1;</code>
             */
            public static final int SMALL_THUMBNAIL_VALUE = 1;
            /**
             * <code>LARGE_THUMBNAIL = 2;</code>
             */
            public static final int LARGE_THUMBNAIL_VALUE = 2;
            private static final com.google.protobuf.Internal.EnumLiteMap<Selector>
                internalValueMap = new com.google.protobuf.Internal.EnumLiteMap<Selector>() {
                public Selector findValueByNumber(int number) {
                    return Selector.forNumber(number);
                }
            };
            private static final Selector[] VALUES = values();
            private final int value;

            private Selector(int value) {
                this.value = value;
            }

            /**
             * @deprecated Use {@link #forNumber(int)} instead.
             */
            @Deprecated public static Selector valueOf(int value) {
                return forNumber(value);
            }

            public static Selector forNumber(int value) {
                switch (value) {
                    case 0:
                        return FILE;
                    case 1:
                        return SMALL_THUMBNAIL;
                    case 2:
                        return LARGE_THUMBNAIL;
                    default:
                        return null;
                }
            }

            public static com.google.protobuf.Internal.EnumLiteMap<Selector> internalGetValueMap() {
                return internalValueMap;
            }

            public static final com.google.protobuf.Descriptors.EnumDescriptor getDescriptor() {
                return FileDownload.getDescriptor().getEnumTypes().get(0);
            }

            public static Selector valueOf(
                com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
                if (desc.getType() != getDescriptor()) {
                    throw new IllegalArgumentException("EnumValueDescriptor is not for this type.");
                }
                if (desc.getIndex() == -1) {
                    return UNRECOGNIZED;
                }
                return VALUES[desc.getIndex()];
            }

            public final int getNumber() {
                if (this == UNRECOGNIZED) {
                    throw new IllegalArgumentException(
                        "Can't get the number of an unknown enum value.");
                }
                return value;
            }

            public final com.google.protobuf.Descriptors.EnumValueDescriptor getValueDescriptor() {
                return getDescriptor().getValues().get(ordinal());
            }

            public final com.google.protobuf.Descriptors.EnumDescriptor getDescriptorForType() {
                return getDescriptor();
            }

            // @@protoc_insertion_point(enum_scope:proto.FileDownload.Selector)
        }

        /**
         * Protobuf type {@code proto.FileDownload}
         */
        public static final class Builder
            extends com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
            // @@protoc_insertion_point(builder_implements:proto.FileDownload)
            FileDownloadOrBuilder {
            private ProtoRequest.Request request_ = null;
            private com.google.protobuf.SingleFieldBuilderV3<ProtoRequest.Request, ProtoRequest.Request.Builder, ProtoRequest.RequestOrBuilder>
                requestBuilder_;
            private Object token_ = "";
            private long offset_;
            private int maxLimit_;
            private int selector_ = 0;

            // Construct using com.iGap.proto.ProtoFileDownload.FileDownload.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
                return ProtoFileDownload.internal_static_proto_FileDownload_descriptor;
            }

            protected FieldAccessorTable internalGetFieldAccessorTable() {
                return ProtoFileDownload.internal_static_proto_FileDownload_fieldAccessorTable.ensureFieldAccessorsInitialized(
                    FileDownload.class, Builder.class);
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders) {
                }
            }

            public Builder clear() {
                super.clear();
                if (requestBuilder_ == null) {
                    request_ = null;
                } else {
                    request_ = null;
                    requestBuilder_ = null;
                }
                token_ = "";

                offset_ = 0L;

                maxLimit_ = 0;

                selector_ = 0;

                return this;
            }

            public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
                return ProtoFileDownload.internal_static_proto_FileDownload_descriptor;
            }

            public FileDownload getDefaultInstanceForType() {
                return FileDownload.getDefaultInstance();
            }

            public FileDownload build() {
                FileDownload result = buildPartial();
                if (!result.isInitialized()) {
                    throw Builder.newUninitializedMessageException(result);
                }
                return result;
            }

            public FileDownload buildPartial() {
                FileDownload result = new FileDownload(this);
                if (requestBuilder_ == null) {
                    result.request_ = request_;
                } else {
                    result.request_ = requestBuilder_.build();
                }
                result.token_ = token_;
                result.offset_ = offset_;
                result.maxLimit_ = maxLimit_;
                result.selector_ = selector_;
                onBuilt();
                return result;
            }

            public Builder clone() {
                return (Builder) super.clone();
            }

            public Builder setField(com.google.protobuf.Descriptors.FieldDescriptor field,
                Object value) {
                return (Builder) super.setField(field, value);
            }

            public Builder clearField(com.google.protobuf.Descriptors.FieldDescriptor field) {
                return (Builder) super.clearField(field);
            }

            public Builder clearOneof(com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return (Builder) super.clearOneof(oneof);
            }

            public Builder setRepeatedField(com.google.protobuf.Descriptors.FieldDescriptor field,
                int index, Object value) {
                return (Builder) super.setRepeatedField(field, index, value);
            }

            public Builder addRepeatedField(com.google.protobuf.Descriptors.FieldDescriptor field,
                Object value) {
                return (Builder) super.addRepeatedField(field, value);
            }

            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof FileDownload) {
                    return mergeFrom((FileDownload) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(FileDownload other) {
                if (other == FileDownload.getDefaultInstance()) return this;
                if (other.hasRequest()) {
                    mergeRequest(other.getRequest());
                }
                if (!other.getToken().isEmpty()) {
                    token_ = other.token_;
                    onChanged();
                }
                if (other.getOffset() != 0L) {
                    setOffset(other.getOffset());
                }
                if (other.getMaxLimit() != 0) {
                    setMaxLimit(other.getMaxLimit());
                }
                if (other.selector_ != 0) {
                    setSelectorValue(other.getSelectorValue());
                }
                onChanged();
                return this;
            }

            public final boolean isInitialized() {
                return true;
            }

            public Builder mergeFrom(com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
                FileDownload parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (FileDownload) e.getUnfinishedMessage();
                    throw e.unwrapIOException();
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            /**
             * <code>optional .proto.Request request = 1;</code>
             */
            public boolean hasRequest() {
                return requestBuilder_ != null || request_ != null;
            }

            /**
             * <code>optional .proto.Request request = 1;</code>
             */
            public ProtoRequest.Request getRequest() {
                if (requestBuilder_ == null) {
                    return request_ == null ? ProtoRequest.Request.getDefaultInstance() : request_;
                } else {
                    return requestBuilder_.getMessage();
                }
            }

            /**
             * <code>optional .proto.Request request = 1;</code>
             */
            public Builder setRequest(ProtoRequest.Request.Builder builderForValue) {
                if (requestBuilder_ == null) {
                    request_ = builderForValue.build();
                    onChanged();
                } else {
                    requestBuilder_.setMessage(builderForValue.build());
                }

                return this;
            }

            /**
             * <code>optional .proto.Request request = 1;</code>
             */
            public Builder setRequest(ProtoRequest.Request value) {
                if (requestBuilder_ == null) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    request_ = value;
                    onChanged();
                } else {
                    requestBuilder_.setMessage(value);
                }

                return this;
            }

            /**
             * <code>optional .proto.Request request = 1;</code>
             */
            public Builder mergeRequest(ProtoRequest.Request value) {
                if (requestBuilder_ == null) {
                    if (request_ != null) {
                        request_ = ProtoRequest.Request.newBuilder(request_)
                            .mergeFrom(value)
                            .buildPartial();
                    } else {
                        request_ = value;
                    }
                    onChanged();
                } else {
                    requestBuilder_.mergeFrom(value);
                }

                return this;
            }

            /**
             * <code>optional .proto.Request request = 1;</code>
             */
            public Builder clearRequest() {
                if (requestBuilder_ == null) {
                    request_ = null;
                    onChanged();
                } else {
                    request_ = null;
                    requestBuilder_ = null;
                }

                return this;
            }

            /**
             * <code>optional .proto.Request request = 1;</code>
             */
            public ProtoRequest.Request.Builder getRequestBuilder() {

                onChanged();
                return getRequestFieldBuilder().getBuilder();
            }

            /**
             * <code>optional .proto.Request request = 1;</code>
             */
            public ProtoRequest.RequestOrBuilder getRequestOrBuilder() {
                if (requestBuilder_ != null) {
                    return requestBuilder_.getMessageOrBuilder();
                } else {
                    return request_ == null ? ProtoRequest.Request.getDefaultInstance() : request_;
                }
            }

            /**
             * <code>optional .proto.Request request = 1;</code>
             */
            private com.google.protobuf.SingleFieldBuilderV3<ProtoRequest.Request, ProtoRequest.Request.Builder, ProtoRequest.RequestOrBuilder> getRequestFieldBuilder() {
                if (requestBuilder_ == null) {
                    requestBuilder_ =
                        new com.google.protobuf.SingleFieldBuilderV3<ProtoRequest.Request, ProtoRequest.Request.Builder, ProtoRequest.RequestOrBuilder>(
                            getRequest(), getParentForChildren(), isClean());
                    request_ = null;
                }
                return requestBuilder_;
            }

            /**
             * <code>optional string token = 2;</code>
             */
            public String getToken() {
                Object ref = token_;
                if (!(ref instanceof String)) {
                    com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
                    String s = bs.toStringUtf8();
                    token_ = s;
                    return s;
                } else {
                    return (String) ref;
                }
            }

            /**
             * <code>optional string token = 2;</code>
             */
            public Builder setToken(String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                token_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>optional string token = 2;</code>
             */
            public com.google.protobuf.ByteString getTokenBytes() {
                Object ref = token_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8((String) ref);
                    token_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>optional string token = 2;</code>
             */
            public Builder setTokenBytes(com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                AbstractMessageLite.checkByteStringIsUtf8(value);

                token_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>optional string token = 2;</code>
             */
            public Builder clearToken() {

                token_ = getDefaultInstance().getToken();
                onChanged();
                return this;
            }

            /**
             * <code>optional int64 offset = 3;</code>
             */
            public long getOffset() {
                return offset_;
            }

            /**
             * <code>optional int64 offset = 3;</code>
             */
            public Builder setOffset(long value) {

                offset_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>optional int64 offset = 3;</code>
             */
            public Builder clearOffset() {

                offset_ = 0L;
                onChanged();
                return this;
            }

            /**
             * <code>optional int32 max_limit = 4;</code>
             */
            public int getMaxLimit() {
                return maxLimit_;
            }

            /**
             * <code>optional int32 max_limit = 4;</code>
             */
            public Builder setMaxLimit(int value) {

                maxLimit_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>optional int32 max_limit = 4;</code>
             */
            public Builder clearMaxLimit() {

                maxLimit_ = 0;
                onChanged();
                return this;
            }

            /**
             * <code>optional .proto.FileDownload.Selector selector = 5;</code>
             */
            public int getSelectorValue() {
                return selector_;
            }

            /**
             * <code>optional .proto.FileDownload.Selector selector = 5;</code>
             */
            public Builder setSelectorValue(int value) {
                selector_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>optional .proto.FileDownload.Selector selector = 5;</code>
             */
            public Selector getSelector() {
                Selector result = Selector.valueOf(selector_);
                return result == null ? Selector.UNRECOGNIZED : result;
            }

            /**
             * <code>optional .proto.FileDownload.Selector selector = 5;</code>
             */
            public Builder setSelector(Selector value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                selector_ = value.getNumber();
                onChanged();
                return this;
            }

            /**
             * <code>optional .proto.FileDownload.Selector selector = 5;</code>
             */
            public Builder clearSelector() {

                selector_ = 0;
                onChanged();
                return this;
            }

            public final Builder setUnknownFields(
                final com.google.protobuf.UnknownFieldSet unknownFields) {
                return this;
            }

            public final Builder mergeUnknownFields(
                final com.google.protobuf.UnknownFieldSet unknownFields) {
                return this;
            }

            // @@protoc_insertion_point(builder_scope:proto.FileDownload)
        }
    }

    /**
     * Protobuf type {@code proto.FileDownloadResponse}
     */
    public static final class FileDownloadResponse extends com.google.protobuf.GeneratedMessageV3
        implements
        // @@protoc_insertion_point(message_implements:proto.FileDownloadResponse)
        FileDownloadResponseOrBuilder {
        public static final int RESPONSE_FIELD_NUMBER = 1;
        public static final int BYTES_FIELD_NUMBER = 4;
        private static final long serialVersionUID = 0L;
        // @@protoc_insertion_point(class_scope:proto.FileDownloadResponse)
        private static final FileDownloadResponse DEFAULT_INSTANCE;
        private static final com.google.protobuf.Parser<FileDownloadResponse> PARSER =
            new com.google.protobuf.AbstractParser<FileDownloadResponse>() {
                public FileDownloadResponse parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                    return new FileDownloadResponse(input, extensionRegistry);
                }
            };

        static {
            DEFAULT_INSTANCE = new FileDownloadResponse();
        }

        private ProtoResponse.Response response_;
        private com.google.protobuf.ByteString bytes_;
        private byte memoizedIsInitialized = -1;

        // Use FileDownloadResponse.newBuilder() to construct.
        private FileDownloadResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }

        private FileDownloadResponse() {
            bytes_ = com.google.protobuf.ByteString.EMPTY;
        }

        private FileDownloadResponse(com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
            this();
            int mutable_bitField0_ = 0;
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        default: {
                            if (!input.skipField(tag)) {
                                done = true;
                            }
                            break;
                        }
                        case 10: {
                            ProtoResponse.Response.Builder subBuilder = null;
                            if (response_ != null) {
                                subBuilder = response_.toBuilder();
                            }
                            response_ = input.readMessage(ProtoResponse.Response.parser(),
                                extensionRegistry);
                            if (subBuilder != null) {
                                subBuilder.mergeFrom(response_);
                                response_ = subBuilder.buildPartial();
                            }

                            break;
                        }
                        case 34: {

                            bytes_ = input.readBytes();
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                    e).setUnfinishedMessage(this);
            } finally {
                makeExtensionsImmutable();
            }
        }

        public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
            return ProtoFileDownload.internal_static_proto_FileDownloadResponse_descriptor;
        }

        public static FileDownloadResponse parseFrom(com.google.protobuf.ByteString data)
            throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static FileDownloadResponse parseFrom(com.google.protobuf.ByteString data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static FileDownloadResponse parseFrom(byte[] data)
            throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static FileDownloadResponse parseFrom(byte[] data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static FileDownloadResponse parseFrom(java.io.InputStream input)
            throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
        }

        public static FileDownloadResponse parseFrom(java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input,
                extensionRegistry);
        }

        public static FileDownloadResponse parseDelimitedFrom(java.io.InputStream input)
            throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(PARSER,
                input);
        }

        public static FileDownloadResponse parseDelimitedFrom(java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(PARSER,
                input, extensionRegistry);
        }

        public static FileDownloadResponse parseFrom(com.google.protobuf.CodedInputStream input)
            throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
        }

        public static FileDownloadResponse parseFrom(com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input,
                extensionRegistry);
        }

        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(FileDownloadResponse prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        public static FileDownloadResponse getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        public static com.google.protobuf.Parser<FileDownloadResponse> parser() {
            return PARSER;
        }

        @Override public final com.google.protobuf.UnknownFieldSet getUnknownFields() {
            return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
        }

        protected FieldAccessorTable internalGetFieldAccessorTable() {
            return ProtoFileDownload.internal_static_proto_FileDownloadResponse_fieldAccessorTable.ensureFieldAccessorsInitialized(
                FileDownloadResponse.class, Builder.class);
        }

        /**
         * <code>optional .proto.Response response = 1;</code>
         */
        public boolean hasResponse() {
            return response_ != null;
        }

        /**
         * <code>optional .proto.Response response = 1;</code>
         */
        public ProtoResponse.Response getResponse() {
            return response_ == null ? ProtoResponse.Response.getDefaultInstance() : response_;
        }

        /**
         * <code>optional .proto.Response response = 1;</code>
         */
        public ProtoResponse.ResponseOrBuilder getResponseOrBuilder() {
            return getResponse();
        }

        /**
         * <code>optional bytes bytes = 4;</code>
         */
        public com.google.protobuf.ByteString getBytes() {
            return bytes_;
        }

        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        public void writeTo(com.google.protobuf.CodedOutputStream output)
            throws java.io.IOException {
            if (response_ != null) {
                output.writeMessage(1, getResponse());
            }
            if (!bytes_.isEmpty()) {
                output.writeBytes(4, bytes_);
            }
        }

        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            if (response_ != null) {
                size += com.google.protobuf.CodedOutputStream.computeMessageSize(1, getResponse());
            }
            if (!bytes_.isEmpty()) {
                size += com.google.protobuf.CodedOutputStream.computeBytesSize(4, bytes_);
            }
            memoizedSize = size;
            return size;
        }

        @Override public boolean equals(final Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof FileDownloadResponse)) {
                return super.equals(obj);
            }
            FileDownloadResponse other = (FileDownloadResponse) obj;

            boolean result = true;
            result = result && (hasResponse() == other.hasResponse());
            if (hasResponse()) {
                result = result && getResponse().equals(other.getResponse());
            }
            result = result && getBytes().equals(other.getBytes());
            return result;
        }

        @Override public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptorForType().hashCode();
            if (hasResponse()) {
                hash = (37 * hash) + RESPONSE_FIELD_NUMBER;
                hash = (53 * hash) + getResponse().hashCode();
            }
            hash = (37 * hash) + BYTES_FIELD_NUMBER;
            hash = (53 * hash) + getBytes().hashCode();
            hash = (29 * hash) + unknownFields.hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public Builder newBuilderForType() {
            return newBuilder();
        }

        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE ? new Builder() : new Builder().mergeFrom(this);
        }

        @Override protected Builder newBuilderForType(BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        @Override public com.google.protobuf.Parser<FileDownloadResponse> getParserForType() {
            return PARSER;
        }

        public FileDownloadResponse getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

        /**
         * Protobuf type {@code proto.FileDownloadResponse}
         */
        public static final class Builder
            extends com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
            // @@protoc_insertion_point(builder_implements:proto.FileDownloadResponse)
            FileDownloadResponseOrBuilder {
            private ProtoResponse.Response response_ = null;
            private com.google.protobuf.SingleFieldBuilderV3<ProtoResponse.Response, ProtoResponse.Response.Builder, ProtoResponse.ResponseOrBuilder>
                responseBuilder_;
            private com.google.protobuf.ByteString bytes_ = com.google.protobuf.ByteString.EMPTY;

            // Construct using com.iGap.proto.ProtoFileDownload.FileDownloadResponse.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
                return ProtoFileDownload.internal_static_proto_FileDownloadResponse_descriptor;
            }

            protected FieldAccessorTable internalGetFieldAccessorTable() {
                return ProtoFileDownload.internal_static_proto_FileDownloadResponse_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(FileDownloadResponse.class, Builder.class);
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders) {
                }
            }

            public Builder clear() {
                super.clear();
                if (responseBuilder_ == null) {
                    response_ = null;
                } else {
                    response_ = null;
                    responseBuilder_ = null;
                }
                bytes_ = com.google.protobuf.ByteString.EMPTY;

                return this;
            }

            public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
                return ProtoFileDownload.internal_static_proto_FileDownloadResponse_descriptor;
            }

            public FileDownloadResponse getDefaultInstanceForType() {
                return FileDownloadResponse.getDefaultInstance();
            }

            public FileDownloadResponse build() {
                FileDownloadResponse result = buildPartial();
                if (!result.isInitialized()) {
                    throw Builder.newUninitializedMessageException(result);
                }
                return result;
            }

            public FileDownloadResponse buildPartial() {
                FileDownloadResponse result = new FileDownloadResponse(this);
                if (responseBuilder_ == null) {
                    result.response_ = response_;
                } else {
                    result.response_ = responseBuilder_.build();
                }
                result.bytes_ = bytes_;
                onBuilt();
                return result;
            }

            public Builder clone() {
                return (Builder) super.clone();
            }

            public Builder setField(com.google.protobuf.Descriptors.FieldDescriptor field,
                Object value) {
                return (Builder) super.setField(field, value);
            }

            public Builder clearField(com.google.protobuf.Descriptors.FieldDescriptor field) {
                return (Builder) super.clearField(field);
            }

            public Builder clearOneof(com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return (Builder) super.clearOneof(oneof);
            }

            public Builder setRepeatedField(com.google.protobuf.Descriptors.FieldDescriptor field,
                int index, Object value) {
                return (Builder) super.setRepeatedField(field, index, value);
            }

            public Builder addRepeatedField(com.google.protobuf.Descriptors.FieldDescriptor field,
                Object value) {
                return (Builder) super.addRepeatedField(field, value);
            }

            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof FileDownloadResponse) {
                    return mergeFrom((FileDownloadResponse) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(FileDownloadResponse other) {
                if (other == FileDownloadResponse.getDefaultInstance()) return this;
                if (other.hasResponse()) {
                    mergeResponse(other.getResponse());
                }
                if (other.getBytes() != com.google.protobuf.ByteString.EMPTY) {
                    setBytes(other.getBytes());
                }
                onChanged();
                return this;
            }

            public final boolean isInitialized() {
                return true;
            }

            public Builder mergeFrom(com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
                FileDownloadResponse parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (FileDownloadResponse) e.getUnfinishedMessage();
                    throw e.unwrapIOException();
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            /**
             * <code>optional .proto.Response response = 1;</code>
             */
            public boolean hasResponse() {
                return responseBuilder_ != null || response_ != null;
            }

            /**
             * <code>optional .proto.Response response = 1;</code>
             */
            public ProtoResponse.Response getResponse() {
                if (responseBuilder_ == null) {
                    return response_ == null ? ProtoResponse.Response.getDefaultInstance()
                        : response_;
                } else {
                    return responseBuilder_.getMessage();
                }
            }

            /**
             * <code>optional .proto.Response response = 1;</code>
             */
            public Builder setResponse(ProtoResponse.Response.Builder builderForValue) {
                if (responseBuilder_ == null) {
                    response_ = builderForValue.build();
                    onChanged();
                } else {
                    responseBuilder_.setMessage(builderForValue.build());
                }

                return this;
            }

            /**
             * <code>optional .proto.Response response = 1;</code>
             */
            public Builder setResponse(ProtoResponse.Response value) {
                if (responseBuilder_ == null) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    response_ = value;
                    onChanged();
                } else {
                    responseBuilder_.setMessage(value);
                }

                return this;
            }

            /**
             * <code>optional .proto.Response response = 1;</code>
             */
            public Builder mergeResponse(ProtoResponse.Response value) {
                if (responseBuilder_ == null) {
                    if (response_ != null) {
                        response_ = ProtoResponse.Response.newBuilder(response_)
                            .mergeFrom(value)
                            .buildPartial();
                    } else {
                        response_ = value;
                    }
                    onChanged();
                } else {
                    responseBuilder_.mergeFrom(value);
                }

                return this;
            }

            /**
             * <code>optional .proto.Response response = 1;</code>
             */
            public Builder clearResponse() {
                if (responseBuilder_ == null) {
                    response_ = null;
                    onChanged();
                } else {
                    response_ = null;
                    responseBuilder_ = null;
                }

                return this;
            }

            /**
             * <code>optional .proto.Response response = 1;</code>
             */
            public ProtoResponse.Response.Builder getResponseBuilder() {

                onChanged();
                return getResponseFieldBuilder().getBuilder();
            }

            /**
             * <code>optional .proto.Response response = 1;</code>
             */
            public ProtoResponse.ResponseOrBuilder getResponseOrBuilder() {
                if (responseBuilder_ != null) {
                    return responseBuilder_.getMessageOrBuilder();
                } else {
                    return response_ == null ? ProtoResponse.Response.getDefaultInstance()
                        : response_;
                }
            }

            /**
             * <code>optional .proto.Response response = 1;</code>
             */
            private com.google.protobuf.SingleFieldBuilderV3<ProtoResponse.Response, ProtoResponse.Response.Builder, ProtoResponse.ResponseOrBuilder> getResponseFieldBuilder() {
                if (responseBuilder_ == null) {
                    responseBuilder_ =
                        new com.google.protobuf.SingleFieldBuilderV3<ProtoResponse.Response, ProtoResponse.Response.Builder, ProtoResponse.ResponseOrBuilder>(
                            getResponse(), getParentForChildren(), isClean());
                    response_ = null;
                }
                return responseBuilder_;
            }

            /**
             * <code>optional bytes bytes = 4;</code>
             */
            public com.google.protobuf.ByteString getBytes() {
                return bytes_;
            }

            /**
             * <code>optional bytes bytes = 4;</code>
             */
            public Builder setBytes(com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                bytes_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>optional bytes bytes = 4;</code>
             */
            public Builder clearBytes() {

                bytes_ = getDefaultInstance().getBytes();
                onChanged();
                return this;
            }

            public final Builder setUnknownFields(
                final com.google.protobuf.UnknownFieldSet unknownFields) {
                return this;
            }

            public final Builder mergeUnknownFields(
                final com.google.protobuf.UnknownFieldSet unknownFields) {
                return this;
            }

            // @@protoc_insertion_point(builder_scope:proto.FileDownloadResponse)
        }
    }

    // @@protoc_insertion_point(outer_class_scope)
}
