// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Heartbeat.proto

package com.iGap.proto;

public final class ProtoHeartbeat {
    private ProtoHeartbeat() {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions(
                (com.google.protobuf.ExtensionRegistryLite) registry);
    }

    public interface HeartbeatOrBuilder extends
            // @@protoc_insertion_point(interface_extends:proto.Heartbeat)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>optional .proto.Request request = 1;</code>
         */
        boolean hasRequest();

        /**
         * <code>optional .proto.Request request = 1;</code>
         */
        ProtoRequest.Request getRequest();

        /**
         * <code>optional .proto.Request request = 1;</code>
         */
        ProtoRequest.RequestOrBuilder getRequestOrBuilder();
    }

    /**
     * Protobuf type {@code proto.Heartbeat}
     */
    public static final class Heartbeat extends
            com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:proto.Heartbeat)
            HeartbeatOrBuilder {
        // Use Heartbeat.newBuilder() to construct.
        private Heartbeat(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }

        private Heartbeat() {
        }

        @Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
        }

        private Heartbeat(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            this();
            int mutable_bitField0_ = 0;
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        default: {
                            if (!input.skipField(tag)) {
                                done = true;
                            }
                            break;
                        }
                        case 10: {
                            ProtoRequest.Request.Builder subBuilder = null;
                            if (request_ != null) {
                                subBuilder = request_.toBuilder();
                            }
                            request_ = input.readMessage(ProtoRequest.Request.parser(), extensionRegistry);
                            if (subBuilder != null) {
                                subBuilder.mergeFrom(request_);
                                request_ = subBuilder.buildPartial();
                            }

                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e).setUnfinishedMessage(this);
            } finally {
                makeExtensionsImmutable();
            }
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return ProtoHeartbeat.internal_static_proto_Heartbeat_descriptor;
        }

        protected FieldAccessorTable
        internalGetFieldAccessorTable() {
            return ProtoHeartbeat.internal_static_proto_Heartbeat_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            Heartbeat.class, Builder.class);
        }

        public static final int REQUEST_FIELD_NUMBER = 1;
        private ProtoRequest.Request request_;

        /**
         * <code>optional .proto.Request request = 1;</code>
         */
        public boolean hasRequest() {
            return request_ != null;
        }

        /**
         * <code>optional .proto.Request request = 1;</code>
         */
        public ProtoRequest.Request getRequest() {
            return request_ == null ? ProtoRequest.Request.getDefaultInstance() : request_;
        }

        /**
         * <code>optional .proto.Request request = 1;</code>
         */
        public ProtoRequest.RequestOrBuilder getRequestOrBuilder() {
            return getRequest();
        }

        private byte memoizedIsInitialized = -1;

        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            if (request_ != null) {
                output.writeMessage(1, getRequest());
            }
        }

        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            if (request_ != null) {
                size += com.google.protobuf.CodedOutputStream
                        .computeMessageSize(1, getRequest());
            }
            memoizedSize = size;
            return size;
        }

        private static final long serialVersionUID = 0L;

        @Override
        public boolean equals(final Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof Heartbeat)) {
                return super.equals(obj);
            }
            Heartbeat other = (Heartbeat) obj;

            boolean result = true;
            result = result && (hasRequest() == other.hasRequest());
            if (hasRequest()) {
                result = result && getRequest()
                        .equals(other.getRequest());
            }
            return result;
        }

        @Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptorForType().hashCode();
            if (hasRequest()) {
                hash = (37 * hash) + REQUEST_FIELD_NUMBER;
                hash = (53 * hash) + getRequest().hashCode();
            }
            hash = (29 * hash) + unknownFields.hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public static Heartbeat parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static Heartbeat parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static Heartbeat parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static Heartbeat parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static Heartbeat parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static Heartbeat parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static Heartbeat parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input);
        }

        public static Heartbeat parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }

        public static Heartbeat parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static Heartbeat parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public Builder newBuilderForType() {
            return newBuilder();
        }

        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(Heartbeat prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @Override
        protected Builder newBuilderForType(
                BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        /**
         * Protobuf type {@code proto.Heartbeat}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:proto.Heartbeat)
                HeartbeatOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return ProtoHeartbeat.internal_static_proto_Heartbeat_descriptor;
            }

            protected FieldAccessorTable
            internalGetFieldAccessorTable() {
                return ProtoHeartbeat.internal_static_proto_Heartbeat_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                Heartbeat.class, Builder.class);
            }

            // Construct using com.iGap.proto.ProtoHeartbeat.Heartbeat.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessageV3
                        .alwaysUseFieldBuilders) {
                }
            }

            public Builder clear() {
                super.clear();
                if (requestBuilder_ == null) {
                    request_ = null;
                } else {
                    request_ = null;
                    requestBuilder_ = null;
                }
                return this;
            }

            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return ProtoHeartbeat.internal_static_proto_Heartbeat_descriptor;
            }

            public Heartbeat getDefaultInstanceForType() {
                return Heartbeat.getDefaultInstance();
            }

            public Heartbeat build() {
                Heartbeat result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            public Heartbeat buildPartial() {
                Heartbeat result = new Heartbeat(this);
                if (requestBuilder_ == null) {
                    result.request_ = request_;
                } else {
                    result.request_ = requestBuilder_.build();
                }
                onBuilt();
                return result;
            }

            public Builder clone() {
                return (Builder) super.clone();
            }

            public Builder setField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    Object value) {
                return (Builder) super.setField(field, value);
            }

            public Builder clearField(
                    com.google.protobuf.Descriptors.FieldDescriptor field) {
                return (Builder) super.clearField(field);
            }

            public Builder clearOneof(
                    com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return (Builder) super.clearOneof(oneof);
            }

            public Builder setRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    int index, Object value) {
                return (Builder) super.setRepeatedField(field, index, value);
            }

            public Builder addRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    Object value) {
                return (Builder) super.addRepeatedField(field, value);
            }

            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof Heartbeat) {
                    return mergeFrom((Heartbeat) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(Heartbeat other) {
                if (other == Heartbeat.getDefaultInstance()) return this;
                if (other.hasRequest()) {
                    mergeRequest(other.getRequest());
                }
                onChanged();
                return this;
            }

            public final boolean isInitialized() {
                return true;
            }

            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                Heartbeat parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (Heartbeat) e.getUnfinishedMessage();
                    throw e.unwrapIOException();
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            private ProtoRequest.Request request_ = null;
            private com.google.protobuf.SingleFieldBuilderV3<
                    ProtoRequest.Request, ProtoRequest.Request.Builder, ProtoRequest.RequestOrBuilder> requestBuilder_;

            /**
             * <code>optional .proto.Request request = 1;</code>
             */
            public boolean hasRequest() {
                return requestBuilder_ != null || request_ != null;
            }

            /**
             * <code>optional .proto.Request request = 1;</code>
             */
            public ProtoRequest.Request getRequest() {
                if (requestBuilder_ == null) {
                    return request_ == null ? ProtoRequest.Request.getDefaultInstance() : request_;
                } else {
                    return requestBuilder_.getMessage();
                }
            }

            /**
             * <code>optional .proto.Request request = 1;</code>
             */
            public Builder setRequest(ProtoRequest.Request value) {
                if (requestBuilder_ == null) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    request_ = value;
                    onChanged();
                } else {
                    requestBuilder_.setMessage(value);
                }

                return this;
            }

            /**
             * <code>optional .proto.Request request = 1;</code>
             */
            public Builder setRequest(
                    ProtoRequest.Request.Builder builderForValue) {
                if (requestBuilder_ == null) {
                    request_ = builderForValue.build();
                    onChanged();
                } else {
                    requestBuilder_.setMessage(builderForValue.build());
                }

                return this;
            }

            /**
             * <code>optional .proto.Request request = 1;</code>
             */
            public Builder mergeRequest(ProtoRequest.Request value) {
                if (requestBuilder_ == null) {
                    if (request_ != null) {
                        request_ =
                                ProtoRequest.Request.newBuilder(request_).mergeFrom(value).buildPartial();
                    } else {
                        request_ = value;
                    }
                    onChanged();
                } else {
                    requestBuilder_.mergeFrom(value);
                }

                return this;
            }

            /**
             * <code>optional .proto.Request request = 1;</code>
             */
            public Builder clearRequest() {
                if (requestBuilder_ == null) {
                    request_ = null;
                    onChanged();
                } else {
                    request_ = null;
                    requestBuilder_ = null;
                }

                return this;
            }

            /**
             * <code>optional .proto.Request request = 1;</code>
             */
            public ProtoRequest.Request.Builder getRequestBuilder() {

                onChanged();
                return getRequestFieldBuilder().getBuilder();
            }

            /**
             * <code>optional .proto.Request request = 1;</code>
             */
            public ProtoRequest.RequestOrBuilder getRequestOrBuilder() {
                if (requestBuilder_ != null) {
                    return requestBuilder_.getMessageOrBuilder();
                } else {
                    return request_ == null ?
                            ProtoRequest.Request.getDefaultInstance() : request_;
                }
            }

            /**
             * <code>optional .proto.Request request = 1;</code>
             */
            private com.google.protobuf.SingleFieldBuilderV3<
                    ProtoRequest.Request, ProtoRequest.Request.Builder, ProtoRequest.RequestOrBuilder>
            getRequestFieldBuilder() {
                if (requestBuilder_ == null) {
                    requestBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
                            ProtoRequest.Request, ProtoRequest.Request.Builder, ProtoRequest.RequestOrBuilder>(
                            getRequest(),
                            getParentForChildren(),
                            isClean());
                    request_ = null;
                }
                return requestBuilder_;
            }

            public final Builder setUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return this;
            }

            public final Builder mergeUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return this;
            }


            // @@protoc_insertion_point(builder_scope:proto.Heartbeat)
        }

        // @@protoc_insertion_point(class_scope:proto.Heartbeat)
        private static final Heartbeat DEFAULT_INSTANCE;

        static {
            DEFAULT_INSTANCE = new Heartbeat();
        }

        public static Heartbeat getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        private static final com.google.protobuf.Parser<Heartbeat>
                PARSER = new com.google.protobuf.AbstractParser<Heartbeat>() {
            public Heartbeat parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return new Heartbeat(input, extensionRegistry);
            }
        };

        public static com.google.protobuf.Parser<Heartbeat> parser() {
            return PARSER;
        }

        @Override
        public com.google.protobuf.Parser<Heartbeat> getParserForType() {
            return PARSER;
        }

        public Heartbeat getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

    }

    public interface HeartbeatResponseOrBuilder extends
            // @@protoc_insertion_point(interface_extends:proto.HeartbeatResponse)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>optional .proto.Response response = 1;</code>
         */
        boolean hasResponse();

        /**
         * <code>optional .proto.Response response = 1;</code>
         */
        ProtoResponse.Response getResponse();

        /**
         * <code>optional .proto.Response response = 1;</code>
         */
        ProtoResponse.ResponseOrBuilder getResponseOrBuilder();
    }

    /**
     * Protobuf type {@code proto.HeartbeatResponse}
     */
    public static final class HeartbeatResponse extends
            com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:proto.HeartbeatResponse)
            HeartbeatResponseOrBuilder {
        // Use HeartbeatResponse.newBuilder() to construct.
        private HeartbeatResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }

        private HeartbeatResponse() {
        }

        @Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
        }

        private HeartbeatResponse(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            this();
            int mutable_bitField0_ = 0;
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        default: {
                            if (!input.skipField(tag)) {
                                done = true;
                            }
                            break;
                        }
                        case 10: {
                            ProtoResponse.Response.Builder subBuilder = null;
                            if (response_ != null) {
                                subBuilder = response_.toBuilder();
                            }
                            response_ = input.readMessage(ProtoResponse.Response.parser(), extensionRegistry);
                            if (subBuilder != null) {
                                subBuilder.mergeFrom(response_);
                                response_ = subBuilder.buildPartial();
                            }

                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e).setUnfinishedMessage(this);
            } finally {
                makeExtensionsImmutable();
            }
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return ProtoHeartbeat.internal_static_proto_HeartbeatResponse_descriptor;
        }

        protected FieldAccessorTable
        internalGetFieldAccessorTable() {
            return ProtoHeartbeat.internal_static_proto_HeartbeatResponse_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            HeartbeatResponse.class, Builder.class);
        }

        public static final int RESPONSE_FIELD_NUMBER = 1;
        private ProtoResponse.Response response_;

        /**
         * <code>optional .proto.Response response = 1;</code>
         */
        public boolean hasResponse() {
            return response_ != null;
        }

        /**
         * <code>optional .proto.Response response = 1;</code>
         */
        public ProtoResponse.Response getResponse() {
            return response_ == null ? ProtoResponse.Response.getDefaultInstance() : response_;
        }

        /**
         * <code>optional .proto.Response response = 1;</code>
         */
        public ProtoResponse.ResponseOrBuilder getResponseOrBuilder() {
            return getResponse();
        }

        private byte memoizedIsInitialized = -1;

        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            if (response_ != null) {
                output.writeMessage(1, getResponse());
            }
        }

        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            if (response_ != null) {
                size += com.google.protobuf.CodedOutputStream
                        .computeMessageSize(1, getResponse());
            }
            memoizedSize = size;
            return size;
        }

        private static final long serialVersionUID = 0L;

        @Override
        public boolean equals(final Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof HeartbeatResponse)) {
                return super.equals(obj);
            }
            HeartbeatResponse other = (HeartbeatResponse) obj;

            boolean result = true;
            result = result && (hasResponse() == other.hasResponse());
            if (hasResponse()) {
                result = result && getResponse()
                        .equals(other.getResponse());
            }
            return result;
        }

        @Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptorForType().hashCode();
            if (hasResponse()) {
                hash = (37 * hash) + RESPONSE_FIELD_NUMBER;
                hash = (53 * hash) + getResponse().hashCode();
            }
            hash = (29 * hash) + unknownFields.hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public static HeartbeatResponse parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static HeartbeatResponse parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static HeartbeatResponse parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static HeartbeatResponse parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static HeartbeatResponse parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static HeartbeatResponse parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static HeartbeatResponse parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input);
        }

        public static HeartbeatResponse parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }

        public static HeartbeatResponse parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static HeartbeatResponse parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public Builder newBuilderForType() {
            return newBuilder();
        }

        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(HeartbeatResponse prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @Override
        protected Builder newBuilderForType(
                BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        /**
         * Protobuf type {@code proto.HeartbeatResponse}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:proto.HeartbeatResponse)
                HeartbeatResponseOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return ProtoHeartbeat.internal_static_proto_HeartbeatResponse_descriptor;
            }

            protected FieldAccessorTable
            internalGetFieldAccessorTable() {
                return ProtoHeartbeat.internal_static_proto_HeartbeatResponse_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                HeartbeatResponse.class, Builder.class);
            }

            // Construct using com.iGap.proto.ProtoHeartbeat.HeartbeatResponse.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessageV3
                        .alwaysUseFieldBuilders) {
                }
            }

            public Builder clear() {
                super.clear();
                if (responseBuilder_ == null) {
                    response_ = null;
                } else {
                    response_ = null;
                    responseBuilder_ = null;
                }
                return this;
            }

            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return ProtoHeartbeat.internal_static_proto_HeartbeatResponse_descriptor;
            }

            public HeartbeatResponse getDefaultInstanceForType() {
                return HeartbeatResponse.getDefaultInstance();
            }

            public HeartbeatResponse build() {
                HeartbeatResponse result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            public HeartbeatResponse buildPartial() {
                HeartbeatResponse result = new HeartbeatResponse(this);
                if (responseBuilder_ == null) {
                    result.response_ = response_;
                } else {
                    result.response_ = responseBuilder_.build();
                }
                onBuilt();
                return result;
            }

            public Builder clone() {
                return (Builder) super.clone();
            }

            public Builder setField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    Object value) {
                return (Builder) super.setField(field, value);
            }

            public Builder clearField(
                    com.google.protobuf.Descriptors.FieldDescriptor field) {
                return (Builder) super.clearField(field);
            }

            public Builder clearOneof(
                    com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return (Builder) super.clearOneof(oneof);
            }

            public Builder setRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    int index, Object value) {
                return (Builder) super.setRepeatedField(field, index, value);
            }

            public Builder addRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    Object value) {
                return (Builder) super.addRepeatedField(field, value);
            }

            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof HeartbeatResponse) {
                    return mergeFrom((HeartbeatResponse) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(HeartbeatResponse other) {
                if (other == HeartbeatResponse.getDefaultInstance()) return this;
                if (other.hasResponse()) {
                    mergeResponse(other.getResponse());
                }
                onChanged();
                return this;
            }

            public final boolean isInitialized() {
                return true;
            }

            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                HeartbeatResponse parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (HeartbeatResponse) e.getUnfinishedMessage();
                    throw e.unwrapIOException();
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            private ProtoResponse.Response response_ = null;
            private com.google.protobuf.SingleFieldBuilderV3<
                    ProtoResponse.Response, ProtoResponse.Response.Builder, ProtoResponse.ResponseOrBuilder> responseBuilder_;

            /**
             * <code>optional .proto.Response response = 1;</code>
             */
            public boolean hasResponse() {
                return responseBuilder_ != null || response_ != null;
            }

            /**
             * <code>optional .proto.Response response = 1;</code>
             */
            public ProtoResponse.Response getResponse() {
                if (responseBuilder_ == null) {
                    return response_ == null ? ProtoResponse.Response.getDefaultInstance() : response_;
                } else {
                    return responseBuilder_.getMessage();
                }
            }

            /**
             * <code>optional .proto.Response response = 1;</code>
             */
            public Builder setResponse(ProtoResponse.Response value) {
                if (responseBuilder_ == null) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    response_ = value;
                    onChanged();
                } else {
                    responseBuilder_.setMessage(value);
                }

                return this;
            }

            /**
             * <code>optional .proto.Response response = 1;</code>
             */
            public Builder setResponse(
                    ProtoResponse.Response.Builder builderForValue) {
                if (responseBuilder_ == null) {
                    response_ = builderForValue.build();
                    onChanged();
                } else {
                    responseBuilder_.setMessage(builderForValue.build());
                }

                return this;
            }

            /**
             * <code>optional .proto.Response response = 1;</code>
             */
            public Builder mergeResponse(ProtoResponse.Response value) {
                if (responseBuilder_ == null) {
                    if (response_ != null) {
                        response_ =
                                ProtoResponse.Response.newBuilder(response_).mergeFrom(value).buildPartial();
                    } else {
                        response_ = value;
                    }
                    onChanged();
                } else {
                    responseBuilder_.mergeFrom(value);
                }

                return this;
            }

            /**
             * <code>optional .proto.Response response = 1;</code>
             */
            public Builder clearResponse() {
                if (responseBuilder_ == null) {
                    response_ = null;
                    onChanged();
                } else {
                    response_ = null;
                    responseBuilder_ = null;
                }

                return this;
            }

            /**
             * <code>optional .proto.Response response = 1;</code>
             */
            public ProtoResponse.Response.Builder getResponseBuilder() {

                onChanged();
                return getResponseFieldBuilder().getBuilder();
            }

            /**
             * <code>optional .proto.Response response = 1;</code>
             */
            public ProtoResponse.ResponseOrBuilder getResponseOrBuilder() {
                if (responseBuilder_ != null) {
                    return responseBuilder_.getMessageOrBuilder();
                } else {
                    return response_ == null ?
                            ProtoResponse.Response.getDefaultInstance() : response_;
                }
            }

            /**
             * <code>optional .proto.Response response = 1;</code>
             */
            private com.google.protobuf.SingleFieldBuilderV3<
                    ProtoResponse.Response, ProtoResponse.Response.Builder, ProtoResponse.ResponseOrBuilder>
            getResponseFieldBuilder() {
                if (responseBuilder_ == null) {
                    responseBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
                            ProtoResponse.Response, ProtoResponse.Response.Builder, ProtoResponse.ResponseOrBuilder>(
                            getResponse(),
                            getParentForChildren(),
                            isClean());
                    response_ = null;
                }
                return responseBuilder_;
            }

            public final Builder setUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return this;
            }

            public final Builder mergeUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return this;
            }


            // @@protoc_insertion_point(builder_scope:proto.HeartbeatResponse)
        }

        // @@protoc_insertion_point(class_scope:proto.HeartbeatResponse)
        private static final HeartbeatResponse DEFAULT_INSTANCE;

        static {
            DEFAULT_INSTANCE = new HeartbeatResponse();
        }

        public static HeartbeatResponse getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        private static final com.google.protobuf.Parser<HeartbeatResponse>
                PARSER = new com.google.protobuf.AbstractParser<HeartbeatResponse>() {
            public HeartbeatResponse parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return new HeartbeatResponse(input, extensionRegistry);
            }
        };

        public static com.google.protobuf.Parser<HeartbeatResponse> parser() {
            return PARSER;
        }

        @Override
        public com.google.protobuf.Parser<HeartbeatResponse> getParserForType() {
            return PARSER;
        }

        public HeartbeatResponse getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

    }

    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_proto_Heartbeat_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_proto_Heartbeat_fieldAccessorTable;
    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_proto_HeartbeatResponse_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_proto_HeartbeatResponse_fieldAccessorTable;

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }

    private static com.google.protobuf.Descriptors.FileDescriptor
            descriptor;

    static {
        String[] descriptorData = {
                "\n\017Heartbeat.proto\022\005proto\032\rRequest.proto\032" +
                        "\016Response.proto\",\n\tHeartbeat\022\037\n\007request\030" +
                        "\001 \001(\0132\016.proto.Request\"6\n\021HeartbeatRespon" +
                        "se\022!\n\010response\030\001 \001(\0132\017.proto.ResponseB \n" +
                        "\016com.iGap.protoB\016ProtoHeartbeatb\006proto3"
        };
        com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
                new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
                    public com.google.protobuf.ExtensionRegistry assignDescriptors(
                            com.google.protobuf.Descriptors.FileDescriptor root) {
                        descriptor = root;
                        return null;
                    }
                };
        com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[]{
                                ProtoRequest.getDescriptor(),
                                ProtoResponse.getDescriptor(),
                        }, assigner);
        internal_static_proto_Heartbeat_descriptor =
                getDescriptor().getMessageTypes().get(0);
        internal_static_proto_Heartbeat_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_proto_Heartbeat_descriptor,
                new String[]{"Request",});
        internal_static_proto_HeartbeatResponse_descriptor =
                getDescriptor().getMessageTypes().get(1);
        internal_static_proto_HeartbeatResponse_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_proto_HeartbeatResponse_descriptor,
                new String[]{"Response",});
        ProtoRequest.getDescriptor();
        ProtoResponse.getDescriptor();
    }

    // @@protoc_insertion_point(outer_class_scope)
}
