// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ChatConvertToGroup.proto

package com.iGap.proto;

public final class ProtoChatConvertToGroup {
    private ProtoChatConvertToGroup() {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions(
                (com.google.protobuf.ExtensionRegistryLite) registry);
    }

    public interface ChatConvertToGroupOrBuilder extends
            // @@protoc_insertion_point(interface_extends:proto.ChatConvertToGroup)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>optional .proto.Request request = 1;</code>
         */
        boolean hasRequest();

        /**
         * <code>optional .proto.Request request = 1;</code>
         */
        ProtoRequest.Request getRequest();

        /**
         * <code>optional .proto.Request request = 1;</code>
         */
        ProtoRequest.RequestOrBuilder getRequestOrBuilder();

        /**
         * <code>optional uint64 room_id = 2;</code>
         */
        long getRoomId();

        /**
         * <code>optional string name = 3;</code>
         */
        String getName();

        /**
         * <code>optional string name = 3;</code>
         */
        com.google.protobuf.ByteString
        getNameBytes();

        /**
         * <code>optional string description = 4;</code>
         */
        String getDescription();

        /**
         * <code>optional string description = 4;</code>
         */
        com.google.protobuf.ByteString
        getDescriptionBytes();
    }

    /**
     * Protobuf type {@code proto.ChatConvertToGroup}
     */
    public static final class ChatConvertToGroup extends
            com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:proto.ChatConvertToGroup)
            ChatConvertToGroupOrBuilder {
        // Use ChatConvertToGroup.newBuilder() to construct.
        private ChatConvertToGroup(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }

        private ChatConvertToGroup() {
            roomId_ = 0L;
            name_ = "";
            description_ = "";
        }

        @Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
        }

        private ChatConvertToGroup(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            this();
            int mutable_bitField0_ = 0;
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        default: {
                            if (!input.skipField(tag)) {
                                done = true;
                            }
                            break;
                        }
                        case 10: {
                            ProtoRequest.Request.Builder subBuilder = null;
                            if (request_ != null) {
                                subBuilder = request_.toBuilder();
                            }
                            request_ = input.readMessage(ProtoRequest.Request.parser(), extensionRegistry);
                            if (subBuilder != null) {
                                subBuilder.mergeFrom(request_);
                                request_ = subBuilder.buildPartial();
                            }

                            break;
                        }
                        case 16: {

                            roomId_ = input.readUInt64();
                            break;
                        }
                        case 26: {
                            String s = input.readStringRequireUtf8();

                            name_ = s;
                            break;
                        }
                        case 34: {
                            String s = input.readStringRequireUtf8();

                            description_ = s;
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e).setUnfinishedMessage(this);
            } finally {
                makeExtensionsImmutable();
            }
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return ProtoChatConvertToGroup.internal_static_proto_ChatConvertToGroup_descriptor;
        }

        protected FieldAccessorTable
        internalGetFieldAccessorTable() {
            return ProtoChatConvertToGroup.internal_static_proto_ChatConvertToGroup_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            ChatConvertToGroup.class, Builder.class);
        }

        public static final int REQUEST_FIELD_NUMBER = 1;
        private ProtoRequest.Request request_;

        /**
         * <code>optional .proto.Request request = 1;</code>
         */
        public boolean hasRequest() {
            return request_ != null;
        }

        /**
         * <code>optional .proto.Request request = 1;</code>
         */
        public ProtoRequest.Request getRequest() {
            return request_ == null ? ProtoRequest.Request.getDefaultInstance() : request_;
        }

        /**
         * <code>optional .proto.Request request = 1;</code>
         */
        public ProtoRequest.RequestOrBuilder getRequestOrBuilder() {
            return getRequest();
        }

        public static final int ROOM_ID_FIELD_NUMBER = 2;
        private long roomId_;

        /**
         * <code>optional uint64 room_id = 2;</code>
         */
        public long getRoomId() {
            return roomId_;
        }

        public static final int NAME_FIELD_NUMBER = 3;
        private volatile Object name_;

        /**
         * <code>optional string name = 3;</code>
         */
        public String getName() {
            Object ref = name_;
            if (ref instanceof String) {
                return (String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                name_ = s;
                return s;
            }
        }

        /**
         * <code>optional string name = 3;</code>
         */
        public com.google.protobuf.ByteString
        getNameBytes() {
            Object ref = name_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (String) ref);
                name_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int DESCRIPTION_FIELD_NUMBER = 4;
        private volatile Object description_;

        /**
         * <code>optional string description = 4;</code>
         */
        public String getDescription() {
            Object ref = description_;
            if (ref instanceof String) {
                return (String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                description_ = s;
                return s;
            }
        }

        /**
         * <code>optional string description = 4;</code>
         */
        public com.google.protobuf.ByteString
        getDescriptionBytes() {
            Object ref = description_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (String) ref);
                description_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        private byte memoizedIsInitialized = -1;

        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            if (request_ != null) {
                output.writeMessage(1, getRequest());
            }
            if (roomId_ != 0L) {
                output.writeUInt64(2, roomId_);
            }
            if (!getNameBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 3, name_);
            }
            if (!getDescriptionBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 4, description_);
            }
        }

        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            if (request_ != null) {
                size += com.google.protobuf.CodedOutputStream
                        .computeMessageSize(1, getRequest());
            }
            if (roomId_ != 0L) {
                size += com.google.protobuf.CodedOutputStream
                        .computeUInt64Size(2, roomId_);
            }
            if (!getNameBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, name_);
            }
            if (!getDescriptionBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, description_);
            }
            memoizedSize = size;
            return size;
        }

        private static final long serialVersionUID = 0L;

        @Override
        public boolean equals(final Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof ChatConvertToGroup)) {
                return super.equals(obj);
            }
            ChatConvertToGroup other = (ChatConvertToGroup) obj;

            boolean result = true;
            result = result && (hasRequest() == other.hasRequest());
            if (hasRequest()) {
                result = result && getRequest()
                        .equals(other.getRequest());
            }
            result = result && (getRoomId()
                    == other.getRoomId());
            result = result && getName()
                    .equals(other.getName());
            result = result && getDescription()
                    .equals(other.getDescription());
            return result;
        }

        @Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptorForType().hashCode();
            if (hasRequest()) {
                hash = (37 * hash) + REQUEST_FIELD_NUMBER;
                hash = (53 * hash) + getRequest().hashCode();
            }
            hash = (37 * hash) + ROOM_ID_FIELD_NUMBER;
            hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
                    getRoomId());
            hash = (37 * hash) + NAME_FIELD_NUMBER;
            hash = (53 * hash) + getName().hashCode();
            hash = (37 * hash) + DESCRIPTION_FIELD_NUMBER;
            hash = (53 * hash) + getDescription().hashCode();
            hash = (29 * hash) + unknownFields.hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public static ChatConvertToGroup parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static ChatConvertToGroup parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static ChatConvertToGroup parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static ChatConvertToGroup parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static ChatConvertToGroup parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static ChatConvertToGroup parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static ChatConvertToGroup parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input);
        }

        public static ChatConvertToGroup parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }

        public static ChatConvertToGroup parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static ChatConvertToGroup parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public Builder newBuilderForType() {
            return newBuilder();
        }

        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(ChatConvertToGroup prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @Override
        protected Builder newBuilderForType(
                BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        /**
         * Protobuf type {@code proto.ChatConvertToGroup}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:proto.ChatConvertToGroup)
                ChatConvertToGroupOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return ProtoChatConvertToGroup.internal_static_proto_ChatConvertToGroup_descriptor;
            }

            protected FieldAccessorTable
            internalGetFieldAccessorTable() {
                return ProtoChatConvertToGroup.internal_static_proto_ChatConvertToGroup_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                ChatConvertToGroup.class, Builder.class);
            }

            // Construct using com.iGap.proto.ProtoChatConvertToGroup.ChatConvertToGroup.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessageV3
                        .alwaysUseFieldBuilders) {
                }
            }

            public Builder clear() {
                super.clear();
                if (requestBuilder_ == null) {
                    request_ = null;
                } else {
                    request_ = null;
                    requestBuilder_ = null;
                }
                roomId_ = 0L;

                name_ = "";

                description_ = "";

                return this;
            }

            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return ProtoChatConvertToGroup.internal_static_proto_ChatConvertToGroup_descriptor;
            }

            public ChatConvertToGroup getDefaultInstanceForType() {
                return ChatConvertToGroup.getDefaultInstance();
            }

            public ChatConvertToGroup build() {
                ChatConvertToGroup result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            public ChatConvertToGroup buildPartial() {
                ChatConvertToGroup result = new ChatConvertToGroup(this);
                if (requestBuilder_ == null) {
                    result.request_ = request_;
                } else {
                    result.request_ = requestBuilder_.build();
                }
                result.roomId_ = roomId_;
                result.name_ = name_;
                result.description_ = description_;
                onBuilt();
                return result;
            }

            public Builder clone() {
                return (Builder) super.clone();
            }

            public Builder setField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    Object value) {
                return (Builder) super.setField(field, value);
            }

            public Builder clearField(
                    com.google.protobuf.Descriptors.FieldDescriptor field) {
                return (Builder) super.clearField(field);
            }

            public Builder clearOneof(
                    com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return (Builder) super.clearOneof(oneof);
            }

            public Builder setRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    int index, Object value) {
                return (Builder) super.setRepeatedField(field, index, value);
            }

            public Builder addRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    Object value) {
                return (Builder) super.addRepeatedField(field, value);
            }

            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof ChatConvertToGroup) {
                    return mergeFrom((ChatConvertToGroup) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(ChatConvertToGroup other) {
                if (other == ChatConvertToGroup.getDefaultInstance()) return this;
                if (other.hasRequest()) {
                    mergeRequest(other.getRequest());
                }
                if (other.getRoomId() != 0L) {
                    setRoomId(other.getRoomId());
                }
                if (!other.getName().isEmpty()) {
                    name_ = other.name_;
                    onChanged();
                }
                if (!other.getDescription().isEmpty()) {
                    description_ = other.description_;
                    onChanged();
                }
                onChanged();
                return this;
            }

            public final boolean isInitialized() {
                return true;
            }

            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                ChatConvertToGroup parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (ChatConvertToGroup) e.getUnfinishedMessage();
                    throw e.unwrapIOException();
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            private ProtoRequest.Request request_ = null;
            private com.google.protobuf.SingleFieldBuilderV3<
                    ProtoRequest.Request, ProtoRequest.Request.Builder, ProtoRequest.RequestOrBuilder> requestBuilder_;

            /**
             * <code>optional .proto.Request request = 1;</code>
             */
            public boolean hasRequest() {
                return requestBuilder_ != null || request_ != null;
            }

            /**
             * <code>optional .proto.Request request = 1;</code>
             */
            public ProtoRequest.Request getRequest() {
                if (requestBuilder_ == null) {
                    return request_ == null ? ProtoRequest.Request.getDefaultInstance() : request_;
                } else {
                    return requestBuilder_.getMessage();
                }
            }

            /**
             * <code>optional .proto.Request request = 1;</code>
             */
            public Builder setRequest(ProtoRequest.Request value) {
                if (requestBuilder_ == null) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    request_ = value;
                    onChanged();
                } else {
                    requestBuilder_.setMessage(value);
                }

                return this;
            }

            /**
             * <code>optional .proto.Request request = 1;</code>
             */
            public Builder setRequest(
                    ProtoRequest.Request.Builder builderForValue) {
                if (requestBuilder_ == null) {
                    request_ = builderForValue.build();
                    onChanged();
                } else {
                    requestBuilder_.setMessage(builderForValue.build());
                }

                return this;
            }

            /**
             * <code>optional .proto.Request request = 1;</code>
             */
            public Builder mergeRequest(ProtoRequest.Request value) {
                if (requestBuilder_ == null) {
                    if (request_ != null) {
                        request_ =
                                ProtoRequest.Request.newBuilder(request_).mergeFrom(value).buildPartial();
                    } else {
                        request_ = value;
                    }
                    onChanged();
                } else {
                    requestBuilder_.mergeFrom(value);
                }

                return this;
            }

            /**
             * <code>optional .proto.Request request = 1;</code>
             */
            public Builder clearRequest() {
                if (requestBuilder_ == null) {
                    request_ = null;
                    onChanged();
                } else {
                    request_ = null;
                    requestBuilder_ = null;
                }

                return this;
            }

            /**
             * <code>optional .proto.Request request = 1;</code>
             */
            public ProtoRequest.Request.Builder getRequestBuilder() {

                onChanged();
                return getRequestFieldBuilder().getBuilder();
            }

            /**
             * <code>optional .proto.Request request = 1;</code>
             */
            public ProtoRequest.RequestOrBuilder getRequestOrBuilder() {
                if (requestBuilder_ != null) {
                    return requestBuilder_.getMessageOrBuilder();
                } else {
                    return request_ == null ?
                            ProtoRequest.Request.getDefaultInstance() : request_;
                }
            }

            /**
             * <code>optional .proto.Request request = 1;</code>
             */
            private com.google.protobuf.SingleFieldBuilderV3<
                    ProtoRequest.Request, ProtoRequest.Request.Builder, ProtoRequest.RequestOrBuilder>
            getRequestFieldBuilder() {
                if (requestBuilder_ == null) {
                    requestBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
                            ProtoRequest.Request, ProtoRequest.Request.Builder, ProtoRequest.RequestOrBuilder>(
                            getRequest(),
                            getParentForChildren(),
                            isClean());
                    request_ = null;
                }
                return requestBuilder_;
            }

            private long roomId_;

            /**
             * <code>optional uint64 room_id = 2;</code>
             */
            public long getRoomId() {
                return roomId_;
            }

            /**
             * <code>optional uint64 room_id = 2;</code>
             */
            public Builder setRoomId(long value) {

                roomId_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>optional uint64 room_id = 2;</code>
             */
            public Builder clearRoomId() {

                roomId_ = 0L;
                onChanged();
                return this;
            }

            private Object name_ = "";

            /**
             * <code>optional string name = 3;</code>
             */
            public String getName() {
                Object ref = name_;
                if (!(ref instanceof String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    String s = bs.toStringUtf8();
                    name_ = s;
                    return s;
                } else {
                    return (String) ref;
                }
            }

            /**
             * <code>optional string name = 3;</code>
             */
            public com.google.protobuf.ByteString
            getNameBytes() {
                Object ref = name_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (String) ref);
                    name_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>optional string name = 3;</code>
             */
            public Builder setName(
                    String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                name_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>optional string name = 3;</code>
             */
            public Builder clearName() {

                name_ = getDefaultInstance().getName();
                onChanged();
                return this;
            }

            /**
             * <code>optional string name = 3;</code>
             */
            public Builder setNameBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                name_ = value;
                onChanged();
                return this;
            }

            private Object description_ = "";

            /**
             * <code>optional string description = 4;</code>
             */
            public String getDescription() {
                Object ref = description_;
                if (!(ref instanceof String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    String s = bs.toStringUtf8();
                    description_ = s;
                    return s;
                } else {
                    return (String) ref;
                }
            }

            /**
             * <code>optional string description = 4;</code>
             */
            public com.google.protobuf.ByteString
            getDescriptionBytes() {
                Object ref = description_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (String) ref);
                    description_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>optional string description = 4;</code>
             */
            public Builder setDescription(
                    String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                description_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>optional string description = 4;</code>
             */
            public Builder clearDescription() {

                description_ = getDefaultInstance().getDescription();
                onChanged();
                return this;
            }

            /**
             * <code>optional string description = 4;</code>
             */
            public Builder setDescriptionBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                description_ = value;
                onChanged();
                return this;
            }

            public final Builder setUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return this;
            }

            public final Builder mergeUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return this;
            }


            // @@protoc_insertion_point(builder_scope:proto.ChatConvertToGroup)
        }

        // @@protoc_insertion_point(class_scope:proto.ChatConvertToGroup)
        private static final ChatConvertToGroup DEFAULT_INSTANCE;

        static {
            DEFAULT_INSTANCE = new ChatConvertToGroup();
        }

        public static ChatConvertToGroup getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        private static final com.google.protobuf.Parser<ChatConvertToGroup>
                PARSER = new com.google.protobuf.AbstractParser<ChatConvertToGroup>() {
            public ChatConvertToGroup parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return new ChatConvertToGroup(input, extensionRegistry);
            }
        };

        public static com.google.protobuf.Parser<ChatConvertToGroup> parser() {
            return PARSER;
        }

        @Override
        public com.google.protobuf.Parser<ChatConvertToGroup> getParserForType() {
            return PARSER;
        }

        public ChatConvertToGroup getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

    }

    public interface ChatConvertToGroupResponseOrBuilder extends
            // @@protoc_insertion_point(interface_extends:proto.ChatConvertToGroupResponse)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>optional .proto.Response response = 1;</code>
         */
        boolean hasResponse();

        /**
         * <code>optional .proto.Response response = 1;</code>
         */
        ProtoResponse.Response getResponse();

        /**
         * <code>optional .proto.Response response = 1;</code>
         */
        ProtoResponse.ResponseOrBuilder getResponseOrBuilder();

        /**
         * <code>optional uint64 room_id = 2;</code>
         */
        long getRoomId();

        /**
         * <code>optional string name = 3;</code>
         */
        String getName();

        /**
         * <code>optional string name = 3;</code>
         */
        com.google.protobuf.ByteString
        getNameBytes();

        /**
         * <code>optional string description = 4;</code>
         */
        String getDescription();

        /**
         * <code>optional string description = 4;</code>
         */
        com.google.protobuf.ByteString
        getDescriptionBytes();

        /**
         * <code>optional .proto.GroupRoom.Role role = 5;</code>
         */
        int getRoleValue();

        /**
         * <code>optional .proto.GroupRoom.Role role = 5;</code>
         */
        ProtoGlobal.GroupRoom.Role getRole();
    }

    /**
     * Protobuf type {@code proto.ChatConvertToGroupResponse}
     */
    public static final class ChatConvertToGroupResponse extends
            com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:proto.ChatConvertToGroupResponse)
            ChatConvertToGroupResponseOrBuilder {
        // Use ChatConvertToGroupResponse.newBuilder() to construct.
        private ChatConvertToGroupResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }

        private ChatConvertToGroupResponse() {
            roomId_ = 0L;
            name_ = "";
            description_ = "";
            role_ = 0;
        }

        @Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
        }

        private ChatConvertToGroupResponse(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            this();
            int mutable_bitField0_ = 0;
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        default: {
                            if (!input.skipField(tag)) {
                                done = true;
                            }
                            break;
                        }
                        case 10: {
                            ProtoResponse.Response.Builder subBuilder = null;
                            if (response_ != null) {
                                subBuilder = response_.toBuilder();
                            }
                            response_ = input.readMessage(ProtoResponse.Response.parser(), extensionRegistry);
                            if (subBuilder != null) {
                                subBuilder.mergeFrom(response_);
                                response_ = subBuilder.buildPartial();
                            }

                            break;
                        }
                        case 16: {

                            roomId_ = input.readUInt64();
                            break;
                        }
                        case 26: {
                            String s = input.readStringRequireUtf8();

                            name_ = s;
                            break;
                        }
                        case 34: {
                            String s = input.readStringRequireUtf8();

                            description_ = s;
                            break;
                        }
                        case 40: {
                            int rawValue = input.readEnum();

                            role_ = rawValue;
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e).setUnfinishedMessage(this);
            } finally {
                makeExtensionsImmutable();
            }
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return ProtoChatConvertToGroup.internal_static_proto_ChatConvertToGroupResponse_descriptor;
        }

        protected FieldAccessorTable
        internalGetFieldAccessorTable() {
            return ProtoChatConvertToGroup.internal_static_proto_ChatConvertToGroupResponse_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            ChatConvertToGroupResponse.class, Builder.class);
        }

        public static final int RESPONSE_FIELD_NUMBER = 1;
        private ProtoResponse.Response response_;

        /**
         * <code>optional .proto.Response response = 1;</code>
         */
        public boolean hasResponse() {
            return response_ != null;
        }

        /**
         * <code>optional .proto.Response response = 1;</code>
         */
        public ProtoResponse.Response getResponse() {
            return response_ == null ? ProtoResponse.Response.getDefaultInstance() : response_;
        }

        /**
         * <code>optional .proto.Response response = 1;</code>
         */
        public ProtoResponse.ResponseOrBuilder getResponseOrBuilder() {
            return getResponse();
        }

        public static final int ROOM_ID_FIELD_NUMBER = 2;
        private long roomId_;

        /**
         * <code>optional uint64 room_id = 2;</code>
         */
        public long getRoomId() {
            return roomId_;
        }

        public static final int NAME_FIELD_NUMBER = 3;
        private volatile Object name_;

        /**
         * <code>optional string name = 3;</code>
         */
        public String getName() {
            Object ref = name_;
            if (ref instanceof String) {
                return (String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                name_ = s;
                return s;
            }
        }

        /**
         * <code>optional string name = 3;</code>
         */
        public com.google.protobuf.ByteString
        getNameBytes() {
            Object ref = name_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (String) ref);
                name_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int DESCRIPTION_FIELD_NUMBER = 4;
        private volatile Object description_;

        /**
         * <code>optional string description = 4;</code>
         */
        public String getDescription() {
            Object ref = description_;
            if (ref instanceof String) {
                return (String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                description_ = s;
                return s;
            }
        }

        /**
         * <code>optional string description = 4;</code>
         */
        public com.google.protobuf.ByteString
        getDescriptionBytes() {
            Object ref = description_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (String) ref);
                description_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int ROLE_FIELD_NUMBER = 5;
        private int role_;

        /**
         * <code>optional .proto.GroupRoom.Role role = 5;</code>
         */
        public int getRoleValue() {
            return role_;
        }

        /**
         * <code>optional .proto.GroupRoom.Role role = 5;</code>
         */
        public ProtoGlobal.GroupRoom.Role getRole() {
            ProtoGlobal.GroupRoom.Role result = ProtoGlobal.GroupRoom.Role.valueOf(role_);
            return result == null ? ProtoGlobal.GroupRoom.Role.UNRECOGNIZED : result;
        }

        private byte memoizedIsInitialized = -1;

        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            if (response_ != null) {
                output.writeMessage(1, getResponse());
            }
            if (roomId_ != 0L) {
                output.writeUInt64(2, roomId_);
            }
            if (!getNameBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 3, name_);
            }
            if (!getDescriptionBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 4, description_);
            }
            if (role_ != ProtoGlobal.GroupRoom.Role.MEMBER.getNumber()) {
                output.writeEnum(5, role_);
            }
        }

        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            if (response_ != null) {
                size += com.google.protobuf.CodedOutputStream
                        .computeMessageSize(1, getResponse());
            }
            if (roomId_ != 0L) {
                size += com.google.protobuf.CodedOutputStream
                        .computeUInt64Size(2, roomId_);
            }
            if (!getNameBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, name_);
            }
            if (!getDescriptionBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, description_);
            }
            if (role_ != ProtoGlobal.GroupRoom.Role.MEMBER.getNumber()) {
                size += com.google.protobuf.CodedOutputStream
                        .computeEnumSize(5, role_);
            }
            memoizedSize = size;
            return size;
        }

        private static final long serialVersionUID = 0L;

        @Override
        public boolean equals(final Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof ChatConvertToGroupResponse)) {
                return super.equals(obj);
            }
            ChatConvertToGroupResponse other = (ChatConvertToGroupResponse) obj;

            boolean result = true;
            result = result && (hasResponse() == other.hasResponse());
            if (hasResponse()) {
                result = result && getResponse()
                        .equals(other.getResponse());
            }
            result = result && (getRoomId()
                    == other.getRoomId());
            result = result && getName()
                    .equals(other.getName());
            result = result && getDescription()
                    .equals(other.getDescription());
            result = result && role_ == other.role_;
            return result;
        }

        @Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptorForType().hashCode();
            if (hasResponse()) {
                hash = (37 * hash) + RESPONSE_FIELD_NUMBER;
                hash = (53 * hash) + getResponse().hashCode();
            }
            hash = (37 * hash) + ROOM_ID_FIELD_NUMBER;
            hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
                    getRoomId());
            hash = (37 * hash) + NAME_FIELD_NUMBER;
            hash = (53 * hash) + getName().hashCode();
            hash = (37 * hash) + DESCRIPTION_FIELD_NUMBER;
            hash = (53 * hash) + getDescription().hashCode();
            hash = (37 * hash) + ROLE_FIELD_NUMBER;
            hash = (53 * hash) + role_;
            hash = (29 * hash) + unknownFields.hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public static ChatConvertToGroupResponse parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static ChatConvertToGroupResponse parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static ChatConvertToGroupResponse parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static ChatConvertToGroupResponse parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static ChatConvertToGroupResponse parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static ChatConvertToGroupResponse parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static ChatConvertToGroupResponse parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input);
        }

        public static ChatConvertToGroupResponse parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }

        public static ChatConvertToGroupResponse parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static ChatConvertToGroupResponse parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public Builder newBuilderForType() {
            return newBuilder();
        }

        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(ChatConvertToGroupResponse prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @Override
        protected Builder newBuilderForType(
                BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        /**
         * Protobuf type {@code proto.ChatConvertToGroupResponse}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:proto.ChatConvertToGroupResponse)
                ChatConvertToGroupResponseOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return ProtoChatConvertToGroup.internal_static_proto_ChatConvertToGroupResponse_descriptor;
            }

            protected FieldAccessorTable
            internalGetFieldAccessorTable() {
                return ProtoChatConvertToGroup.internal_static_proto_ChatConvertToGroupResponse_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                ChatConvertToGroupResponse.class, Builder.class);
            }

            // Construct using com.iGap.proto.ProtoChatConvertToGroup.ChatConvertToGroupResponse.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessageV3
                        .alwaysUseFieldBuilders) {
                }
            }

            public Builder clear() {
                super.clear();
                if (responseBuilder_ == null) {
                    response_ = null;
                } else {
                    response_ = null;
                    responseBuilder_ = null;
                }
                roomId_ = 0L;

                name_ = "";

                description_ = "";

                role_ = 0;

                return this;
            }

            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return ProtoChatConvertToGroup.internal_static_proto_ChatConvertToGroupResponse_descriptor;
            }

            public ChatConvertToGroupResponse getDefaultInstanceForType() {
                return ChatConvertToGroupResponse.getDefaultInstance();
            }

            public ChatConvertToGroupResponse build() {
                ChatConvertToGroupResponse result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            public ChatConvertToGroupResponse buildPartial() {
                ChatConvertToGroupResponse result = new ChatConvertToGroupResponse(this);
                if (responseBuilder_ == null) {
                    result.response_ = response_;
                } else {
                    result.response_ = responseBuilder_.build();
                }
                result.roomId_ = roomId_;
                result.name_ = name_;
                result.description_ = description_;
                result.role_ = role_;
                onBuilt();
                return result;
            }

            public Builder clone() {
                return (Builder) super.clone();
            }

            public Builder setField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    Object value) {
                return (Builder) super.setField(field, value);
            }

            public Builder clearField(
                    com.google.protobuf.Descriptors.FieldDescriptor field) {
                return (Builder) super.clearField(field);
            }

            public Builder clearOneof(
                    com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return (Builder) super.clearOneof(oneof);
            }

            public Builder setRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    int index, Object value) {
                return (Builder) super.setRepeatedField(field, index, value);
            }

            public Builder addRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    Object value) {
                return (Builder) super.addRepeatedField(field, value);
            }

            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof ChatConvertToGroupResponse) {
                    return mergeFrom((ChatConvertToGroupResponse) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(ChatConvertToGroupResponse other) {
                if (other == ChatConvertToGroupResponse.getDefaultInstance()) return this;
                if (other.hasResponse()) {
                    mergeResponse(other.getResponse());
                }
                if (other.getRoomId() != 0L) {
                    setRoomId(other.getRoomId());
                }
                if (!other.getName().isEmpty()) {
                    name_ = other.name_;
                    onChanged();
                }
                if (!other.getDescription().isEmpty()) {
                    description_ = other.description_;
                    onChanged();
                }
                if (other.role_ != 0) {
                    setRoleValue(other.getRoleValue());
                }
                onChanged();
                return this;
            }

            public final boolean isInitialized() {
                return true;
            }

            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                ChatConvertToGroupResponse parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (ChatConvertToGroupResponse) e.getUnfinishedMessage();
                    throw e.unwrapIOException();
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            private ProtoResponse.Response response_ = null;
            private com.google.protobuf.SingleFieldBuilderV3<
                    ProtoResponse.Response, ProtoResponse.Response.Builder, ProtoResponse.ResponseOrBuilder> responseBuilder_;

            /**
             * <code>optional .proto.Response response = 1;</code>
             */
            public boolean hasResponse() {
                return responseBuilder_ != null || response_ != null;
            }

            /**
             * <code>optional .proto.Response response = 1;</code>
             */
            public ProtoResponse.Response getResponse() {
                if (responseBuilder_ == null) {
                    return response_ == null ? ProtoResponse.Response.getDefaultInstance() : response_;
                } else {
                    return responseBuilder_.getMessage();
                }
            }

            /**
             * <code>optional .proto.Response response = 1;</code>
             */
            public Builder setResponse(ProtoResponse.Response value) {
                if (responseBuilder_ == null) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    response_ = value;
                    onChanged();
                } else {
                    responseBuilder_.setMessage(value);
                }

                return this;
            }

            /**
             * <code>optional .proto.Response response = 1;</code>
             */
            public Builder setResponse(
                    ProtoResponse.Response.Builder builderForValue) {
                if (responseBuilder_ == null) {
                    response_ = builderForValue.build();
                    onChanged();
                } else {
                    responseBuilder_.setMessage(builderForValue.build());
                }

                return this;
            }

            /**
             * <code>optional .proto.Response response = 1;</code>
             */
            public Builder mergeResponse(ProtoResponse.Response value) {
                if (responseBuilder_ == null) {
                    if (response_ != null) {
                        response_ =
                                ProtoResponse.Response.newBuilder(response_).mergeFrom(value).buildPartial();
                    } else {
                        response_ = value;
                    }
                    onChanged();
                } else {
                    responseBuilder_.mergeFrom(value);
                }

                return this;
            }

            /**
             * <code>optional .proto.Response response = 1;</code>
             */
            public Builder clearResponse() {
                if (responseBuilder_ == null) {
                    response_ = null;
                    onChanged();
                } else {
                    response_ = null;
                    responseBuilder_ = null;
                }

                return this;
            }

            /**
             * <code>optional .proto.Response response = 1;</code>
             */
            public ProtoResponse.Response.Builder getResponseBuilder() {

                onChanged();
                return getResponseFieldBuilder().getBuilder();
            }

            /**
             * <code>optional .proto.Response response = 1;</code>
             */
            public ProtoResponse.ResponseOrBuilder getResponseOrBuilder() {
                if (responseBuilder_ != null) {
                    return responseBuilder_.getMessageOrBuilder();
                } else {
                    return response_ == null ?
                            ProtoResponse.Response.getDefaultInstance() : response_;
                }
            }

            /**
             * <code>optional .proto.Response response = 1;</code>
             */
            private com.google.protobuf.SingleFieldBuilderV3<
                    ProtoResponse.Response, ProtoResponse.Response.Builder, ProtoResponse.ResponseOrBuilder>
            getResponseFieldBuilder() {
                if (responseBuilder_ == null) {
                    responseBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
                            ProtoResponse.Response, ProtoResponse.Response.Builder, ProtoResponse.ResponseOrBuilder>(
                            getResponse(),
                            getParentForChildren(),
                            isClean());
                    response_ = null;
                }
                return responseBuilder_;
            }

            private long roomId_;

            /**
             * <code>optional uint64 room_id = 2;</code>
             */
            public long getRoomId() {
                return roomId_;
            }

            /**
             * <code>optional uint64 room_id = 2;</code>
             */
            public Builder setRoomId(long value) {

                roomId_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>optional uint64 room_id = 2;</code>
             */
            public Builder clearRoomId() {

                roomId_ = 0L;
                onChanged();
                return this;
            }

            private Object name_ = "";

            /**
             * <code>optional string name = 3;</code>
             */
            public String getName() {
                Object ref = name_;
                if (!(ref instanceof String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    String s = bs.toStringUtf8();
                    name_ = s;
                    return s;
                } else {
                    return (String) ref;
                }
            }

            /**
             * <code>optional string name = 3;</code>
             */
            public com.google.protobuf.ByteString
            getNameBytes() {
                Object ref = name_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (String) ref);
                    name_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>optional string name = 3;</code>
             */
            public Builder setName(
                    String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                name_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>optional string name = 3;</code>
             */
            public Builder clearName() {

                name_ = getDefaultInstance().getName();
                onChanged();
                return this;
            }

            /**
             * <code>optional string name = 3;</code>
             */
            public Builder setNameBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                name_ = value;
                onChanged();
                return this;
            }

            private Object description_ = "";

            /**
             * <code>optional string description = 4;</code>
             */
            public String getDescription() {
                Object ref = description_;
                if (!(ref instanceof String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    String s = bs.toStringUtf8();
                    description_ = s;
                    return s;
                } else {
                    return (String) ref;
                }
            }

            /**
             * <code>optional string description = 4;</code>
             */
            public com.google.protobuf.ByteString
            getDescriptionBytes() {
                Object ref = description_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (String) ref);
                    description_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>optional string description = 4;</code>
             */
            public Builder setDescription(
                    String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                description_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>optional string description = 4;</code>
             */
            public Builder clearDescription() {

                description_ = getDefaultInstance().getDescription();
                onChanged();
                return this;
            }

            /**
             * <code>optional string description = 4;</code>
             */
            public Builder setDescriptionBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                description_ = value;
                onChanged();
                return this;
            }

            private int role_ = 0;

            /**
             * <code>optional .proto.GroupRoom.Role role = 5;</code>
             */
            public int getRoleValue() {
                return role_;
            }

            /**
             * <code>optional .proto.GroupRoom.Role role = 5;</code>
             */
            public Builder setRoleValue(int value) {
                role_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>optional .proto.GroupRoom.Role role = 5;</code>
             */
            public ProtoGlobal.GroupRoom.Role getRole() {
                ProtoGlobal.GroupRoom.Role result = ProtoGlobal.GroupRoom.Role.valueOf(role_);
                return result == null ? ProtoGlobal.GroupRoom.Role.UNRECOGNIZED : result;
            }

            /**
             * <code>optional .proto.GroupRoom.Role role = 5;</code>
             */
            public Builder setRole(ProtoGlobal.GroupRoom.Role value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                role_ = value.getNumber();
                onChanged();
                return this;
            }

            /**
             * <code>optional .proto.GroupRoom.Role role = 5;</code>
             */
            public Builder clearRole() {

                role_ = 0;
                onChanged();
                return this;
            }

            public final Builder setUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return this;
            }

            public final Builder mergeUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return this;
            }


            // @@protoc_insertion_point(builder_scope:proto.ChatConvertToGroupResponse)
        }

        // @@protoc_insertion_point(class_scope:proto.ChatConvertToGroupResponse)
        private static final ChatConvertToGroupResponse DEFAULT_INSTANCE;

        static {
            DEFAULT_INSTANCE = new ChatConvertToGroupResponse();
        }

        public static ChatConvertToGroupResponse getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        private static final com.google.protobuf.Parser<ChatConvertToGroupResponse>
                PARSER = new com.google.protobuf.AbstractParser<ChatConvertToGroupResponse>() {
            public ChatConvertToGroupResponse parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return new ChatConvertToGroupResponse(input, extensionRegistry);
            }
        };

        public static com.google.protobuf.Parser<ChatConvertToGroupResponse> parser() {
            return PARSER;
        }

        @Override
        public com.google.protobuf.Parser<ChatConvertToGroupResponse> getParserForType() {
            return PARSER;
        }

        public ChatConvertToGroupResponse getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

    }

    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_proto_ChatConvertToGroup_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_proto_ChatConvertToGroup_fieldAccessorTable;
    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_proto_ChatConvertToGroupResponse_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_proto_ChatConvertToGroupResponse_fieldAccessorTable;

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }

    private static com.google.protobuf.Descriptors.FileDescriptor
            descriptor;

    static {
        String[] descriptorData = {
                "\n\030ChatConvertToGroup.proto\022\005proto\032\rReque" +
                        "st.proto\032\016Response.proto\032\014Global.proto\"i" +
                        "\n\022ChatConvertToGroup\022\037\n\007request\030\001 \001(\0132\016." +
                        "proto.Request\022\017\n\007room_id\030\002 \001(\004\022\014\n\004name\030\003" +
                        " \001(\t\022\023\n\013description\030\004 \001(\t\"\230\001\n\032ChatConver" +
                        "tToGroupResponse\022!\n\010response\030\001 \001(\0132\017.pro" +
                        "to.Response\022\017\n\007room_id\030\002 \001(\004\022\014\n\004name\030\003 \001" +
                        "(\t\022\023\n\013description\030\004 \001(\t\022#\n\004role\030\005 \001(\0162\025." +
                        "proto.GroupRoom.RoleB)\n\016com.iGap.protoB\027" +
                        "ProtoChatConvertToGroupb\006proto3"
        };
        com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
                new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
                    public com.google.protobuf.ExtensionRegistry assignDescriptors(
                            com.google.protobuf.Descriptors.FileDescriptor root) {
                        descriptor = root;
                        return null;
                    }
                };
        com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[]{
                                ProtoRequest.getDescriptor(),
                                ProtoResponse.getDescriptor(),
                                ProtoGlobal.getDescriptor(),
                        }, assigner);
        internal_static_proto_ChatConvertToGroup_descriptor =
                getDescriptor().getMessageTypes().get(0);
        internal_static_proto_ChatConvertToGroup_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_proto_ChatConvertToGroup_descriptor,
                new String[]{"Request", "RoomId", "Name", "Description",});
        internal_static_proto_ChatConvertToGroupResponse_descriptor =
                getDescriptor().getMessageTypes().get(1);
        internal_static_proto_ChatConvertToGroupResponse_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_proto_ChatConvertToGroupResponse_descriptor,
                new String[]{"Response", "RoomId", "Name", "Description", "Role",});
        ProtoRequest.getDescriptor();
        ProtoResponse.getDescriptor();
        ProtoGlobal.getDescriptor();
    }

    // @@protoc_insertion_point(outer_class_scope)
}
