// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: UserVerify.proto

package com.iGap.proto;

public final class ProtoUserVerify {
  private ProtoUserVerify() {
  }

  public static void registerAllExtensions(
          com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
          com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
            (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public interface UserVerifyOrBuilder extends
          // @@protoc_insertion_point(interface_extends:proto.UserVerify)
          com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional .proto.Request request = 1;</code>
     */
    boolean hasRequest();

    /**
     * <code>optional .proto.Request request = 1;</code>
     */
    ProtoRequest.Request getRequest();

    /**
     * <code>optional .proto.Request request = 1;</code>
     */
    ProtoRequest.RequestOrBuilder getRequestOrBuilder();

    /**
     * <code>optional uint32 code = 2;</code>
     */
    int getCode();

    /**
     * <code>optional string username = 3;</code>
     */
    String getUsername();

    /**
     * <code>optional string username = 3;</code>
     */
    com.google.protobuf.ByteString
    getUsernameBytes();
  }

  /**
   * Protobuf type {@code proto.UserVerify}
   */
  public static final class UserVerify extends
          com.google.protobuf.GeneratedMessageV3 implements
          // @@protoc_insertion_point(message_implements:proto.UserVerify)
          UserVerifyOrBuilder {
    // Use UserVerify.newBuilder() to construct.
    private UserVerify(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }

    private UserVerify() {
      code_ = 0;
      username_ = "";
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }

    private UserVerify(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              ProtoRequest.Request.Builder subBuilder = null;
              if (request_ != null) {
                subBuilder = request_.toBuilder();
              }
              request_ = input.readMessage(ProtoRequest.Request.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(request_);
                request_ = subBuilder.buildPartial();
              }

              break;
            }
            case 16: {

              code_ = input.readUInt32();
              break;
            }
            case 26: {
              String s = input.readStringRequireUtf8();

              username_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
                e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }

    public static final com.google.protobuf.Descriptors.Descriptor
    getDescriptor() {
      return ProtoUserVerify.internal_static_proto_UserVerify_descriptor;
    }

    protected FieldAccessorTable
    internalGetFieldAccessorTable() {
      return ProtoUserVerify.internal_static_proto_UserVerify_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                      UserVerify.class, Builder.class);
    }

    public static final int REQUEST_FIELD_NUMBER = 1;
    private ProtoRequest.Request request_;

    /**
     * <code>optional .proto.Request request = 1;</code>
     */
    public boolean hasRequest() {
      return request_ != null;
    }

    /**
     * <code>optional .proto.Request request = 1;</code>
     */
    public ProtoRequest.Request getRequest() {
      return request_ == null ? ProtoRequest.Request.getDefaultInstance() : request_;
    }

    /**
     * <code>optional .proto.Request request = 1;</code>
     */
    public ProtoRequest.RequestOrBuilder getRequestOrBuilder() {
      return getRequest();
    }

    public static final int CODE_FIELD_NUMBER = 2;
    private int code_;

    /**
     * <code>optional uint32 code = 2;</code>
     */
    public int getCode() {
      return code_;
    }

    public static final int USERNAME_FIELD_NUMBER = 3;
    private volatile Object username_;

    /**
     * <code>optional string username = 3;</code>
     */
    public String getUsername() {
      Object ref = username_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        username_ = s;
        return s;
      }
    }

    /**
     * <code>optional string username = 3;</code>
     */
    public com.google.protobuf.ByteString
    getUsernameBytes() {
      Object ref = username_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
                com.google.protobuf.ByteString.copyFromUtf8(
                        (String) ref);
        username_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;

    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
            throws java.io.IOException {
      if (request_ != null) {
        output.writeMessage(1, getRequest());
      }
      if (code_ != 0) {
        output.writeUInt32(2, code_);
      }
      if (!getUsernameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, username_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (request_ != null) {
        size += com.google.protobuf.CodedOutputStream
                .computeMessageSize(1, getRequest());
      }
      if (code_ != 0) {
        size += com.google.protobuf.CodedOutputStream
                .computeUInt32Size(2, code_);
      }
      if (!getUsernameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, username_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
        return true;
      }
      if (!(obj instanceof UserVerify)) {
        return super.equals(obj);
      }
      UserVerify other = (UserVerify) obj;

      boolean result = true;
      result = result && (hasRequest() == other.hasRequest());
      if (hasRequest()) {
        result = result && getRequest()
                .equals(other.getRequest());
      }
      result = result && (getCode()
              == other.getCode());
      result = result && getUsername()
              .equals(other.getUsername());
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasRequest()) {
        hash = (37 * hash) + REQUEST_FIELD_NUMBER;
        hash = (53 * hash) + getRequest().hashCode();
      }
      hash = (37 * hash) + CODE_FIELD_NUMBER;
      hash = (53 * hash) + getCode();
      hash = (37 * hash) + USERNAME_FIELD_NUMBER;
      hash = (53 * hash) + getUsername().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static UserVerify parseFrom(
            com.google.protobuf.ByteString data)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }

    public static UserVerify parseFrom(
            com.google.protobuf.ByteString data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }

    public static UserVerify parseFrom(byte[] data)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }

    public static UserVerify parseFrom(
            byte[] data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }

    public static UserVerify parseFrom(java.io.InputStream input)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseWithIOException(PARSER, input);
    }

    public static UserVerify parseFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static UserVerify parseDelimitedFrom(java.io.InputStream input)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseDelimitedWithIOException(PARSER, input);
    }

    public static UserVerify parseDelimitedFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }

    public static UserVerify parseFrom(
            com.google.protobuf.CodedInputStream input)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseWithIOException(PARSER, input);
    }

    public static UserVerify parseFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() {
      return newBuilder();
    }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }

    public static Builder newBuilder(UserVerify prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
              ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
            BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }

    /**
     * Protobuf type {@code proto.UserVerify}
     */
    public static final class Builder extends
            com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:proto.UserVerify)
            UserVerifyOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
        return ProtoUserVerify.internal_static_proto_UserVerify_descriptor;
      }

      protected FieldAccessorTable
      internalGetFieldAccessorTable() {
        return ProtoUserVerify.internal_static_proto_UserVerify_fieldAccessorTable
                .ensureFieldAccessorsInitialized(
                        UserVerify.class, Builder.class);
      }

      // Construct using com.iGap.proto.ProtoUserVerify.UserVerify.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
              BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }

      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }

      public Builder clear() {
        super.clear();
        if (requestBuilder_ == null) {
          request_ = null;
        } else {
          request_ = null;
          requestBuilder_ = null;
        }
        code_ = 0;

        username_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
      getDescriptorForType() {
        return ProtoUserVerify.internal_static_proto_UserVerify_descriptor;
      }

      public UserVerify getDefaultInstanceForType() {
        return UserVerify.getDefaultInstance();
      }

      public UserVerify build() {
        UserVerify result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public UserVerify buildPartial() {
        UserVerify result = new UserVerify(this);
        if (requestBuilder_ == null) {
          result.request_ = request_;
        } else {
          result.request_ = requestBuilder_.build();
        }
        result.code_ = code_;
        result.username_ = username_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }

      public Builder setField(
              com.google.protobuf.Descriptors.FieldDescriptor field,
              Object value) {
        return (Builder) super.setField(field, value);
      }

      public Builder clearField(
              com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }

      public Builder clearOneof(
              com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }

      public Builder setRepeatedField(
              com.google.protobuf.Descriptors.FieldDescriptor field,
              int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }

      public Builder addRepeatedField(
              com.google.protobuf.Descriptors.FieldDescriptor field,
              Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof UserVerify) {
          return mergeFrom((UserVerify) other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(UserVerify other) {
        if (other == UserVerify.getDefaultInstance()) return this;
        if (other.hasRequest()) {
          mergeRequest(other.getRequest());
        }
        if (other.getCode() != 0) {
          setCode(other.getCode());
        }
        if (!other.getUsername().isEmpty()) {
          username_ = other.username_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
              com.google.protobuf.CodedInputStream input,
              com.google.protobuf.ExtensionRegistryLite extensionRegistry)
              throws java.io.IOException {
        UserVerify parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (UserVerify) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private ProtoRequest.Request request_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
              ProtoRequest.Request, ProtoRequest.Request.Builder, ProtoRequest.RequestOrBuilder> requestBuilder_;

      /**
       * <code>optional .proto.Request request = 1;</code>
       */
      public boolean hasRequest() {
        return requestBuilder_ != null || request_ != null;
      }

      /**
       * <code>optional .proto.Request request = 1;</code>
       */
      public ProtoRequest.Request getRequest() {
        if (requestBuilder_ == null) {
          return request_ == null ? ProtoRequest.Request.getDefaultInstance() : request_;
        } else {
          return requestBuilder_.getMessage();
        }
      }

      /**
       * <code>optional .proto.Request request = 1;</code>
       */
      public Builder setRequest(ProtoRequest.Request value) {
        if (requestBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          request_ = value;
          onChanged();
        } else {
          requestBuilder_.setMessage(value);
        }

        return this;
      }

      /**
       * <code>optional .proto.Request request = 1;</code>
       */
      public Builder setRequest(
              ProtoRequest.Request.Builder builderForValue) {
        if (requestBuilder_ == null) {
          request_ = builderForValue.build();
          onChanged();
        } else {
          requestBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }

      /**
       * <code>optional .proto.Request request = 1;</code>
       */
      public Builder mergeRequest(ProtoRequest.Request value) {
        if (requestBuilder_ == null) {
          if (request_ != null) {
            request_ =
                    ProtoRequest.Request.newBuilder(request_).mergeFrom(value).buildPartial();
          } else {
            request_ = value;
          }
          onChanged();
        } else {
          requestBuilder_.mergeFrom(value);
        }

        return this;
      }

      /**
       * <code>optional .proto.Request request = 1;</code>
       */
      public Builder clearRequest() {
        if (requestBuilder_ == null) {
          request_ = null;
          onChanged();
        } else {
          request_ = null;
          requestBuilder_ = null;
        }

        return this;
      }

      /**
       * <code>optional .proto.Request request = 1;</code>
       */
      public ProtoRequest.Request.Builder getRequestBuilder() {

        onChanged();
        return getRequestFieldBuilder().getBuilder();
      }

      /**
       * <code>optional .proto.Request request = 1;</code>
       */
      public ProtoRequest.RequestOrBuilder getRequestOrBuilder() {
        if (requestBuilder_ != null) {
          return requestBuilder_.getMessageOrBuilder();
        } else {
          return request_ == null ?
                  ProtoRequest.Request.getDefaultInstance() : request_;
        }
      }

      /**
       * <code>optional .proto.Request request = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
              ProtoRequest.Request, ProtoRequest.Request.Builder, ProtoRequest.RequestOrBuilder>
      getRequestFieldBuilder() {
        if (requestBuilder_ == null) {
          requestBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
                  ProtoRequest.Request, ProtoRequest.Request.Builder, ProtoRequest.RequestOrBuilder>(
                  getRequest(),
                  getParentForChildren(),
                  isClean());
          request_ = null;
        }
        return requestBuilder_;
      }

      private int code_;

      /**
       * <code>optional uint32 code = 2;</code>
       */
      public int getCode() {
        return code_;
      }

      /**
       * <code>optional uint32 code = 2;</code>
       */
      public Builder setCode(int value) {

        code_ = value;
        onChanged();
        return this;
      }

      /**
       * <code>optional uint32 code = 2;</code>
       */
      public Builder clearCode() {

        code_ = 0;
        onChanged();
        return this;
      }

      private Object username_ = "";

      /**
       * <code>optional string username = 3;</code>
       */
      public String getUsername() {
        Object ref = username_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
                  (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          username_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }

      /**
       * <code>optional string username = 3;</code>
       */
      public com.google.protobuf.ByteString
      getUsernameBytes() {
        Object ref = username_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
                  com.google.protobuf.ByteString.copyFromUtf8(
                          (String) ref);
          username_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      /**
       * <code>optional string username = 3;</code>
       */
      public Builder setUsername(
              String value) {
        if (value == null) {
          throw new NullPointerException();
        }

        username_ = value;
        onChanged();
        return this;
      }

      /**
       * <code>optional string username = 3;</code>
       */
      public Builder clearUsername() {

        username_ = getDefaultInstance().getUsername();
        onChanged();
        return this;
      }

      /**
       * <code>optional string username = 3;</code>
       */
      public Builder setUsernameBytes(
              com.google.protobuf.ByteString value) {
        if (value == null) {
          throw new NullPointerException();
        }
        checkByteStringIsUtf8(value);

        username_ = value;
        onChanged();
        return this;
      }

      public final Builder setUnknownFields(
              final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
              final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:proto.UserVerify)
    }

    // @@protoc_insertion_point(class_scope:proto.UserVerify)
    private static final UserVerify DEFAULT_INSTANCE;

    static {
      DEFAULT_INSTANCE = new UserVerify();
    }

    public static UserVerify getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<UserVerify>
            PARSER = new com.google.protobuf.AbstractParser<UserVerify>() {
      public UserVerify parsePartialFrom(
              com.google.protobuf.CodedInputStream input,
              com.google.protobuf.ExtensionRegistryLite extensionRegistry)
              throws com.google.protobuf.InvalidProtocolBufferException {
        return new UserVerify(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<UserVerify> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<UserVerify> getParserForType() {
      return PARSER;
    }

    public UserVerify getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface UserVerifyResponseOrBuilder extends
          // @@protoc_insertion_point(interface_extends:proto.UserVerifyResponse)
          com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional .proto.Response response = 1;</code>
     */
    boolean hasResponse();

    /**
     * <code>optional .proto.Response response = 1;</code>
     */
    ProtoResponse.Response getResponse();

    /**
     * <code>optional .proto.Response response = 1;</code>
     */
    ProtoResponse.ResponseOrBuilder getResponseOrBuilder();

    /**
     * <code>optional string token = 2;</code>
     */
    String getToken();

    /**
     * <code>optional string token = 2;</code>
     */
    com.google.protobuf.ByteString
    getTokenBytes();

    /**
     * <code>optional bool new_user = 3;</code>
     */
    boolean getNewUser();
  }

  /**
   * Protobuf type {@code proto.UserVerifyResponse}
   */
  public static final class UserVerifyResponse extends
          com.google.protobuf.GeneratedMessageV3 implements
          // @@protoc_insertion_point(message_implements:proto.UserVerifyResponse)
          UserVerifyResponseOrBuilder {
    // Use UserVerifyResponse.newBuilder() to construct.
    private UserVerifyResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }

    private UserVerifyResponse() {
      token_ = "";
      newUser_ = false;
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }

    private UserVerifyResponse(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              ProtoResponse.Response.Builder subBuilder = null;
              if (response_ != null) {
                subBuilder = response_.toBuilder();
              }
              response_ = input.readMessage(ProtoResponse.Response.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(response_);
                response_ = subBuilder.buildPartial();
              }

              break;
            }
            case 18: {
              String s = input.readStringRequireUtf8();

              token_ = s;
              break;
            }
            case 24: {

              newUser_ = input.readBool();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
                e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }

    public static final com.google.protobuf.Descriptors.Descriptor
    getDescriptor() {
      return ProtoUserVerify.internal_static_proto_UserVerifyResponse_descriptor;
    }

    protected FieldAccessorTable
    internalGetFieldAccessorTable() {
      return ProtoUserVerify.internal_static_proto_UserVerifyResponse_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                      UserVerifyResponse.class, Builder.class);
    }

    public static final int RESPONSE_FIELD_NUMBER = 1;
    private ProtoResponse.Response response_;

    /**
     * <code>optional .proto.Response response = 1;</code>
     */
    public boolean hasResponse() {
      return response_ != null;
    }

    /**
     * <code>optional .proto.Response response = 1;</code>
     */
    public ProtoResponse.Response getResponse() {
      return response_ == null ? ProtoResponse.Response.getDefaultInstance() : response_;
    }

    /**
     * <code>optional .proto.Response response = 1;</code>
     */
    public ProtoResponse.ResponseOrBuilder getResponseOrBuilder() {
      return getResponse();
    }

    public static final int TOKEN_FIELD_NUMBER = 2;
    private volatile Object token_;

    /**
     * <code>optional string token = 2;</code>
     */
    public String getToken() {
      Object ref = token_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        token_ = s;
        return s;
      }
    }

    /**
     * <code>optional string token = 2;</code>
     */
    public com.google.protobuf.ByteString
    getTokenBytes() {
      Object ref = token_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
                com.google.protobuf.ByteString.copyFromUtf8(
                        (String) ref);
        token_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NEW_USER_FIELD_NUMBER = 3;
    private boolean newUser_;

    /**
     * <code>optional bool new_user = 3;</code>
     */
    public boolean getNewUser() {
      return newUser_;
    }

    private byte memoizedIsInitialized = -1;

    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
            throws java.io.IOException {
      if (response_ != null) {
        output.writeMessage(1, getResponse());
      }
      if (!getTokenBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, token_);
      }
      if (newUser_ != false) {
        output.writeBool(3, newUser_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (response_ != null) {
        size += com.google.protobuf.CodedOutputStream
                .computeMessageSize(1, getResponse());
      }
      if (!getTokenBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, token_);
      }
      if (newUser_ != false) {
        size += com.google.protobuf.CodedOutputStream
                .computeBoolSize(3, newUser_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
        return true;
      }
      if (!(obj instanceof UserVerifyResponse)) {
        return super.equals(obj);
      }
      UserVerifyResponse other = (UserVerifyResponse) obj;

      boolean result = true;
      result = result && (hasResponse() == other.hasResponse());
      if (hasResponse()) {
        result = result && getResponse()
                .equals(other.getResponse());
      }
      result = result && getToken()
              .equals(other.getToken());
      result = result && (getNewUser()
              == other.getNewUser());
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasResponse()) {
        hash = (37 * hash) + RESPONSE_FIELD_NUMBER;
        hash = (53 * hash) + getResponse().hashCode();
      }
      hash = (37 * hash) + TOKEN_FIELD_NUMBER;
      hash = (53 * hash) + getToken().hashCode();
      hash = (37 * hash) + NEW_USER_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
              getNewUser());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static UserVerifyResponse parseFrom(
            com.google.protobuf.ByteString data)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }

    public static UserVerifyResponse parseFrom(
            com.google.protobuf.ByteString data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }

    public static UserVerifyResponse parseFrom(byte[] data)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }

    public static UserVerifyResponse parseFrom(
            byte[] data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }

    public static UserVerifyResponse parseFrom(java.io.InputStream input)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseWithIOException(PARSER, input);
    }

    public static UserVerifyResponse parseFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static UserVerifyResponse parseDelimitedFrom(java.io.InputStream input)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseDelimitedWithIOException(PARSER, input);
    }

    public static UserVerifyResponse parseDelimitedFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }

    public static UserVerifyResponse parseFrom(
            com.google.protobuf.CodedInputStream input)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseWithIOException(PARSER, input);
    }

    public static UserVerifyResponse parseFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() {
      return newBuilder();
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }

    public static Builder newBuilder(UserVerifyResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
              ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
            BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }

    /**
     * Protobuf type {@code proto.UserVerifyResponse}
     */
    public static final class Builder extends
            com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
            // @@protoc_insertion_point(builder_implements:proto.UserVerifyResponse)
            UserVerifyResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
        return ProtoUserVerify.internal_static_proto_UserVerifyResponse_descriptor;
      }

      protected FieldAccessorTable
      internalGetFieldAccessorTable() {
        return ProtoUserVerify.internal_static_proto_UserVerifyResponse_fieldAccessorTable
                .ensureFieldAccessorsInitialized(
                        UserVerifyResponse.class, Builder.class);
      }

      // Construct using com.iGap.proto.ProtoUserVerify.UserVerifyResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
              BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }

      public Builder clear() {
        super.clear();
        if (responseBuilder_ == null) {
          response_ = null;
        } else {
          response_ = null;
          responseBuilder_ = null;
        }
        token_ = "";

        newUser_ = false;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
      getDescriptorForType() {
        return ProtoUserVerify.internal_static_proto_UserVerifyResponse_descriptor;
      }

      public UserVerifyResponse getDefaultInstanceForType() {
        return UserVerifyResponse.getDefaultInstance();
      }

      public UserVerifyResponse build() {
        UserVerifyResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public UserVerifyResponse buildPartial() {
        UserVerifyResponse result = new UserVerifyResponse(this);
        if (responseBuilder_ == null) {
          result.response_ = response_;
        } else {
          result.response_ = responseBuilder_.build();
        }
        result.token_ = token_;
        result.newUser_ = newUser_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }

      public Builder setField(
              com.google.protobuf.Descriptors.FieldDescriptor field,
              Object value) {
        return (Builder) super.setField(field, value);
      }

      public Builder clearField(
              com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }

      public Builder clearOneof(
              com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }

      public Builder setRepeatedField(
              com.google.protobuf.Descriptors.FieldDescriptor field,
              int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }

      public Builder addRepeatedField(
              com.google.protobuf.Descriptors.FieldDescriptor field,
              Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof UserVerifyResponse) {
          return mergeFrom((UserVerifyResponse) other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(UserVerifyResponse other) {
        if (other == UserVerifyResponse.getDefaultInstance()) return this;
        if (other.hasResponse()) {
          mergeResponse(other.getResponse());
        }
        if (!other.getToken().isEmpty()) {
          token_ = other.token_;
          onChanged();
        }
        if (other.getNewUser() != false) {
          setNewUser(other.getNewUser());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
              com.google.protobuf.CodedInputStream input,
              com.google.protobuf.ExtensionRegistryLite extensionRegistry)
              throws java.io.IOException {
        UserVerifyResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (UserVerifyResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private ProtoResponse.Response response_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
              ProtoResponse.Response, ProtoResponse.Response.Builder, ProtoResponse.ResponseOrBuilder> responseBuilder_;

      /**
       * <code>optional .proto.Response response = 1;</code>
       */
      public boolean hasResponse() {
        return responseBuilder_ != null || response_ != null;
      }

      /**
       * <code>optional .proto.Response response = 1;</code>
       */
      public ProtoResponse.Response getResponse() {
        if (responseBuilder_ == null) {
          return response_ == null ? ProtoResponse.Response.getDefaultInstance() : response_;
        } else {
          return responseBuilder_.getMessage();
        }
      }

      /**
       * <code>optional .proto.Response response = 1;</code>
       */
      public Builder setResponse(ProtoResponse.Response value) {
        if (responseBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          response_ = value;
          onChanged();
        } else {
          responseBuilder_.setMessage(value);
        }

        return this;
      }

      /**
       * <code>optional .proto.Response response = 1;</code>
       */
      public Builder setResponse(
              ProtoResponse.Response.Builder builderForValue) {
        if (responseBuilder_ == null) {
          response_ = builderForValue.build();
          onChanged();
        } else {
          responseBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }

      /**
       * <code>optional .proto.Response response = 1;</code>
       */
      public Builder mergeResponse(ProtoResponse.Response value) {
        if (responseBuilder_ == null) {
          if (response_ != null) {
            response_ =
                    ProtoResponse.Response.newBuilder(response_).mergeFrom(value).buildPartial();
          } else {
            response_ = value;
          }
          onChanged();
        } else {
          responseBuilder_.mergeFrom(value);
        }

        return this;
      }

      /**
       * <code>optional .proto.Response response = 1;</code>
       */
      public Builder clearResponse() {
        if (responseBuilder_ == null) {
          response_ = null;
          onChanged();
        } else {
          response_ = null;
          responseBuilder_ = null;
        }

        return this;
      }

      /**
       * <code>optional .proto.Response response = 1;</code>
       */
      public ProtoResponse.Response.Builder getResponseBuilder() {

        onChanged();
        return getResponseFieldBuilder().getBuilder();
      }

      /**
       * <code>optional .proto.Response response = 1;</code>
       */
      public ProtoResponse.ResponseOrBuilder getResponseOrBuilder() {
        if (responseBuilder_ != null) {
          return responseBuilder_.getMessageOrBuilder();
        } else {
          return response_ == null ?
                  ProtoResponse.Response.getDefaultInstance() : response_;
        }
      }

      /**
       * <code>optional .proto.Response response = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
              ProtoResponse.Response, ProtoResponse.Response.Builder, ProtoResponse.ResponseOrBuilder>
      getResponseFieldBuilder() {
        if (responseBuilder_ == null) {
          responseBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
                  ProtoResponse.Response, ProtoResponse.Response.Builder, ProtoResponse.ResponseOrBuilder>(
                  getResponse(),
                  getParentForChildren(),
                  isClean());
          response_ = null;
        }
        return responseBuilder_;
      }

      private Object token_ = "";

      /**
       * <code>optional string token = 2;</code>
       */
      public String getToken() {
        Object ref = token_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
                  (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          token_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }

      /**
       * <code>optional string token = 2;</code>
       */
      public com.google.protobuf.ByteString
      getTokenBytes() {
        Object ref = token_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
                  com.google.protobuf.ByteString.copyFromUtf8(
                          (String) ref);
          token_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      /**
       * <code>optional string token = 2;</code>
       */
      public Builder setToken(
              String value) {
        if (value == null) {
          throw new NullPointerException();
        }

        token_ = value;
        onChanged();
        return this;
      }

      /**
       * <code>optional string token = 2;</code>
       */
      public Builder clearToken() {

        token_ = getDefaultInstance().getToken();
        onChanged();
        return this;
      }

      /**
       * <code>optional string token = 2;</code>
       */
      public Builder setTokenBytes(
              com.google.protobuf.ByteString value) {
        if (value == null) {
          throw new NullPointerException();
        }
        checkByteStringIsUtf8(value);

        token_ = value;
        onChanged();
        return this;
      }

      private boolean newUser_;

      /**
       * <code>optional bool new_user = 3;</code>
       */
      public boolean getNewUser() {
        return newUser_;
      }

      /**
       * <code>optional bool new_user = 3;</code>
       */
      public Builder setNewUser(boolean value) {

        newUser_ = value;
        onChanged();
        return this;
      }

      /**
       * <code>optional bool new_user = 3;</code>
       */
      public Builder clearNewUser() {

        newUser_ = false;
        onChanged();
        return this;
      }

      public final Builder setUnknownFields(
              final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
              final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:proto.UserVerifyResponse)
    }

    // @@protoc_insertion_point(class_scope:proto.UserVerifyResponse)
    private static final UserVerifyResponse DEFAULT_INSTANCE;

    static {
      DEFAULT_INSTANCE = new UserVerifyResponse();
    }

    public static UserVerifyResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<UserVerifyResponse>
            PARSER = new com.google.protobuf.AbstractParser<UserVerifyResponse>() {
      public UserVerifyResponse parsePartialFrom(
              com.google.protobuf.CodedInputStream input,
              com.google.protobuf.ExtensionRegistryLite extensionRegistry)
              throws com.google.protobuf.InvalidProtocolBufferException {
        return new UserVerifyResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<UserVerifyResponse> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<UserVerifyResponse> getParserForType() {
      return PARSER;
    }

    public UserVerifyResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
          internal_static_proto_UserVerify_descriptor;
  private static final
  com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internal_static_proto_UserVerify_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
          internal_static_proto_UserVerifyResponse_descriptor;
  private static final
  com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internal_static_proto_UserVerifyResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
  getDescriptor() {
    return descriptor;
  }

  private static com.google.protobuf.Descriptors.FileDescriptor
          descriptor;

  static {
    String[] descriptorData = {
            "\n\020UserVerify.proto\022\005proto\032\rRequest.proto" +
                    "\032\016Response.proto\"M\n\nUserVerify\022\037\n\007reques" +
                    "t\030\001 \001(\0132\016.proto.Request\022\014\n\004code\030\002 \001(\r\022\020\n" +
                    "\010username\030\003 \001(\t\"X\n\022UserVerifyResponse\022!\n" +
                    "\010response\030\001 \001(\0132\017.proto.Response\022\r\n\005toke" +
                    "n\030\002 \001(\t\022\020\n\010new_user\030\003 \001(\010B!\n\016com.iGap.pr" +
                    "otoB\017ProtoUserVerifyb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
            new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
              public com.google.protobuf.ExtensionRegistry assignDescriptors(
                      com.google.protobuf.Descriptors.FileDescriptor root) {
                descriptor = root;
                return null;
              }
            };
    com.google.protobuf.Descriptors.FileDescriptor
            .internalBuildGeneratedFileFrom(descriptorData,
                    new com.google.protobuf.Descriptors.FileDescriptor[]{
                            ProtoRequest.getDescriptor(),
                            ProtoResponse.getDescriptor(),
                    }, assigner);
    internal_static_proto_UserVerify_descriptor =
            getDescriptor().getMessageTypes().get(0);
    internal_static_proto_UserVerify_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_proto_UserVerify_descriptor,
        new String[] { "Request", "Code", "Username", });
    internal_static_proto_UserVerifyResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_proto_UserVerifyResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_UserVerifyResponse_descriptor,
        new String[] { "Response", "Token", "NewUser", });
    ProtoRequest.getDescriptor();
    ProtoResponse.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
