// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GroupSetAction.proto

package com.iGap.proto;

public final class ProtoGroupSetAction {
    private ProtoGroupSetAction() {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions(
                (com.google.protobuf.ExtensionRegistryLite) registry);
    }

    public interface GroupSetActionOrBuilder extends
            // @@protoc_insertion_point(interface_extends:proto.GroupSetAction)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>optional .proto.Request request = 1;</code>
         */
        boolean hasRequest();

        /**
         * <code>optional .proto.Request request = 1;</code>
         */
        ProtoRequest.Request getRequest();

        /**
         * <code>optional .proto.Request request = 1;</code>
         */
        ProtoRequest.RequestOrBuilder getRequestOrBuilder();

        /**
         * <code>optional uint64 room_id = 2;</code>
         */
        long getRoomId();

        /**
         * <code>optional .proto.ClientAction action = 3;</code>
         */
        int getActionValue();

        /**
         * <code>optional .proto.ClientAction action = 3;</code>
         */
        ProtoGlobal.ClientAction getAction();

        /**
         * <code>optional uint32 action_id = 4;</code>
         */
        int getActionId();
    }

    /**
     * Protobuf type {@code proto.GroupSetAction}
     */
    public static final class GroupSetAction extends
            com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:proto.GroupSetAction)
            GroupSetActionOrBuilder {
        // Use GroupSetAction.newBuilder() to construct.
        private GroupSetAction(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }

        private GroupSetAction() {
            roomId_ = 0L;
            action_ = 0;
            actionId_ = 0;
        }

        @Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
        }

        private GroupSetAction(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            this();
            int mutable_bitField0_ = 0;
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        default: {
                            if (!input.skipField(tag)) {
                                done = true;
                            }
                            break;
                        }
                        case 10: {
                            ProtoRequest.Request.Builder subBuilder = null;
                            if (request_ != null) {
                                subBuilder = request_.toBuilder();
                            }
                            request_ = input.readMessage(ProtoRequest.Request.parser(), extensionRegistry);
                            if (subBuilder != null) {
                                subBuilder.mergeFrom(request_);
                                request_ = subBuilder.buildPartial();
                            }

                            break;
                        }
                        case 16: {

                            roomId_ = input.readUInt64();
                            break;
                        }
                        case 24: {
                            int rawValue = input.readEnum();

                            action_ = rawValue;
                            break;
                        }
                        case 32: {

                            actionId_ = input.readUInt32();
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e).setUnfinishedMessage(this);
            } finally {
                makeExtensionsImmutable();
            }
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return ProtoGroupSetAction.internal_static_proto_GroupSetAction_descriptor;
        }

        protected FieldAccessorTable
        internalGetFieldAccessorTable() {
            return ProtoGroupSetAction.internal_static_proto_GroupSetAction_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            GroupSetAction.class, Builder.class);
        }

        public static final int REQUEST_FIELD_NUMBER = 1;
        private ProtoRequest.Request request_;

        /**
         * <code>optional .proto.Request request = 1;</code>
         */
        public boolean hasRequest() {
            return request_ != null;
        }

        /**
         * <code>optional .proto.Request request = 1;</code>
         */
        public ProtoRequest.Request getRequest() {
            return request_ == null ? ProtoRequest.Request.getDefaultInstance() : request_;
        }

        /**
         * <code>optional .proto.Request request = 1;</code>
         */
        public ProtoRequest.RequestOrBuilder getRequestOrBuilder() {
            return getRequest();
        }

        public static final int ROOM_ID_FIELD_NUMBER = 2;
        private long roomId_;

        /**
         * <code>optional uint64 room_id = 2;</code>
         */
        public long getRoomId() {
            return roomId_;
        }

        public static final int ACTION_FIELD_NUMBER = 3;
        private int action_;

        /**
         * <code>optional .proto.ClientAction action = 3;</code>
         */
        public int getActionValue() {
            return action_;
        }

        /**
         * <code>optional .proto.ClientAction action = 3;</code>
         */
        public ProtoGlobal.ClientAction getAction() {
            ProtoGlobal.ClientAction result = ProtoGlobal.ClientAction.valueOf(action_);
            return result == null ? ProtoGlobal.ClientAction.UNRECOGNIZED : result;
        }

        public static final int ACTION_ID_FIELD_NUMBER = 4;
        private int actionId_;

        /**
         * <code>optional uint32 action_id = 4;</code>
         */
        public int getActionId() {
            return actionId_;
        }

        private byte memoizedIsInitialized = -1;

        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            if (request_ != null) {
                output.writeMessage(1, getRequest());
            }
            if (roomId_ != 0L) {
                output.writeUInt64(2, roomId_);
            }
            if (action_ != ProtoGlobal.ClientAction.CANCEL.getNumber()) {
                output.writeEnum(3, action_);
            }
            if (actionId_ != 0) {
                output.writeUInt32(4, actionId_);
            }
        }

        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            if (request_ != null) {
                size += com.google.protobuf.CodedOutputStream
                        .computeMessageSize(1, getRequest());
            }
            if (roomId_ != 0L) {
                size += com.google.protobuf.CodedOutputStream
                        .computeUInt64Size(2, roomId_);
            }
            if (action_ != ProtoGlobal.ClientAction.CANCEL.getNumber()) {
                size += com.google.protobuf.CodedOutputStream
                        .computeEnumSize(3, action_);
            }
            if (actionId_ != 0) {
                size += com.google.protobuf.CodedOutputStream
                        .computeUInt32Size(4, actionId_);
            }
            memoizedSize = size;
            return size;
        }

        private static final long serialVersionUID = 0L;

        @Override
        public boolean equals(final Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof GroupSetAction)) {
                return super.equals(obj);
            }
            GroupSetAction other = (GroupSetAction) obj;

            boolean result = true;
            result = result && (hasRequest() == other.hasRequest());
            if (hasRequest()) {
                result = result && getRequest()
                        .equals(other.getRequest());
            }
            result = result && (getRoomId()
                    == other.getRoomId());
            result = result && action_ == other.action_;
            result = result && (getActionId()
                    == other.getActionId());
            return result;
        }

        @Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptorForType().hashCode();
            if (hasRequest()) {
                hash = (37 * hash) + REQUEST_FIELD_NUMBER;
                hash = (53 * hash) + getRequest().hashCode();
            }
            hash = (37 * hash) + ROOM_ID_FIELD_NUMBER;
            hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
                    getRoomId());
            hash = (37 * hash) + ACTION_FIELD_NUMBER;
            hash = (53 * hash) + action_;
            hash = (37 * hash) + ACTION_ID_FIELD_NUMBER;
            hash = (53 * hash) + getActionId();
            hash = (29 * hash) + unknownFields.hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public static GroupSetAction parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static GroupSetAction parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static GroupSetAction parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static GroupSetAction parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static GroupSetAction parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static GroupSetAction parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static GroupSetAction parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input);
        }

        public static GroupSetAction parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }

        public static GroupSetAction parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static GroupSetAction parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public Builder newBuilderForType() {
            return newBuilder();
        }

        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(GroupSetAction prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @Override
        protected Builder newBuilderForType(
                BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        /**
         * Protobuf type {@code proto.GroupSetAction}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:proto.GroupSetAction)
                GroupSetActionOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return ProtoGroupSetAction.internal_static_proto_GroupSetAction_descriptor;
            }

            protected FieldAccessorTable
            internalGetFieldAccessorTable() {
                return ProtoGroupSetAction.internal_static_proto_GroupSetAction_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                GroupSetAction.class, Builder.class);
            }

            // Construct using com.iGap.proto.ProtoGroupSetAction.GroupSetAction.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessageV3
                        .alwaysUseFieldBuilders) {
                }
            }

            public Builder clear() {
                super.clear();
                if (requestBuilder_ == null) {
                    request_ = null;
                } else {
                    request_ = null;
                    requestBuilder_ = null;
                }
                roomId_ = 0L;

                action_ = 0;

                actionId_ = 0;

                return this;
            }

            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return ProtoGroupSetAction.internal_static_proto_GroupSetAction_descriptor;
            }

            public GroupSetAction getDefaultInstanceForType() {
                return GroupSetAction.getDefaultInstance();
            }

            public GroupSetAction build() {
                GroupSetAction result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            public GroupSetAction buildPartial() {
                GroupSetAction result = new GroupSetAction(this);
                if (requestBuilder_ == null) {
                    result.request_ = request_;
                } else {
                    result.request_ = requestBuilder_.build();
                }
                result.roomId_ = roomId_;
                result.action_ = action_;
                result.actionId_ = actionId_;
                onBuilt();
                return result;
            }

            public Builder clone() {
                return (Builder) super.clone();
            }

            public Builder setField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    Object value) {
                return (Builder) super.setField(field, value);
            }

            public Builder clearField(
                    com.google.protobuf.Descriptors.FieldDescriptor field) {
                return (Builder) super.clearField(field);
            }

            public Builder clearOneof(
                    com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return (Builder) super.clearOneof(oneof);
            }

            public Builder setRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    int index, Object value) {
                return (Builder) super.setRepeatedField(field, index, value);
            }

            public Builder addRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    Object value) {
                return (Builder) super.addRepeatedField(field, value);
            }

            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof GroupSetAction) {
                    return mergeFrom((GroupSetAction) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(GroupSetAction other) {
                if (other == GroupSetAction.getDefaultInstance()) return this;
                if (other.hasRequest()) {
                    mergeRequest(other.getRequest());
                }
                if (other.getRoomId() != 0L) {
                    setRoomId(other.getRoomId());
                }
                if (other.action_ != 0) {
                    setActionValue(other.getActionValue());
                }
                if (other.getActionId() != 0) {
                    setActionId(other.getActionId());
                }
                onChanged();
                return this;
            }

            public final boolean isInitialized() {
                return true;
            }

            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                GroupSetAction parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (GroupSetAction) e.getUnfinishedMessage();
                    throw e.unwrapIOException();
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            private ProtoRequest.Request request_ = null;
            private com.google.protobuf.SingleFieldBuilderV3<
                    ProtoRequest.Request, ProtoRequest.Request.Builder, ProtoRequest.RequestOrBuilder> requestBuilder_;

            /**
             * <code>optional .proto.Request request = 1;</code>
             */
            public boolean hasRequest() {
                return requestBuilder_ != null || request_ != null;
            }

            /**
             * <code>optional .proto.Request request = 1;</code>
             */
            public ProtoRequest.Request getRequest() {
                if (requestBuilder_ == null) {
                    return request_ == null ? ProtoRequest.Request.getDefaultInstance() : request_;
                } else {
                    return requestBuilder_.getMessage();
                }
            }

            /**
             * <code>optional .proto.Request request = 1;</code>
             */
            public Builder setRequest(ProtoRequest.Request value) {
                if (requestBuilder_ == null) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    request_ = value;
                    onChanged();
                } else {
                    requestBuilder_.setMessage(value);
                }

                return this;
            }

            /**
             * <code>optional .proto.Request request = 1;</code>
             */
            public Builder setRequest(
                    ProtoRequest.Request.Builder builderForValue) {
                if (requestBuilder_ == null) {
                    request_ = builderForValue.build();
                    onChanged();
                } else {
                    requestBuilder_.setMessage(builderForValue.build());
                }

                return this;
            }

            /**
             * <code>optional .proto.Request request = 1;</code>
             */
            public Builder mergeRequest(ProtoRequest.Request value) {
                if (requestBuilder_ == null) {
                    if (request_ != null) {
                        request_ =
                                ProtoRequest.Request.newBuilder(request_).mergeFrom(value).buildPartial();
                    } else {
                        request_ = value;
                    }
                    onChanged();
                } else {
                    requestBuilder_.mergeFrom(value);
                }

                return this;
            }

            /**
             * <code>optional .proto.Request request = 1;</code>
             */
            public Builder clearRequest() {
                if (requestBuilder_ == null) {
                    request_ = null;
                    onChanged();
                } else {
                    request_ = null;
                    requestBuilder_ = null;
                }

                return this;
            }

            /**
             * <code>optional .proto.Request request = 1;</code>
             */
            public ProtoRequest.Request.Builder getRequestBuilder() {

                onChanged();
                return getRequestFieldBuilder().getBuilder();
            }

            /**
             * <code>optional .proto.Request request = 1;</code>
             */
            public ProtoRequest.RequestOrBuilder getRequestOrBuilder() {
                if (requestBuilder_ != null) {
                    return requestBuilder_.getMessageOrBuilder();
                } else {
                    return request_ == null ?
                            ProtoRequest.Request.getDefaultInstance() : request_;
                }
            }

            /**
             * <code>optional .proto.Request request = 1;</code>
             */
            private com.google.protobuf.SingleFieldBuilderV3<
                    ProtoRequest.Request, ProtoRequest.Request.Builder, ProtoRequest.RequestOrBuilder>
            getRequestFieldBuilder() {
                if (requestBuilder_ == null) {
                    requestBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
                            ProtoRequest.Request, ProtoRequest.Request.Builder, ProtoRequest.RequestOrBuilder>(
                            getRequest(),
                            getParentForChildren(),
                            isClean());
                    request_ = null;
                }
                return requestBuilder_;
            }

            private long roomId_;

            /**
             * <code>optional uint64 room_id = 2;</code>
             */
            public long getRoomId() {
                return roomId_;
            }

            /**
             * <code>optional uint64 room_id = 2;</code>
             */
            public Builder setRoomId(long value) {

                roomId_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>optional uint64 room_id = 2;</code>
             */
            public Builder clearRoomId() {

                roomId_ = 0L;
                onChanged();
                return this;
            }

            private int action_ = 0;

            /**
             * <code>optional .proto.ClientAction action = 3;</code>
             */
            public int getActionValue() {
                return action_;
            }

            /**
             * <code>optional .proto.ClientAction action = 3;</code>
             */
            public Builder setActionValue(int value) {
                action_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>optional .proto.ClientAction action = 3;</code>
             */
            public ProtoGlobal.ClientAction getAction() {
                ProtoGlobal.ClientAction result = ProtoGlobal.ClientAction.valueOf(action_);
                return result == null ? ProtoGlobal.ClientAction.UNRECOGNIZED : result;
            }

            /**
             * <code>optional .proto.ClientAction action = 3;</code>
             */
            public Builder setAction(ProtoGlobal.ClientAction value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                action_ = value.getNumber();
                onChanged();
                return this;
            }

            /**
             * <code>optional .proto.ClientAction action = 3;</code>
             */
            public Builder clearAction() {

                action_ = 0;
                onChanged();
                return this;
            }

            private int actionId_;

            /**
             * <code>optional uint32 action_id = 4;</code>
             */
            public int getActionId() {
                return actionId_;
            }

            /**
             * <code>optional uint32 action_id = 4;</code>
             */
            public Builder setActionId(int value) {

                actionId_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>optional uint32 action_id = 4;</code>
             */
            public Builder clearActionId() {

                actionId_ = 0;
                onChanged();
                return this;
            }

            public final Builder setUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return this;
            }

            public final Builder mergeUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return this;
            }


            // @@protoc_insertion_point(builder_scope:proto.GroupSetAction)
        }

        // @@protoc_insertion_point(class_scope:proto.GroupSetAction)
        private static final GroupSetAction DEFAULT_INSTANCE;

        static {
            DEFAULT_INSTANCE = new GroupSetAction();
        }

        public static GroupSetAction getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        private static final com.google.protobuf.Parser<GroupSetAction>
                PARSER = new com.google.protobuf.AbstractParser<GroupSetAction>() {
            public GroupSetAction parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return new GroupSetAction(input, extensionRegistry);
            }
        };

        public static com.google.protobuf.Parser<GroupSetAction> parser() {
            return PARSER;
        }

        @Override
        public com.google.protobuf.Parser<GroupSetAction> getParserForType() {
            return PARSER;
        }

        public GroupSetAction getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

    }

    public interface GroupSetActionResponseOrBuilder extends
            // @@protoc_insertion_point(interface_extends:proto.GroupSetActionResponse)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>optional .proto.Response response = 1;</code>
         */
        boolean hasResponse();

        /**
         * <code>optional .proto.Response response = 1;</code>
         */
        ProtoResponse.Response getResponse();

        /**
         * <code>optional .proto.Response response = 1;</code>
         */
        ProtoResponse.ResponseOrBuilder getResponseOrBuilder();

        /**
         * <code>optional uint64 room_id = 2;</code>
         */
        long getRoomId();

        /**
         * <code>optional .proto.ClientAction action = 3;</code>
         */
        int getActionValue();

        /**
         * <code>optional .proto.ClientAction action = 3;</code>
         */
        ProtoGlobal.ClientAction getAction();

        /**
         * <code>optional uint64 user_id = 4;</code>
         */
        long getUserId();
    }

    /**
     * Protobuf type {@code proto.GroupSetActionResponse}
     */
    public static final class GroupSetActionResponse extends
            com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:proto.GroupSetActionResponse)
            GroupSetActionResponseOrBuilder {
        // Use GroupSetActionResponse.newBuilder() to construct.
        private GroupSetActionResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }

        private GroupSetActionResponse() {
            roomId_ = 0L;
            action_ = 0;
            userId_ = 0L;
        }

        @Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
        }

        private GroupSetActionResponse(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            this();
            int mutable_bitField0_ = 0;
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        default: {
                            if (!input.skipField(tag)) {
                                done = true;
                            }
                            break;
                        }
                        case 10: {
                            ProtoResponse.Response.Builder subBuilder = null;
                            if (response_ != null) {
                                subBuilder = response_.toBuilder();
                            }
                            response_ = input.readMessage(ProtoResponse.Response.parser(), extensionRegistry);
                            if (subBuilder != null) {
                                subBuilder.mergeFrom(response_);
                                response_ = subBuilder.buildPartial();
                            }

                            break;
                        }
                        case 16: {

                            roomId_ = input.readUInt64();
                            break;
                        }
                        case 24: {
                            int rawValue = input.readEnum();

                            action_ = rawValue;
                            break;
                        }
                        case 32: {

                            userId_ = input.readUInt64();
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e).setUnfinishedMessage(this);
            } finally {
                makeExtensionsImmutable();
            }
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return ProtoGroupSetAction.internal_static_proto_GroupSetActionResponse_descriptor;
        }

        protected FieldAccessorTable
        internalGetFieldAccessorTable() {
            return ProtoGroupSetAction.internal_static_proto_GroupSetActionResponse_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            GroupSetActionResponse.class, Builder.class);
        }

        public static final int RESPONSE_FIELD_NUMBER = 1;
        private ProtoResponse.Response response_;

        /**
         * <code>optional .proto.Response response = 1;</code>
         */
        public boolean hasResponse() {
            return response_ != null;
        }

        /**
         * <code>optional .proto.Response response = 1;</code>
         */
        public ProtoResponse.Response getResponse() {
            return response_ == null ? ProtoResponse.Response.getDefaultInstance() : response_;
        }

        /**
         * <code>optional .proto.Response response = 1;</code>
         */
        public ProtoResponse.ResponseOrBuilder getResponseOrBuilder() {
            return getResponse();
        }

        public static final int ROOM_ID_FIELD_NUMBER = 2;
        private long roomId_;

        /**
         * <code>optional uint64 room_id = 2;</code>
         */
        public long getRoomId() {
            return roomId_;
        }

        public static final int ACTION_FIELD_NUMBER = 3;
        private int action_;

        /**
         * <code>optional .proto.ClientAction action = 3;</code>
         */
        public int getActionValue() {
            return action_;
        }

        /**
         * <code>optional .proto.ClientAction action = 3;</code>
         */
        public ProtoGlobal.ClientAction getAction() {
            ProtoGlobal.ClientAction result = ProtoGlobal.ClientAction.valueOf(action_);
            return result == null ? ProtoGlobal.ClientAction.UNRECOGNIZED : result;
        }

        public static final int USER_ID_FIELD_NUMBER = 4;
        private long userId_;

        /**
         * <code>optional uint64 user_id = 4;</code>
         */
        public long getUserId() {
            return userId_;
        }

        private byte memoizedIsInitialized = -1;

        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            if (response_ != null) {
                output.writeMessage(1, getResponse());
            }
            if (roomId_ != 0L) {
                output.writeUInt64(2, roomId_);
            }
            if (action_ != ProtoGlobal.ClientAction.CANCEL.getNumber()) {
                output.writeEnum(3, action_);
            }
            if (userId_ != 0L) {
                output.writeUInt64(4, userId_);
            }
        }

        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            if (response_ != null) {
                size += com.google.protobuf.CodedOutputStream
                        .computeMessageSize(1, getResponse());
            }
            if (roomId_ != 0L) {
                size += com.google.protobuf.CodedOutputStream
                        .computeUInt64Size(2, roomId_);
            }
            if (action_ != ProtoGlobal.ClientAction.CANCEL.getNumber()) {
                size += com.google.protobuf.CodedOutputStream
                        .computeEnumSize(3, action_);
            }
            if (userId_ != 0L) {
                size += com.google.protobuf.CodedOutputStream
                        .computeUInt64Size(4, userId_);
            }
            memoizedSize = size;
            return size;
        }

        private static final long serialVersionUID = 0L;

        @Override
        public boolean equals(final Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof GroupSetActionResponse)) {
                return super.equals(obj);
            }
            GroupSetActionResponse other = (GroupSetActionResponse) obj;

            boolean result = true;
            result = result && (hasResponse() == other.hasResponse());
            if (hasResponse()) {
                result = result && getResponse()
                        .equals(other.getResponse());
            }
            result = result && (getRoomId()
                    == other.getRoomId());
            result = result && action_ == other.action_;
            result = result && (getUserId()
                    == other.getUserId());
            return result;
        }

        @Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptorForType().hashCode();
            if (hasResponse()) {
                hash = (37 * hash) + RESPONSE_FIELD_NUMBER;
                hash = (53 * hash) + getResponse().hashCode();
            }
            hash = (37 * hash) + ROOM_ID_FIELD_NUMBER;
            hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
                    getRoomId());
            hash = (37 * hash) + ACTION_FIELD_NUMBER;
            hash = (53 * hash) + action_;
            hash = (37 * hash) + USER_ID_FIELD_NUMBER;
            hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
                    getUserId());
            hash = (29 * hash) + unknownFields.hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public static GroupSetActionResponse parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static GroupSetActionResponse parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static GroupSetActionResponse parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static GroupSetActionResponse parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static GroupSetActionResponse parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static GroupSetActionResponse parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static GroupSetActionResponse parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input);
        }

        public static GroupSetActionResponse parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }

        public static GroupSetActionResponse parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static GroupSetActionResponse parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public Builder newBuilderForType() {
            return newBuilder();
        }

        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(GroupSetActionResponse prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @Override
        protected Builder newBuilderForType(
                BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        /**
         * Protobuf type {@code proto.GroupSetActionResponse}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:proto.GroupSetActionResponse)
                GroupSetActionResponseOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return ProtoGroupSetAction.internal_static_proto_GroupSetActionResponse_descriptor;
            }

            protected FieldAccessorTable
            internalGetFieldAccessorTable() {
                return ProtoGroupSetAction.internal_static_proto_GroupSetActionResponse_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                GroupSetActionResponse.class, Builder.class);
            }

            // Construct using com.iGap.proto.ProtoGroupSetAction.GroupSetActionResponse.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessageV3
                        .alwaysUseFieldBuilders) {
                }
            }

            public Builder clear() {
                super.clear();
                if (responseBuilder_ == null) {
                    response_ = null;
                } else {
                    response_ = null;
                    responseBuilder_ = null;
                }
                roomId_ = 0L;

                action_ = 0;

                userId_ = 0L;

                return this;
            }

            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return ProtoGroupSetAction.internal_static_proto_GroupSetActionResponse_descriptor;
            }

            public GroupSetActionResponse getDefaultInstanceForType() {
                return GroupSetActionResponse.getDefaultInstance();
            }

            public GroupSetActionResponse build() {
                GroupSetActionResponse result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            public GroupSetActionResponse buildPartial() {
                GroupSetActionResponse result = new GroupSetActionResponse(this);
                if (responseBuilder_ == null) {
                    result.response_ = response_;
                } else {
                    result.response_ = responseBuilder_.build();
                }
                result.roomId_ = roomId_;
                result.action_ = action_;
                result.userId_ = userId_;
                onBuilt();
                return result;
            }

            public Builder clone() {
                return (Builder) super.clone();
            }

            public Builder setField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    Object value) {
                return (Builder) super.setField(field, value);
            }

            public Builder clearField(
                    com.google.protobuf.Descriptors.FieldDescriptor field) {
                return (Builder) super.clearField(field);
            }

            public Builder clearOneof(
                    com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return (Builder) super.clearOneof(oneof);
            }

            public Builder setRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    int index, Object value) {
                return (Builder) super.setRepeatedField(field, index, value);
            }

            public Builder addRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    Object value) {
                return (Builder) super.addRepeatedField(field, value);
            }

            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof GroupSetActionResponse) {
                    return mergeFrom((GroupSetActionResponse) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(GroupSetActionResponse other) {
                if (other == GroupSetActionResponse.getDefaultInstance()) return this;
                if (other.hasResponse()) {
                    mergeResponse(other.getResponse());
                }
                if (other.getRoomId() != 0L) {
                    setRoomId(other.getRoomId());
                }
                if (other.action_ != 0) {
                    setActionValue(other.getActionValue());
                }
                if (other.getUserId() != 0L) {
                    setUserId(other.getUserId());
                }
                onChanged();
                return this;
            }

            public final boolean isInitialized() {
                return true;
            }

            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                GroupSetActionResponse parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (GroupSetActionResponse) e.getUnfinishedMessage();
                    throw e.unwrapIOException();
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            private ProtoResponse.Response response_ = null;
            private com.google.protobuf.SingleFieldBuilderV3<
                    ProtoResponse.Response, ProtoResponse.Response.Builder, ProtoResponse.ResponseOrBuilder> responseBuilder_;

            /**
             * <code>optional .proto.Response response = 1;</code>
             */
            public boolean hasResponse() {
                return responseBuilder_ != null || response_ != null;
            }

            /**
             * <code>optional .proto.Response response = 1;</code>
             */
            public ProtoResponse.Response getResponse() {
                if (responseBuilder_ == null) {
                    return response_ == null ? ProtoResponse.Response.getDefaultInstance() : response_;
                } else {
                    return responseBuilder_.getMessage();
                }
            }

            /**
             * <code>optional .proto.Response response = 1;</code>
             */
            public Builder setResponse(ProtoResponse.Response value) {
                if (responseBuilder_ == null) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    response_ = value;
                    onChanged();
                } else {
                    responseBuilder_.setMessage(value);
                }

                return this;
            }

            /**
             * <code>optional .proto.Response response = 1;</code>
             */
            public Builder setResponse(
                    ProtoResponse.Response.Builder builderForValue) {
                if (responseBuilder_ == null) {
                    response_ = builderForValue.build();
                    onChanged();
                } else {
                    responseBuilder_.setMessage(builderForValue.build());
                }

                return this;
            }

            /**
             * <code>optional .proto.Response response = 1;</code>
             */
            public Builder mergeResponse(ProtoResponse.Response value) {
                if (responseBuilder_ == null) {
                    if (response_ != null) {
                        response_ =
                                ProtoResponse.Response.newBuilder(response_).mergeFrom(value).buildPartial();
                    } else {
                        response_ = value;
                    }
                    onChanged();
                } else {
                    responseBuilder_.mergeFrom(value);
                }

                return this;
            }

            /**
             * <code>optional .proto.Response response = 1;</code>
             */
            public Builder clearResponse() {
                if (responseBuilder_ == null) {
                    response_ = null;
                    onChanged();
                } else {
                    response_ = null;
                    responseBuilder_ = null;
                }

                return this;
            }

            /**
             * <code>optional .proto.Response response = 1;</code>
             */
            public ProtoResponse.Response.Builder getResponseBuilder() {

                onChanged();
                return getResponseFieldBuilder().getBuilder();
            }

            /**
             * <code>optional .proto.Response response = 1;</code>
             */
            public ProtoResponse.ResponseOrBuilder getResponseOrBuilder() {
                if (responseBuilder_ != null) {
                    return responseBuilder_.getMessageOrBuilder();
                } else {
                    return response_ == null ?
                            ProtoResponse.Response.getDefaultInstance() : response_;
                }
            }

            /**
             * <code>optional .proto.Response response = 1;</code>
             */
            private com.google.protobuf.SingleFieldBuilderV3<
                    ProtoResponse.Response, ProtoResponse.Response.Builder, ProtoResponse.ResponseOrBuilder>
            getResponseFieldBuilder() {
                if (responseBuilder_ == null) {
                    responseBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
                            ProtoResponse.Response, ProtoResponse.Response.Builder, ProtoResponse.ResponseOrBuilder>(
                            getResponse(),
                            getParentForChildren(),
                            isClean());
                    response_ = null;
                }
                return responseBuilder_;
            }

            private long roomId_;

            /**
             * <code>optional uint64 room_id = 2;</code>
             */
            public long getRoomId() {
                return roomId_;
            }

            /**
             * <code>optional uint64 room_id = 2;</code>
             */
            public Builder setRoomId(long value) {

                roomId_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>optional uint64 room_id = 2;</code>
             */
            public Builder clearRoomId() {

                roomId_ = 0L;
                onChanged();
                return this;
            }

            private int action_ = 0;

            /**
             * <code>optional .proto.ClientAction action = 3;</code>
             */
            public int getActionValue() {
                return action_;
            }

            /**
             * <code>optional .proto.ClientAction action = 3;</code>
             */
            public Builder setActionValue(int value) {
                action_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>optional .proto.ClientAction action = 3;</code>
             */
            public ProtoGlobal.ClientAction getAction() {
                ProtoGlobal.ClientAction result = ProtoGlobal.ClientAction.valueOf(action_);
                return result == null ? ProtoGlobal.ClientAction.UNRECOGNIZED : result;
            }

            /**
             * <code>optional .proto.ClientAction action = 3;</code>
             */
            public Builder setAction(ProtoGlobal.ClientAction value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                action_ = value.getNumber();
                onChanged();
                return this;
            }

            /**
             * <code>optional .proto.ClientAction action = 3;</code>
             */
            public Builder clearAction() {

                action_ = 0;
                onChanged();
                return this;
            }

            private long userId_;

            /**
             * <code>optional uint64 user_id = 4;</code>
             */
            public long getUserId() {
                return userId_;
            }

            /**
             * <code>optional uint64 user_id = 4;</code>
             */
            public Builder setUserId(long value) {

                userId_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>optional uint64 user_id = 4;</code>
             */
            public Builder clearUserId() {

                userId_ = 0L;
                onChanged();
                return this;
            }

            public final Builder setUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return this;
            }

            public final Builder mergeUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return this;
            }


            // @@protoc_insertion_point(builder_scope:proto.GroupSetActionResponse)
        }

        // @@protoc_insertion_point(class_scope:proto.GroupSetActionResponse)
        private static final GroupSetActionResponse DEFAULT_INSTANCE;

        static {
            DEFAULT_INSTANCE = new GroupSetActionResponse();
        }

        public static GroupSetActionResponse getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        private static final com.google.protobuf.Parser<GroupSetActionResponse>
                PARSER = new com.google.protobuf.AbstractParser<GroupSetActionResponse>() {
            public GroupSetActionResponse parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return new GroupSetActionResponse(input, extensionRegistry);
            }
        };

        public static com.google.protobuf.Parser<GroupSetActionResponse> parser() {
            return PARSER;
        }

        @Override
        public com.google.protobuf.Parser<GroupSetActionResponse> getParserForType() {
            return PARSER;
        }

        public GroupSetActionResponse getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

    }

    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_proto_GroupSetAction_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_proto_GroupSetAction_fieldAccessorTable;
    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_proto_GroupSetActionResponse_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_proto_GroupSetActionResponse_fieldAccessorTable;

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }

    private static com.google.protobuf.Descriptors.FileDescriptor
            descriptor;

    static {
        String[] descriptorData = {
                "\n\024GroupSetAction.proto\022\005proto\032\rRequest.p" +
                        "roto\032\016Response.proto\032\014Global.proto\"z\n\016Gr" +
                        "oupSetAction\022\037\n\007request\030\001 \001(\0132\016.proto.Re" +
                        "quest\022\017\n\007room_id\030\002 \001(\004\022#\n\006action\030\003 \001(\0162\023" +
                        ".proto.ClientAction\022\021\n\taction_id\030\004 \001(\r\"\202" +
                        "\001\n\026GroupSetActionResponse\022!\n\010response\030\001 " +
                        "\001(\0132\017.proto.Response\022\017\n\007room_id\030\002 \001(\004\022#\n" +
                        "\006action\030\003 \001(\0162\023.proto.ClientAction\022\017\n\007us" +
                        "er_id\030\004 \001(\004B%\n\016com.iGap.protoB\023ProtoGrou" +
                        "pSetActionb\006proto3"
        };
        com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
                new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
                    public com.google.protobuf.ExtensionRegistry assignDescriptors(
                            com.google.protobuf.Descriptors.FileDescriptor root) {
                        descriptor = root;
                        return null;
                    }
                };
        com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[]{
                                ProtoRequest.getDescriptor(),
                                ProtoResponse.getDescriptor(),
                                ProtoGlobal.getDescriptor(),
                        }, assigner);
        internal_static_proto_GroupSetAction_descriptor =
                getDescriptor().getMessageTypes().get(0);
        internal_static_proto_GroupSetAction_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_proto_GroupSetAction_descriptor,
                new String[]{"Request", "RoomId", "Action", "ActionId",});
        internal_static_proto_GroupSetActionResponse_descriptor =
                getDescriptor().getMessageTypes().get(1);
        internal_static_proto_GroupSetActionResponse_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_proto_GroupSetActionResponse_descriptor,
                new String[]{"Response", "RoomId", "Action", "UserId",});
        ProtoRequest.getDescriptor();
        ProtoResponse.getDescriptor();
        ProtoGlobal.getDescriptor();
    }

    // @@protoc_insertion_point(outer_class_scope)
}
